### ISSUE TITLE
Undocumented breaking change for "flat" error enums

### ISSUE THREAD

**Issue by rfk** [mozilla/uniffi-rs#1024]
When we introduced the new "rich" structured error enums, we also introduced an undocumented (maybe unintended?) change to the behaviour of "flat" error enums. Consider an error declared like:

```
[Error]
enum LoginsStorageError {
    "SyncAuthInvalid",
    "MismatchedLock",
    ... others omitted ...
};
```

Prior to v0.13, the generated bindings for this error would be an enum-shaped thing where each variant has a `message` field, and we'd populate the `message` field using the stringification of the Rust-side error. Taking Swift as an example, calling code would match on it like this:

```
switch err{
    case .SyncAuthInvalid(message)
        log.error(message)
    ... others omitted ...
}
```

With v0.13, the generated bindings for this error are now an enum-shaped thing with no fields, and no way to access more info about the error. The Swift calling code now needs to look like this:

```
switch err{
    case .SyncAuthInvalid
        log.error("invalid auth")
    ... others omitted ...
}
```

It's not clear from the changelog that this has occurred, why, or what to do about it.

I figure we have two options, depending on what we think about the new behaviour.

#### 1) Document how to migrate and restore the previous behaviour.

Here, we decide that the new behaviour is a keeper and we update the changelog with a note about the breaking change and some details on how to best migrate to the new richer enums. In theory, consumers can declare an explicit `message` field on enums and populate it on the Rust side to get back to the old behaviour. We should test this out to see if it actually works before committing to it.

#### 2) Revert flat error enums to their previous behaviour.

Here, we decide that this change isn't good for consumers on balance, because they *probably* want to know the underlying error message. We figure out how to revert flat enums to the previous behaviour while keeping the new rich structured enums as they are. Two downsides to watch out for:

* This is probably non-trivial in codegen, we'd have to keep an eye on the complexity.
* This is technically semver-breaking for anyone who already migrated to the v0.13 behaviour.

Any strong opinions on the right way to proceed?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-81)
┆Issue Number: UNIFFI-81
┆Sprint End Date: 2021-08-20

**Comment by rfk** [comment]
(FWIW, my very-weakly-held opinion is that (2) is the better option for consumers, including ourselves...but only if the complexity doesn't get away from us).

**Comment by mhammond** [comment]
yes, FWIW I agree that (2) is what we should do. app-services probably still should lean into richer enums but it's not clear how that will work out in practice given it really does also want the stringified error

**Comment by rfk** [comment]
Cross-linking the original "rich structured enums" PR for context: https://github.com/mozilla/uniffi-rs/pull/983

**Comment by rfk** [comment]
> 2) Revert flat error enums to their previous behaviour.

I've started exploring an implementation of this over in https://github.com/mozilla/uniffi-rs/pull/1025
