### ISSUE TITLE
Move templates from multi-line strings to their own files

### ISSUE THREAD

**Issue by jhugman** [mozilla/uniffi-rs#1047]
#993 and #1042 moved swift and kotlin types from one giant template file to many different multi-line strings in Rust.

This issue is about moving these multi-line strings in lots of small template files, so that syntax highlighting can work again for the foreign languages.

The types with the strings are in `compounds.rs`, `primitives.rs` and `miscellany.rs`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-87)
┆Issue Number: UNIFFI-87

**Comment by bendk** [comment]
[This PR](https://github.com/mozilla/uniffi-rs/pull/1052) covers Kotlin, so just focus on Swift
