### ISSUE TITLE
uniffi-bindgen 0.14.0 - Swift errors with associated data do not conform with the Error protocol

### ISSUE THREAD

**Issue by AlexDBlack** [mozilla/uniffi-rs#1067]
Related: https://github.com/mozilla/uniffi-rs/issues/1062
Note it's a different problem and fix required (i.e., fixing #1062 won't fix this), but this Swift code generation issue can be reproduced with the same test case.

In Uniffi, it's possible to define errors in two ways:
`[Error] enum MyError` - with String messages
`[Enum] interface MyError` - with arbitrary associated data
https://mozilla.github.io/uniffi-rs/udl/errors.html

Using the latter produces Swift error enumerations that do not conform with the Error protocol.

Interface definition:
```
namespace test {
    [Throws=TestError]
    string foo();
};

[Enum]
interface TestError {
    FirstError(string err);
    SecondError(u32 value);
};
```

Generated Swift enumeration (error) and function call:
```swift
public enum TestError {
    case firstError(err: String )
    case secondError(value: UInt32 )
}

public func foo() throws -> String {
    let _retval = try
    
    
    rustCallWithError(TestError.self) {
    
    test_8c63_foo( $0)
}
    return try String.lift(_retval)
}

private func rustCallWithError<T, E: ViaFfiUsingByteBuffer & Error>(_ errorClass: E.Type, _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
```

Note that the Error type for rustCallWithError requires conformance with the Error protocol -- which the generated TestError enumeration does not have.

The fix: the TestError type needs to conform to the Swift Error protocol
i.e.,
```swift
public enum TestError {
```
should become
```swift
public enum TestError : Error {
```

---

Example of this producing a compilation error in XCode:
![image](https://user-images.githubusercontent.com/2360237/135980361-1651ac4c-3a18-4e11-a216-678483d43533.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-95)
┆Issue Number: UNIFFI-95

**Comment by arg0d** [comment]
The issue here is that Uniffi does not detect when `[Throws=..]` is used with non-error type.

In your example,
```[Enum] interface MyError```
should be
```[Error] interface MyError```.

Uniffi also does not detect when `[Throws=..]` is used with a simple enum missing `[Error]` attribute. This UDL code does not trigger any errors while handling UDL. Though the generated foreign bindings are broken.
```
enum MyError {"a"};
namespace test {
    [Throws=MyError]
    string foo();
};
```

@mhammond

**Comment by mhammond** [comment]
> In your example,
> `[Enum] interface MyError`
> should be
> `[Error] interface MyError`.

That's correct, thanks for digging this old issue up!

> Uniffi also does not detect when `[Throws=..]` is used with a simple enum missing `[Error]` attribute.

Ouch, thanks - do you mind opening a new report for this? If not, I'm happy to, but figured you might as well get the "glory" if you want it :)
