### ISSUE TITLE
Add library name explanation to readme

### ISSUE THREAD

**Issue by thunderbiscuit** [mozilla/uniffi-rs#1100]
Hi there!

Thanks for the awesome library. We've started testing with it for producing Kotlin and Swift libraries of the [bitcoindevkit](https://github.com/bitcoindevkit/bdk-ffi), and so far it works great!

I'm currently going over the user guide and taking notes, and I realized that somehow I cannot find a 1-liner explaining what the `uni` in `uniffi` stands for. I think it would be great to add a line in the readme "opening up" the name, e.g. _UniFFI stands for [...] Foreign Function Interface_.

Cheers!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-110)
┆Issue Number: UNIFFI-110

**Comment by mhammond** [comment]
Thanks for the suggestion - we'll try and work out where to add this, but FYI, it's just a play on the word "unify"

**Comment by rfk** [comment]
> it's just a play on the word "unify"

Because it lets you write a single FFI (think *uni* as in "unicycle") that's consumed by multiple target languages, so you can support multiple target applications from a single *unified* codebase. Just to be clear 😁.
