### ISSUE TITLE
Prepend local variables and parameters with `_` or `__`

### ISSUE THREAD

**Issue by jhugman** [mozilla/uniffi-rs#1102]
Currently uniffi generates code like: 

```kotlin
rustCall() { status -> _UniFFILib.INSTANCE.glean_83a2_process(uuid.lower(), foo.lower(), status) }
```

Here, uniffi needs the variable `status`, and the user  is using `foo` and `uuid`.

If the user wants to use `status` then the bindings and/or scaffoldings will not compile.

To allow this, we should use characters in internal variables/parameters that aren't parsed by WebIDL and/or won't survive the changing by `heck::MixedCase`.

```kotlin
rustCall() { _status -> _UniFFILib.INSTANCE.glean_83a2_process(uuid.lower(), status.lower(), _status) }
```

Potential followups: review our uses of fully qualified class names in Kotlin, additional prefixes in Swift class names.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-112)
┆Issue Number: UNIFFI-112

**Comment by name1e5s** [comment]
I'll try this.
