### ISSUE TITLE
Refactor Swift FFI type handling

### ISSUE THREAD

**Issue by bendk** [mozilla/uniffi-rs#1106]
The `type_ffi` filter on swift is a bit confusing and should be refactored.  It currently outputs the type that we want to use in the header file (e.g. `int32_t`).  This is different than all the other bindings, which outputs the type that `lower()` returns (`Int32` in this case).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-113)
┆friendlyId: UNIFFI-113

**Comment by jhugman** [comment]
I wonder if this should prompt us to break the file in to a `gen_swift` and `gen_header` files, with two different filters modules?

```rust
use  super::header_filters as filters;
```

**Comment by bendk** [comment]
This was fixed by #1106.
