### ISSUE TITLE
Build failure due to anyhow 1.0.47 changes

### ISSUE THREAD

**Issue by yujingaya** [mozilla/uniffi-rs#1109]
I just started using `uniffi` following the user guide, but I was unable to build it.

```sh
$ cargo build
  Compiling anyhow v1.0.47
  Compiling uniffi_build v0.14.1
  Compiling uniffi v0.14.1
error: 1 positional argument in format string, but no arguments were given
   --> /Users/yujingaya/.cargo/registry/src/github.com-1ecc6299db9ec823/uniffi-0.14.1/src/testing.rs:147:43
    |
147 |         bail!("Error while running tests: {}",);
    |                                           ^^

error: could not compile `uniffi` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I was able to check the bug in this repository has been fixed with #1097, but it's not released yet.

The build failure is due to breaking changes in `anyhow` 1.0.47 updates.

```rust
// This builds fine in anyhow 1.45, but fails in 1.47.
fn main() -> anyhow::Result<()> {
    anyhow::bail!("hello {}");
}
```

This results build failure up until 0.14.1.

As mentioned in https://github.com/dtolnay/anyhow/issues/188, this can be mitigated by explicitly fixing `anyhow` version. (I wasn't able to build it with mentioned patch method)

```toml
[dependencies]
anyhow = "=1.0.45"
```

As far as I know, there's no way we can fix already published versions, so best we can do is just letting people know what they can do about it, or possibly publish new release that fixes this problem?

Thank you for the great project, by the way 😉

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-114)
┆friendlyId: UNIFFI-114

**Comment by yokomizor** [comment]
I just tested v0.16.0 and it works now.

**Comment by yujingaya** [comment]
As we have newer versions, I believe it's okay to close this issue. Resolution: use the latest release

**Comment by gogo2464** [comment]
It is ok. It could be still cool if somebody updates the doc. This one is outdated: https://mozilla.github.io/uniffi-rs/tutorial/Rust_scaffolding.html#rust-scaffolding-codeI had to read this issue to solve.
