### ISSUE TITLE
Rust bindings (to provide a stable binary interface)

### ISSUE THREAD

**Issue by clemens-msupply** [mozilla/uniffi-rs#1125]
The specific use-case I have is a plugin system where host and plugins are both written in Rust. Moreover, host and plugins should have a stable binary interface (plugins compiled with an old Rust compiler should continue to work in the future).

- Would this work/align with uniffi-rs? (given somebody writes a Rust bindings backend).
- Is uniffi-rs suppose to generate stable interface bindings?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-120)
┆friendlyId: UNIFFI-120

**Comment by mhammond** [comment]
> * Would this work/align with uniffi-rs? (given somebody writes a Rust bindings backend).

I think so, yes.

> * Is uniffi-rs suppose to generate stable interface bindings?

I guess it depends on exactly how you define "stable" - in short, both sides of the generated world need to come from the exact same uniffi version, and other protections are in place to ensure mismatches can't happen. But this is true even without considering whether Rust makes sense as a "foreign" binding.

To put it another way, Rust foreign bindings would get the exact same guarantees the existing foreign bindings do.

**Comment by clemens-msupply** [comment]
thanks, in my case plugins could be complied with different versions. Currently I communicate with the plugin through a c api which works but is cumbersome. I was hoping that uniffi-rs / UDL could help me to generate the c interface.

So what you are saying is that two uniffi-rs versions could generate incompatible c apis from the same UDL file, right? This would make sense and I guess for the main use of uniffi-rs this is not an issue.

Another problem I see is that I probably want to reserve some bytes in the c struct to extend the api in the future without breaking it...

**Comment by mhammond** [comment]
> thanks, in my case plugins could be complied with different versions. Currently I communicate with the plugin through a c api which works but is cumbersome. I was hoping that uniffi-rs / UDL could help me to generate the c interface.

uniffi doesn't require all structs be `extern "C"`, so this is probably the first deal-breaker here.  uniffi instead embraces the flexibility that its guarantees provide - future optimizations become possible and things like reserving extra data at the end of structs for this purpose are never necessary.

There a little more about the scheme uniffi uses [here](https://github.com/mozilla/uniffi-rs/blob/adfa195ad2a01964e3b4d65568fc4121acf58222/uniffi_bindgen/src/interface/mod.rs#L289)

**Comment by clemens-msupply** [comment]
thanks @mhammond  I think I have a different use case, i.e. I don't necessarily control how the plugin is compiled. Maybe I can reuse some parts of uniffi though!
