### ISSUE TITLE
README should include (partial?) list of bindgen languages

### ISSUE THREAD

**Issue by mqudsi** [mozilla/uniffi-rs#1136]
Hello,

I just stumbled across this project via a Reddit link and it sounds like something that would really work for speeding up development of GUI applications written in rust but with a non-rust UI layer. However, I expected to see a mention of (or link to) a list of currently supported languages that UniFFI can generate bindings for but there is only a passing mention that Mozilla uses this to generate bindings for Swift and Kotlin (but not in a way that makes it clear if those are the only two languages currently supported or not).

I’m not asking about the language-agnostic rust side of things that will work for FFI in any language (the dynamic library, the exported API shape/impl, etc) but specifically the automated binding generator. 

Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-122)
┆friendlyId: UNIFFI-122

**Comment by mhammond** [comment]
The README should certainly indicate which languages are supported! Currently there's swift, kotlin, ruby and python - but we hope people will contribute other languages in the future.

**Comment by mqudsi** [comment]
Thanks. That's two more than I would have guessed from reading the README :)
