### ISSUE TITLE
xcframework demo

### ISSUE THREAD

**Issue by imWildCat** [mozilla/uniffi-rs#1147]
Hello, thanks for making such a great project!

The current iOS demo project (<https://github.com/mozilla/uniffi-rs/tree/main/examples/app/ios>) is using Xcode build script to make static libraries for the app. 
Is it a planned to make a `xcframework` demo? Or can I contribute to that?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-126)
┆friendlyId: UNIFFI-126

**Comment by tarikeshaq** [comment]
Hi @imWildCat!! Thanks a ton for your interest in contributing to uniffi 🔥 🔥 

We don't have a plan to create a demo for an `xcframework` at the time, but we would most definitely welcome one if you are interested in contributing 😄 

For inspiration, we package an `xcframework` over at https://github.com/mozilla/application-services/tree/main/megazords/ios-rust this doesn't mean the demo has to work that way (we don't use Xcode there for example) and we welcome you to demonstrate whichever use case/example you feel most comfortable with!

Feel free to tag me if you have any questions about how any of that works 😄

**Comment by imWildCat** [comment]
Hello @tarikeshaq , thanks for the reply!

I actually created a small demo here <https://github.com/imWildCat/uniffi-rs-fullstack-examples>. After finishing the demo of Android (I'm hoping to create an `aar` or `jar` file for the Rust module), I will start to improve the demo of uniffi-rs!
