### ISSUE TITLE
uniffi-bindgen scaffolding --manifest-path not working

### ISSUE THREAD

**Issue by BlueGreenMagick** [mozilla/uniffi-rs#1149]
As of #414, `uniffi-bindgen scaffolding --manifest-path <PATH>` no longer works. But it wasn't deleted from list of arguments in clap and still appears as an option when running `uniffi-bindgen scaffolding --help`.

Related code:
https://github.com/mozilla/uniffi-rs/blob/e7ff0dafda31d413ba94065c2f7039166ae03e94/uniffi_bindgen/src/lib.rs#L396

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-127)
┆friendlyId: UNIFFI-127

**Comment by mhammond** [comment]
This was removed as an option in #1211
