### ISSUE TITLE
Better error handling when lowering args?

### ISSUE THREAD

**Issue by bendk** [mozilla/uniffi-rs#1155]
On most of our bindings, we assume that lowering arguments always works.  For example on [Kotlin](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/kotlin/templates/macros.kt#L30-L35), we simply lower all arguments in order, there's no error handling if any of the lower calls fail.  If one of those lower calls creates a `RustBuffer`, then a subsequent lower call fails, then that `RustBuffer` will be leaked.

Should we add some error handling to properly clean up in the case of error failures?  It doesn't seem totally clear:
  - The cleanup isn't trivial, since you could be lowering multiple arguments into `RustBuffers`.  You would need to track which ones have been lowered so far and only free those.  I think the simplest way would be to have an object responsible for allocating `RustBuffers` that would track allocations, store them in a list, and allow you to free them all at once on an error.  Then you would need to change the signatures for each of the lower() functions to input that object.
  - I think the main failure case is a failed `RustBuffer` allocation.  We added some [sentry error reporting](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/16534301/) to track that and it seems like it's happening maybe once a day for nightly users.  I'm not sure what production error rate that corresponds to though.
  - It's also not clear what the consequences for the user are.  If `RustBuffer.alloc()` fails because we can't allocate memory, then it's seems somewhat likely that the entire process is about to crash.  If that's true, then we probably don't need to worry about freeing memory.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-131)
┆friendlyId: UNIFFI-131

**Comment by mhammond** [comment]
This should be "impossible" right? We see kotlin code generated like:

```
            _UniFFILib.INSTANCE.ffi_logins_6d43_rustbuffer_alloc(size, status).also {
                if (it.data == null) {
                    throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=$size)")
                }
            }
```

and the Rust scaffolding looks like:

```rust
pub extern "C" fn ffi_logins_8575_rustbuffer_alloc(
    size: i32,
    call_status: &mut uniffi::RustCallStatus,
) -> uniffi::RustBuffer {
    uniffi::call_with_output(call_status, || {
        uniffi::RustBuffer::new_with_size(size.max(0) as usize)
    })
}
```

(ignore the different hash there, because I didn't grab matching generated versions.)

And there doesn't seem a path there that doesn't panic. 

If I look at sentry, every event I looked at has `arm64-v8a` - I wonder if this is another manifestation of that other hiesenbug we are also scratching our heads over (but which I can't find at the moment)?

Stepping back, implicitly we already assume, via Rust, that OOM == panic. So I'm really not sure what is going on, but I can't find a justification for handling this more gracefully unless we can identify a viable path to legitimately his this.

Happy to hear contrary opinions though!

**Comment by mhammond** [comment]
(I also can't find an event where the "device" section reports `low_memory = true`)

**Comment by bendk** [comment]
Very interesting.
  - I personally think this is the same bug as the NPE in lower.  If I hadn't added the check, then I believe the next thing that would happen is a NPE when trying to use the `RustBuffer`.
  - I mistakenly thought that we would get a panic on when we couldn't allocate memory, but you're right it's going to abort.  So this definitely seems like a hiesenbug to me.
  - Even if it's a heisenbug, that doesn't rule out trying to free the previously allocated memory.  But I agree with you that it doesn't seem worth the time and extra complexity.

**Comment by mhammond** [comment]
> * I personally think this is the same bug as the NPE in lower.

I agree 100% - it's just that I'm skeptical it's actually OOM causing it.

> * that doesn't rule out trying to free the previously allocated memory



> * Even if it's a heisenbug, that doesn't rule out trying to free the previously allocated memory

TBH, I think it does. Otherwise, where would we stop trying to have our code handle impossible OOM situations?

**Comment by bendk** [comment]
Seems like we're divided between "it's possible but a bad idea" and "it's not really possible".  Looks like there's not much more discussion to be had and we shouldn't try to fix this.
