### ISSUE TITLE
Better isolation in the test fixture code.

### ISSUE THREAD

**Issue by bendk** [mozilla/uniffi-rs#1169]
When adding external type support for Kotlin, I noticed an issue with these.  When we are building multiple UDL files together, we need to include all the .jar files in the classpath for `compile_bindings()`and `run_script()`.  In order to support this, we simply add all .jar files from `out_dir`, but this includes .jar files that were built for other tests, were built from the previous runs, etc.  When I was changing the generated package names, I noticed false positives because we were including .jar files built from the previous run.

What if we combined `compile_bindings()` and `run_script()` into a `run_test` function?  It would input an array of `(&Config, &ComponentInterface)` tuples and a test script path.  Then it would bundle everything together and run the test.  By combining things into 1 function, we can track which jar files we're building and setup a precise classpath.  Also, these functions are only used for testing, so let's make the function name reflect that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-133)
┆friendlyId: UNIFFI-133
┆sprintEndDate: 2022-10-28

**Comment by bendk** [comment]
Let's wait for work Tarik is doing to move bindings to their own crate before we touch this one.

**Comment by mhammond** [comment]
As I noted in that other PR, the fact the compile functions are only used for tests isn't obvious to the casual reader, so I'm +1 on making it more explicit (but also agree to wait for Tarik's PR)
