### ISSUE TITLE
Update to askama 0.11

### ISSUE THREAD

**Issue by bendk** [mozilla/uniffi-rs#1176]
In addition to being a nice upgrade in general, Askama 0.11 changes how the features work with `askama_derive` and `akama_shared` in order to support Rust 2021 and the new feature resolver.

Currently, I can reliably get a build error by adding `uniffi_bindgen` as a dependency and adding either `edition = "2021"` or `resolver= "2"` to `Cargo.toml`.  I believe the askama upgrade should fix it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-135)
┆epic: Rust Components on Desktop
┆friendlyId: UNIFFI-135
┆sprintEndDate: 2022-03-18

**Comment by rfk** [comment]
I had an old PR here dealing with some of the API changes in the new Askama release, not sure how relevant it still is but may be useful: https://github.com/mozilla/uniffi-rs/pull/973

**Comment by bendk** [comment]
That PR was great, I stole quite a bit from it.  But after finally getting things to compile, I'm wondering if we should take a different approach.

Here's [my attempt to get this to work](https://github.com/mozilla/uniffi-rs/commit/69fe52f69b9a7c1bbd731034f1550622faaa659f).  This code builds, but the tests are failing.  I don't think it would be hard to get the tests to pass, I just wanted to take a step back before doing more work.

The change from `&dyn fmt::Display` to `&str` seems totally fine.  The amount of `.borrow()`s feels wrong to me and I want to restructure our code to avoid it.

A while back I proposed replacing the filter functions with trait methods (`type_.type_name()` instead of `type_|type_name`).  I feel like `askama 0.11` could be a good time for that.  If these were methods, then we wouldn't need to care how `askama` implements it's borrow mechanics -- the method above will work regardless of if `type_` is a reference or owned object.  As a bonus, we might be able to avoid the boilerplate required to implement both a regular rust function and a filter.  One issue is how to handle state, currently `type|type_name` depends on the static `ORACLE` variable.  It's not totally clear how that would work with regular methods, but I think there's a way.

We're currently using a system like this for the desktop JS bindings.  Maybe we could do some exploration there and see how it works.

**Comment by mhammond** [comment]
> The change from `&dyn fmt::Display` to `&str` seems totally fine. The amount of `.borrow()`s feels wrong to me and I want to restructure our code to avoid it.

I agree with both of those statements, although I don't think the restructure is necessary now. The vast majority of that branch is the `&str`, and at least some of the `borrow()` calls look a little to me like limitations in askama's parsing - I agree that they suck, but I think I'd be fine with that branch landing roughly as-is and thinking about the restructure away from filters into other traits in a followup where we can consider things in a slightly more compartmentalized way. WDYT?
