### ISSUE TITLE
Add command to output list of dependencies

### ISSUE THREAD

**Issue by bendk** [mozilla/uniffi-rs#1184]
We're currently working on developing a binding for Firefox Desktop JS.  Part of that work is integrating with the Gecko build system to auto-generate files. That build system requires you to specify the list of dependent files for a generated file, but this is not a totally trivial task.   For example, the location of `uniffi.toml` depends on our `guess_crate_root` function.

To assist with this, we should add a command to uniffi-bindgen-gecko-js  that outputs the list of dependent files.  Maybe this would be nice to add as a general uniffi-bindgen feature as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-141)
┆epic: Rust Components on Desktop
┆friendlyId: UNIFFI-141

**Comment by data-sync-user** [comment]
➤ Ben Dean-Kawamura commented:

We’re not going to integrate into the build system for the first pass, so let’s close this.
