### ISSUE TITLE
Unable to ensure version match between uniffi core and uniffi-bindgen

### ISSUE THREAD

**Issue by thunderbiscuit** [mozilla/uniffi-rs#1190]
I have read the section [Avoiding version mismatches...](https://mozilla.github.io/uniffi-rs/tutorial/Rust_scaffolding.html#avoiding-version-mismatches-between-uniffi-core-and-uniffi-bindgen) in the readme but the exact way to generate the bindings using this "internal" uniffi-bindgen still evades me.

Our `Cargo.toml` file has the appropriate config:
```toml
[build-dependencies]
uniffi_build = { version = "0.16.0", features = ["builtin-bindgen"] }
```

But the docs don't describe how to generate the bindings any differently than before, which for us is:
```shell
uniffi-bindgen generate src/bdk.udl --no-format --out-dir ../jvm/src/main/kotlin --language kotlin
```

I assume there is something missing in my understanding of how to work this, but I can't quite figure out what... 

The reason why I'm trying to get this work work _without_ the cli tool is that I'm trying to automate the build of the native libs and the bindings file inside a Gradle plugin. We were bug chasing for a little while last week when a newcomer to the project could not get his code to work, and we finally realized he was building using the cli tool on 0.17 whereas we're on 0.16.

Any tips appreciated!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-143)
┆friendlyId: UNIFFI-143

**Comment by mhammond** [comment]
This is all a bit messy, but https://github.com/mozilla/application-services/tree/main/tools/embedded-uniffi-bindgen along with https://github.com/mozilla/application-services/blob/0d4ae3876b1f20da2b40c6fe5701863d0b6696dd/publish.gradle#L206-L226 is how Mozilla's main consumer of uniffi manages this.  We'd welcome your feedback on what improvements we can make here (even if it's just to document out flow a bit better?)

**Comment by thunderbiscuit** [comment]
Thanks for the context and sharing your solution! It's funny because we ended up with a similar (even if less refined) solution, where our [ffi layer](https://github.com/bitcoindevkit/bdk-ffi) which feeds into the three libraries we support (Kotlin, Swift, Python) has a small binary that calls the proper version of uniffi-bindgen, effectively creating a drop-in replacement for the cli. This drop-in replacement is what I then use in the Gradle plugin for building the JVM and Android libraries.

As for the documentation, I'll have to take a second look (I'll open a new issue if I think of something good). I'd say it was very made very clear that it's important that the library and the cli tool be in sync version-wise, so that's good. But then even after working with the library and knowing the tool for a little while the section on how to avoid version conflicts didn't quite click for me (like "oh _that's_ what I should do!"). Maybe an example on your recommended approach would be nice. Maybe I was just missing context, not sure.

But I realize now how much of a footgun the cli tool _can_ be if not properly understood. It's good for exploration and getting a hello world example working quickly, but you really shouldn't use it for production. In the workflow of uniffi-rs, I'd say it's one of the tripping points for sure. 

Again thanks for the always awesome help.
