### ISSUE TITLE
import UDF

### ISSUE THREAD

**Issue by lattice0** [mozilla/uniffi-rs#1195]
How to import one UDF type into another?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-146)
┆friendlyId: UNIFFI-146

**Comment by mhammond** [comment]
You mean `.udl`? If so, you can't, but you can refer to types in other `udl` files by using [external types](https://mozilla.github.io/uniffi-rs/udl/ext_types.html)

**Comment by mainrs** [comment]
It seems to not work across files inside the same src folder. I have a file `error.udl` that defines an error type I want to use in other files that are in the same folder. The build fails to compile though.
