### ISSUE TITLE
Rework scaffolding generation?

### ISSUE THREAD

**Issue by bendk** [mozilla/uniffi-rs#1199]
If our current plan of moving bindings generation into separate crates, we should consider what to do with the scaffolding code.

- Should it live in its own crate and/or be its own binary?
- If not, should the `uniffi-bindgen` args change?  It feels a bit weird having to add `scaffolding` as an argument when the binary always generates the scaffolding.
   - For now, we're still supporting `uniffi-bindgen generate` for backwards-compatibility.  so we should probably wait until we remove that code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-150)
┆friendlyId: UNIFFI-150

**Comment by jplatte** [comment]
> For now, we're still supporting `uniffi-bindgen generate` for backwards-compatibility.

The website [documents](https://mozilla.github.io/uniffi-rs/tutorial/foreign_language_bindings.html) `uniffi-bindgen generate` as the (primary?) way to generate bindings, is there actually a different way?

**Comment by bendk** [comment]
Currently `uniffi-bindgen generate` is the only way.  This was based on some speculation on how thing might work in the future.  In fact, this seems very far in the future at this point and I think we should just close it.
