### ISSUE TITLE
Please upgrade weedle2 to nom 7

### ISSUE THREAD

**Issue by glandium** [mozilla/uniffi-rs#1260]
Currently, building uniffi_bindgen requires 2 versions of nom: 5, through weedle2 and 7, through askama. It would be better to only require one.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-169)
┆friendlyId: UNIFFI-169

**Comment by badboy** [comment]
nom 5 -> 6 upgrade for weedle is pretty simple.
but 6 -> 7 is more involved as all macros are dropped, which weedle relies on heavily.
