### ISSUE TITLE
[question] Some questions to understand better this tool

### ISSUE THREAD

**Issue by paulocoutinhox** [mozilla/uniffi-rs#1293]
Hi,

I made a project called Nativium (https://github.com/nativium/nativium) that uses C++ for all platforms.

I want make a "rust" version of my project that let me understand better about rust.

I use a tool called Djinni, that i'am one of contributors:

- https://github.com/cross-language-cpp/djinni-generator/graphs/contributors
- https://github.com/Snapchat/djinni/graphs/contributors

I want know somethings to make a tool similar of Nativium, but using rust with `uniffi-rs`:

1. It support everything that djinni have?
2. It generate bindings for `wasm`?
3. It has support for call Kotlin/Swift code from rust, like callbacks, async/wait or futures?

Thanks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-179)
┆friendlyId: UNIFFI-179

**Comment by mhammond** [comment]
> I want know somethings to make a tool similar of Nativium, but using rust with `uniffi-rs`:
> 
>     1. It support everything that djinni have?

You'll have to do your own research here - I don't think anyone working on uniffi is familiar with djinni.

>     2. It generate bindings for `wasm`?

It does not and there are no concrete plans to do this.

>     3. It has support for call Kotlin/Swift code from rust, like callbacks, async/wait or futures?

It does not directly support async or futures, but this is something we are thinking about.
