### ISSUE TITLE
FFI extern function declaration is different from compiled library exports

### ISSUE THREAD

**Issue by p0vidl0** [mozilla/uniffi-rs#1300]
I have tried to build a kotlin wrapper for own library, but got unclear mismatch in exported function name in compiled library and generated kotlin code. For example, rust-library function exported  in `librsl.so` binary as `rsl_d7ce_mul2` and described as `rsl_3ad6_mul2` in generated `rsl.kt` file.

Initially, found this issue on rustc 1.62.0 (a8314ef7d 2022-06-27) & cargo 1.62.0 (a748cf5a3 2022-06-08) on Windows10 x64 with kotlin.
It's also reproduced on MacOS with kotlin and swift.

Prepared the [example repository](https://github.com/p0vidl0/uniffi-rs-issue-example).

Please advise, if it's possible to make this behavior consistent?

Android app falls with the error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 14718
    java.lang.UnsatisfiedLinkError: Error looking up function 'rsl_3ad6_mul2': undefined symbol: rsl_3ad6_mul2
        at com.sun.jna.Function.<init>(Function.java:252)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:600)
        ...
```

## Details
Generated `rsl.kt` file part:
```
fun `mul2`(`a`: UInt, `b`: UInt): UInt {
    return FfiConverterUInt.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.rsl_3ad6_mul2(FfiConverterUInt.lower(`a`), FfiConverterUInt.lower(`b`), _status)
})
```

Compiled library `librsl.so`:
```shell
> nm -gD librsl.so

                 U __cxa_atexit
                 U __cxa_finalize
...
                 U close
                 U dl_iterate_phdr
0000000000042c6c T ffi_rsl_d7ce_rustbuffer_alloc
0000000000042c78 T ffi_rsl_d7ce_rustbuffer_free
0000000000042c70 T ffi_rsl_d7ce_rustbuffer_from_bytes
0000000000042c7c T ffi_rsl_d7ce_rustbuffer_reserve
                 U fflush
                 U fprintf
...
                 U realloc
                 U realpath
0000000000042c80 T rsl_d7ce_mul2 # <<< exported function mul2
                 U stat
                 U strerror_r
                 U strlen
                 U syscall
0000000000043158 T uniffi_rustbuffer_alloc
00000000000431b4 T uniffi_rustbuffer_free
0000000000043188 T uniffi_rustbuffer_from_bytes
00000000000431d8 T uniffi_rustbuffer_reserve
                 U write
                 U writev
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-182)
┆friendlyId: UNIFFI-182

**Comment by tarikeshaq** [comment]
Hi @p0vidl0! Thank you for filing a bug! 

The most likely case is that there is a mismatch between the version of `uniffi-bindgen` used to generate the scaffolding and the one used to generate the bindings. In the example repo, look like you are using the `builtin-bindgen` feature, which will use the version of `uniffi` defined in the `Cargo.toml` to generate the Rust scaffolding (and build that into the binary). 

You can verify that by running `uniffi-bindgen --help` and see if that version matches the one used in your `Cargo.toml` for the build script.

Let us know if that isn't the case and we can take a deeper look!

(as a side note, we are planning to make the versioning a bit less strict in the future, see https://github.com/mozilla/uniffi-rs/pull/1271 cc @bendk)

**Comment by p0vidl0** [comment]
Thanks for fast response, @tarikeshaq!
I'm fixed versions in `Cargo.toml` to the `"=0.19.3"`, install exact same `uniffi-bindgen` version with `cargo install uniffi_bindgen@0.19.3` and now the tooling behavior is consistent.
