### ISSUE TITLE
Help required for building Realm alternative with rust

### ISSUE THREAD

**Issue by akashgurava** [mozilla/uniffi-rs#1305]
I am trying to build Realm alternative using Rust - [Juno](https://github.com/akashgurava/Juno). I have the barebone UniFFI integration into a Swift package where I can send structs from Rust to Swift. But what I want to achieve is have a Swift struct/class implementing a protocol/subclass be able to stored using a KV store in rust.
1. I have tried to do a microservice approach where rust starts a server and accepts struct definition + values and store and retrieve data similarly.
2. But later thought that was too much and can just send Vec<u8> and serialize/deserialize between languages. I found a blog from Mozilla where it was explained that protocol buffer was used to achive this. I tried rust-protobuf as it had runtime definition parsing ability.

I am pretty new to Application development and have no idea is there an easier way for this? I am willing to put time into this but have been hitting walls a lot. Any suggestions about how I could proceed would be very helpful.

Also thank you for this wonderful library!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-186)
┆friendlyId: UNIFFI-186

**Comment by mhammond** [comment]
Thanks for your interest in UniFFI! I'm afraid I don't fully understand your question, but maybe I can still help. Mozilla was using protobuf before UniFFI came on the scene - so in all cases where we now use UniFFI we no longer use protobuf. I don't know how you could express protobuf structs in UniFFI, so I think the best you will be able to do is to so the protobuf serialization and derserialization on the kotlin side of the world, and express the UniFFI interface and KV store in terms of bytes.

If that doesn't help, then maybe you can go into more detail about what the .udl you would like to create looks like?

**Comment by akashgurava** [comment]
To clarify, I am trying to build a swift package not an application. My package will be used as a data store by the package users, who would define structs that needs to be stored. So I cannot define the structs at rust's compile time.

Here's what I am doing now:
Package user defines struct A -> My package creates a proto as string sends to rust using UniFFI -> Rust-protobuf parses the proto in runtime

Then when the user needs to store an instance of A -> My package serializes the strcut to protobuf using [BinaryCodable](https://github.com/christophhagen/BinaryCodable) send binary messages to rust -> Rust parses the messages stores the data

and the reverse direction for reading data.

**Comment by mhammond** [comment]
The Rust code can probably only store the binary message, but is probably unable to reasonably parse it.

**Comment by akashgurava** [comment]
Yea looks that way. Thank you!
