### ISSUE TITLE
Swift bindings being generated with wrong labels

### ISSUE THREAD

**Issue by augustocdias** [mozilla/uniffi-rs#1311]
We have a library that we are generating swift bindings for and we noticed that for an interface it is generating wrong labels. 

In the `foreignCallback` method they're calling the interface passing the labels wrongly named which causes the project to fail to compile. They're being generated as snake_case (actually the same name as we declare in the udl file) instead of camelCase.

Here's an example:

https://github.com/wireapp/core-crypto/blob/develop/crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift#L1465

We have the interface declared correctly:

```swift
public protocol CoreCryptoCallbacks : AnyObject {
    func authorize(conversationId: [UInt8], clientId: String)  -> Bool
    func isUserInGroup(identity: [UInt8], otherClients: [[UInt8]])  -> Bool
    
}
```

but then in the call:

```swift
            let result = swiftCallbackInterface.authorize(
                    conversation_id: try FfiConverterSequenceUInt8.read(from: reader), 
                    client_id: try FfiConverterString.read(from: reader)
                    )
```

Our config for generating swift: https://github.com/wireapp/core-crypto/blob/develop/crypto-ffi/uniffi.toml

```toml
[bindings.swift]
cdylib_name = "core_crypto_ffi"
ffi_module_name = "CoreCrypto"
ffi_module_filename = "core_cryptoFFI"
```

I've tried with `omit_argument_labels = false` but it still generated bad labels there.

A workaround to make it work that we're using for now is declaring them as camel case in the udl file. But that generates warnings during rust compilation...

**Comment by mhammond** [comment]
That sounds like #1310?

**Comment by augustocdias** [comment]
@mhammond it seems so... I didn't go through the PR's when searching for issues here 😅 sorry

**Comment by mhammond** [comment]
No probs - good timing though as that PR was only opened today! I'll close this for now and I expect that PR to land tomorrow or so. I'm not sure when the next release will be though. but probably not too far away.
