### ISSUE TITLE
[Swift] Bad generation of swift callback interface

### ISSUE THREAD

**Issue by SebMenozzi** [mozilla/uniffi-rs#1312]
Hey Uniffi team!

I just encountered an issue with the swift file generation which I suspect might be bug.

Th issue occurs when I set in the `uniffi.toml` the flag `omit_argument_labels = true`, changing it to `false` resolves the issue.

<img width="1066" alt="Screen Shot 2022-08-22 at 4 25 17 PM" src="https://user-images.githubusercontent.com/5332196/186013309-41072911-6f10-4ded-b633-de9b0695224e.png">

The protocol has an underscore `didReceiveFriendRequest(_ user: UserModel)` where the `swiftCallbackInterface` has the extra `user:` which it shouldn't.

The UDL file looks like this:
```
callback interface ClientDelegate {
    void did_receive_friend_request(UserModel user);
};
```
And the Rust implementation like this:
```
pub trait ClientDelegate: Sync + Send {
    fn did_receive_friend_request(&self, user: UserModel);
}
```

Thank you!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-188)
┆friendlyId: UNIFFI-188

**Comment by badboy** [comment]
I'm taking a look here.
