### ISSUE TITLE
Looking for information on breaking change in `0.19.5`

### ISSUE THREAD

**Issue by thunderbiscuit** [mozilla/uniffi-rs#1322]
Hello everyone,

A few of our CI workflows started breaking because of the new argument required in `generate_bindings()` introduced a few days ago in uniffi-bindgen (the CI pulls version `0.19.5`, and we were on `0.19.3`). This is not a problem in the short term because I can just pin the version to `0.19.3`, but in the process of looking into this I was trying to find information on this new argument required by the method (`library_file: Option<&Utf8Path>,`), and I wasn't able to find info/details on it (I looked at the changelog, docs, and issues).

Eventually however we'll want to upgrade, and so I'm wondering if there is a location where this argument is outlined (what do we gain by adding it? it maybe looks like it ensures that components of the UDL file are in the native binaries?) or if not if this issue can serve as its de facto documentation (feel free to change the title if necessary).

Cheers!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-191)
┆friendlyId: UNIFFI-191

**Comment by badboy** [comment]
Ugh, the fact that this is a breaking change was an oversight. We should have gone to 0.20 then. I'm sorry about that happening.

We indeed currently lack proper docs around that.
It is exposed to the CLI [in the command definition](https://github.com/mozilla/uniffi-rs/blob/4f335162807297a0192199f05fab3cc04a743447/uniffi_bindgen/src/lib.rs#L540-L542):

```
Extract proc-macro metadata from a cdylib for this crate
```

This is used when using the macro-based approach (see #1257).
Unless you're using that you should pass `None`.

**Comment by thunderbiscuit** [comment]
Sounds good! We haven't looked at upgrading to the new macro-based approach yet (although I'm keeping an eye on it), so this will be an easy fix for us.

Thanks for the quick response!

**Comment by thunderbiscuit** [comment]
After applying the recommended change, the CI now picks up `0.19.6` and [breaks again](https://github.com/bitcoindevkit/bdk-ffi/runs/8160996199?check_suite_focus=true)... 😆 

```sh
    Compiling uniffi_meta v0.19.6
error: there is no argument named `mod_path`
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/uniffi_meta-0.19.6/src/lib.rs:71:22
   |
71 |     format!("_uniffi_{mod_path}_{name}_{checksum:x}")
   |                      ^^^^^^^^^^

error: there is no argument named `name`
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/uniffi_meta-0.19.6/src/lib.rs:71:33
   |
71 |     format!("_uniffi_{mod_path}_{name}_{checksum:x}")
   |                                 ^^^^^^

error: there is no argument named `checksum`
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/uniffi_meta-0.19.6/src/lib.rs:71:40
   |
71 |     format!("_uniffi_{mod_path}_{name}_{checksum:x}")
   |                                        ^^^^^^^^^^^^

error: could not compile `uniffi_meta` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Process completed with exit code 101.
```

The error is coming from uniffi-meta, so I'm not sure how/if I can solve it on my side of things... let me know if there is a simple fix I'm just not seeing. Cheers!

**Comment by badboy** [comment]
Use a newer compiler. UniFFI uses [Captured identifiers in format strings](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings), that came with Rust 1.58.
Our [MSRV is 1.60](https://github.com/mozilla/uniffi-rs/pull/1314).

**Comment by thunderbiscuit** [comment]
Thank you!
