### ISSUE TITLE
Generated function names does not agreed with symbols names in compiled library

### ISSUE THREAD

**Issue by JDM-ULL-93** [mozilla/uniffi-rs#1345]
For some reason i cannot find, the names generated by Uniffi using ** uniffi-bindgen** diffier from the names generated in the compiled library. For example, here is a name of a Uniffi helper function:

```rust
#[allow(clippy::missing_safety_doc)]
#[no_mangle]
pub extern "C" fn ffi_test_9083_rustbuffer_alloc(
    size: i32,
    call_status: &mut uniffi::RustCallStatus,
) -> uniffi::RustBuffer {
    uniffi::ffi::uniffi_rustbuffer_alloc(size, call_status)
}
``` 
**_9083_**

It was generated this way:
```
  $ uniffi-bindgen scaffolding ./src/test.udl --out-dir ./out/
```

And in the compiled .so this is found:
```
  U abort@GLIBC_2.2.5
  U bcmp@GLIBC_2.2.5
  U calloc@GLIBC_2.2.5
  U clock_gettime@GLIBC_2.17
  U close@GLIBC_2.2.5
  w __cxa_finalize@GLIBC_2.2.5
  w __cxa_thread_atexit_impl@GLIBC_2.18
  U dl_iterate_phdr@GLIBC_2.2.5
  U __errno_location@GLIBC_2.2.5
  ffi_test_6ce6_rustbuffer_alloc
```
**_6ce6_** instead of **_9083_** . Output generated by using: 
```
  $ nm -gD libtest.so
```

This will end in an error "method not found" when we try to import it later.

Files:
[Rust.zip](https://github.com/mozilla/uniffi-rs/files/9598655/Rust.zip)
Sys specs:
[sys_info.zip](https://github.com/mozilla/uniffi-rs/files/9598660/sys_info.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-200)
┆friendlyId: UNIFFI-200

**Comment by badboy** [comment]
This usually happens when `uniffi-bindgen` and your library's uniffi dependency are different versions.
What's the output of `uniffi-bindgen --version` and what's the version for `uniffi` in your `Cargo.lock`?

**Comment by JDM-ULL-93** [comment]
Yes. The problem was a divergence between crate version(0.19.6 and bindgen version(0.20.0) . 

Thank you for the support, the issue can be closed.
