### ISSUE TITLE
Java Library Name without Prefix

### ISSUE THREAD

**Issue by easytarget2000** [mozilla/uniffi-rs#1412]
I am working on a setup for Android with UniFFI version 0.21.0, in which Gradle tasks build the Rust library and the bindings, based on the [Integrating with Gradle](https://mozilla.github.io/uniffi-rs/kotlin/gradle.html#integrating-with-gradle) section from the UniFFI docs. 

The components are mostly working together now, except for one part:
Running `uniffi-bindgen generate src/my_lib.udl --language kotlin` generates a Kotlin file that specifies the library name like so:
```kotlin
// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_my_lib"
}
```
Without renaming the Rust artifact that Cargo produces out of the box, loading the library during runtime fails:
```java
dlopen failed: library "libuniffi_my_lib.so" not found
```

This makes me wonder:
1. Is it possible to tell `uniffi-bindgen` not to add the `uniffi_` prefix?
2. `libOverride` is always `null` in my case. Is this expected?
3. Wouldn't `return "uniffi_$componentName"` or `return componentName` suffice?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-213)
┆Issue Number: UNIFFI-213

**Comment by badboy** [comment]
You can control the library name using `cdylib_name` in the `uniffi.toml` config. See https://mozilla.github.io/uniffi-rs/swift/configuration.html?highlight=cdylib_name#available-options

`libOverride` allows to override the name at runtime. This is a feature some of the Mozilla projects require at the moment.

**Comment by easytarget2000** [comment]
Thanks, that was the setting I was looking for. `$ uniffi-bindgen generate --help` mentions a config file, but I didn't find the documentation for it.

**Comment by badboy** [comment]
> Thanks, that was the setting I was looking for. `$ uniffi-bindgen generate --help` mentions a config file, but I didn't find the documentation for it.

Indeed we don't even have a unified place (see what I did there?) for documentantion about that config file. We should fix that.
