### ISSUE TITLE
CaseIterable enums in Swift

### ISSUE THREAD

**Issue by justinmoon** [mozilla/uniffi-rs#1413]
Hey. Thanks for the great library. 

I have an enum in Rust representing different types of messages which will be sent from Rust to Swift / Kotlin, which will send them to React Native.

The thing in Swift that can forward events to React Native is called `RCTEventEmitter` and it requires that I provide an array of all all events names (strings). I can't figure out how to do this using the Swift enum produced by Uniffi. But if this Swift enum was [CaseIterable](https://developer.apple.com/documentation/swift/caseiterable) then I think it would work. 

Would it be possible to produce `CaseIterable` Swift enums in some way?

For now I'm just using `sed` to add `CaseIterable` ....

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-212)
┆Issue Number: UNIFFI-212

**Comment by mhammond** [comment]
It looks like that can only be used for enums without associated data, but UniFFI supports enums with associated data. TBH, I'm not sure if that alone is a good enough reason to not support it where we can. IIUC though, this doesn't help Kotlin, or can that already do it?

**Comment by nbhasin2** [comment]
Hi Justin, 

I am jumping on this thread as I was wondering why can't you extend the associated type enum on the Swift side and conform it to `CaseIterable` protocol and use it 🤔 

### Example:

**Rust Side**
```
enum RustSampleEnum {
    case sendToDevice
    case numberOfConnectedDevices(Int)
}
```

**Your App Extension**
```
extension RustSampleEnum: CaseIterable {
    static var allCases: [RustSampleEnum] {
        return [.sendToDevice, numberOfConnectedDevices(-1)]
    }
}
```

**Documentation Apple:** 

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/8919439/204903246-4cb8e2dd-d6b8-4d0b-8456-f485b90572a4.png">

**Comment by justinmoon** [comment]
Thanks @nbhasin2. That does work. Thanks for sharing. Feel free to close this.
