### ISSUE TITLE
UDL plugin for Android Studio

### ISSUE THREAD

**Issue by Lonami** [mozilla/uniffi-rs#1418]
(My intention with this issue is not for it to come as an advertisement, but rather ask if the team would like me to upstream it to make it official. Feel free to close, lock, or even delete the issue if it's not appropriate.)

The lack of syntax highlighting for `.udl` files in Android Studio was bothering me, so I took the matter into my own hands and [made the *uniffi-dl* plugin for the IDEA platform](https://github.com/Lonami/uniffi-dl). I have also [published it to the JetBrains marketplace](https://plugins.jetbrains.com/plugin/20527-uniffi-dl). Currently the plugin markets itself as follows:

> Unofficial plugin which provides syntax highlighting, code folding, code completion, reference resolution and navigation (among others features) for the [UniFFI Definition Language (UDL)](https://mozilla.github.io/uniffi-rs/), a variant of [WebIDL](https://webidl.spec.whatwg.org/) specifically tailored for the [UniFFI tool](https://github.com/mozilla/uniffi-rs/) to "generate foreign-language bindings targeting Rust libraries".

Here's how it looks:

![Showcase of the syntax highlighting of the uniffi-dl](https://plugins.jetbrains.com/files/20527/screenshot_7c64e5ad-e693-41ad-8467-6fa1e5f0153b)

I was wondering if the UniFFI team would like to mark this as "the" official plugin for UniFFI. It's not very polished as of 0.2.2 (first release in the marketplace), so maybe its quality is not on par with something the team would like to claim official. But at the very least, I hope someone finds it useful, and if the team would eventually publish their own, I wouldn't mind giving away the ownership of the plugin in marketplace so the official version can replace mine.

I have also not upstreamed things like these before, so I don't know what the process is like.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-216)
┆Issue Number: UNIFFI-216

**Comment by mhammond** [comment]
That looks fantastic! 

> I was wondering if the UniFFI team would like to mark this as "the" official plugin for UniFFI.

I doubt we'd want to make it '"the" official plugin', but we'd certainly be happy to work out the best place to have external links for interesting things like this - as discussed in https://github.com/mozilla/uniffi-rs/issues/441#issuecomment-1328787223 we'd also want this to link to external bindings. An "External Resources" section in README.md is probably a good place to start.
