### ISSUE TITLE
Objects can't be external types

### ISSUE THREAD

**Issue by bendk** [mozilla/uniffi-rs#1435]
Currently, objects can't be supported by external types because we generate [this scaffolding code](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/scaffolding/templates/ExternalTypesTemplate.rs#L6)

This works for enums, errors, and records, where we generate an `FfiConverterType[name]` struct for them.  But it doesn't work for objects, where we use `Arc<T>` as the `FfiConverter`, which is implemented in the `uniffi` crate itself.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-223)
┆Issue Number: UNIFFI-223

**Comment by stan-irl** [comment]
@bendk do you have any tips for how to work around this limitation?

I think this blocks users of this framework from splitting up a workspace into separate crates (like in application-services) for a lot of use cases - my specific usecase is that I want to define an auth delegate to pass from the platform into a number of different rust crates:
```
callback interface AuthDelegate {
  string get_token();
};

```

Right now my backup plan is to have a single crate with many modules, and concatenate all the udl files into a single file in the root. 

Keen to hear what you think

**Comment by bendk** [comment]
I can't think of any good workarounds for now, but once we figure out #1444, I think this might get fixed automatically.  I'm hoping that happens in the next couple weeks

**Comment by stan-irl** [comment]
that would be awesome 🤞

**Comment by stan-irl** [comment]
ok i have a workaround:
I'm building my consumer UDL with the following script
```
use std::error::Error;
use std::fs;
use std::{fs::File, io};

const TMPFILE: &str = "./consumer.udl";

fn main() -> Result<(), Box<dyn Error>> {
    {
        let mut output = File::create(TMPFILE)?;
        let inputs = vec!["./consumer.tmpl.udl", "../auth/auth.udl", "../log/log.udl"];
        for i in inputs {
            let mut input = File::open(i)?;
            io::copy(&mut input, &mut output)?;
        }

        uniffi_build::generate_scaffolding(TMPFILE).unwrap();
    }
    fs::remove_file(TMPFILE)?;
    return Ok(());
}
```

Im concatenating the dependency UDLs (which have the namespace omitted) into the consumer UDL before generating the scaffolding. The I can just re-export the types from the consumer crate.

This is obviously a little bit hacky and the namespaces are a little bit messed up (`consumer::AuthDelegate` etc) but it avoids duplicating anything and allows for a pretty clean fix if and when  https://github.com/mozilla/uniffi-rs/pull/1444 is figured out.

Thanks again for your help!!

**Comment by bendk** [comment]
I tested it out and #1444 didn't fix this one so I made a real fix in #1456

**Comment by GGGava** [comment]
@bendk amazing, is this going to be released anytime soon?

**Comment by stan-irl** [comment]
I just installed from git and give it a go but my callback interface still didnt work because the scaffolding didnt put a `dyn` in the right place.

I made a PR to add a fixture which covers this: https://github.com/mozilla/uniffi-rs/pull/1472. Although I'm not sure if you intend on supporting my usecase.

**Comment by bendk** [comment]
One more case we forgot about.... I'll try to review that issue today and get back to you.  In the meantime, I think we can close this one since #1456 was merged.
