### ISSUE TITLE
invalid kotlin and python code generated for external types

### ISSUE THREAD

**Issue by mhammond** [mozilla/uniffi-rs#1443]
As demonstrated in #1442. See the CI there, but the tl;dr is:

* A .udl defines the `Url` type as an "external" type (ie, defined in a UDL file from a different crate, and a function which takes a `Url` as a param (in this case, a simple `Url get_url(Url url);`)
* The declaration for the "raw" FFI function looks like: `fun imported_types_lib_755c_get_url(`url`: RustBuffer.ByValue, _uniffi_out_err: RustCallStatus): RustBuffer.ByValue`
* The declaration for the "friendly" Kotlin version of that function tries to call that "raw" FFI function like: `_UniFFILib.INSTANCE.imported_types_lib_755c_get_url(FfiConverterTypeUrl.lower(`url`), _status)`
* Because `FfiConverterTypeUrl` is external, it's signature is `customtypes.RustBuffer.ByValue` - a different implementation of `RustBuffer` than the above.
* The resulting error ends up as:
```
/mnt/c/src/moz/uniffi-rs/target/tmp/uniffi-fixture-ext-types-badd42f1a46aef55/uniffi/imported_types_lib/imported_types_lib.kt:685:5: error: type mismatch: inferred type is uniffi.imported_types_lib.RustBuffer.ByValue but customtypes.RustBuffer.ByValue was expected
    rustCall() { _status ->
    ^
/mnt/c/src/moz/uniffi-rs/target/tmp/uniffi-fixture-ext-types-badd42f1a46aef55/uniffi/imported_types_lib/imported_types_lib.kt:686:57: error: type mismatch: inferred type is customtypes.RustBuffer.ByValue but uniffi.imported_types_lib.RustBuffer.ByValue was expected
    _UniFFILib.INSTANCE.imported_types_lib_755c_get_url(FfiConverterTypeUrl.lower(`url`), _status)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-225)
┆Issue Number: UNIFFI-225

**Comment by arg0d** [comment]
The problem is that `RustBuffer` is declared for each package, right? So when using multiple .udl files, there are multiple `RustBuffer` types defined inside each individual .kt file.

**Comment by mhammond** [comment]
Yeah, that was the problem, but I think it's been correctly fixed everywhere via the linked issue and a few followups.
