### ISSUE TITLE
Is it safe to apply certain optimizations to reduce binary size?

### ISSUE THREAD

**Issue by nugmanoff** [mozilla/uniffi-rs#1448]
Hey, Mozilla team! 

First of all I'd love to thank you for the amazing job you have done and continue doing with UniFFI. 
The amount of transparency and openness that you guys bring to your decision making processes with all the ADRs, thorough docs and even the inline docstring in bash scripts – it is just next level!

### Context

I am working on Swift (and Kotlin) [bindings](https://github.com/y-crdt/y-uniffi) for [Yrs](https://github.com/y-crdt/y-crdt) (performant CRDT library for building rich collaborative documents).

We have decided to leverage the UniFFI to achieve this goal. At the moment, building and packaging the Rust lib is heavily inspired by what you guys did with [ios-rust](https://github.com/mozilla/application-services/tree/main/megazords/ios-rust) and [rust-components-swift](https://github.com/mozilla/rust-components-swift). Here is the [bash script](https://github.com/y-crdt/y-uniffi/blob/main/lib/build-xcframework.sh) that does the job.

### Issue

What I noticed is that resulting static (`.a`) libraries and the eventual `.xcframework` turn out to be quite heavy – 67MB (ios-arm64, ios-arm64_x86_64-simulator) for unzipped xcframework in my case, e.g. where 25MB accounts for single static library (`.a`) built for **ios-arm64** arch.

I looked at [MozillaRustComponents.xcframework.zip](https://github.com/mozilla/application-services/releases/tag/v96.2.1) that you produce as artifact, that is also *not small* 104MB zipped.

I have seen that you are aware of the binary sizes by looking at https://github.com/mozilla/application-services/issues/3925

### Question

I did [apply](https://github.com/y-crdt/y-uniffi/blob/main/lib/Cargo.toml#L6-L11) some recommended optimizations from [min-sized-rust](https://github.com/johnthagen/min-sized-rust):

```toml
[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
```
I was able to get to 20MB unzipped `.xcframework` size for the same target triplet with above. 

My question is – is it safe to do so in the context of UniFFI bindgen and stuff? Maybe there are some implicit pitfalls/tradeoffs that I am missing. Or maybe you can nudge me into the direction of how to optimize things even further.

I'd appreciate any help, 
Thanks!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-227)
┆Issue Number: UNIFFI-227

**Comment by badboy** [comment]
Optimizations like that should always be safe in the context of Rust, they cannot affect your code.

**Comment by nugmanoff** [comment]
@badboy thanks for the reply! I think this will suffice – closing the issue
