### ISSUE TITLE
[question] udl for types from other crate

### ISSUE THREAD

**Issue by conanoc** [mozilla/uniffi-rs#1449]
How can I define a function using the FfiStr type from another crate in a udl file?
Here's an example:
```rust
use ffi_support::FfiStr;
pub extern "C" fn key_generate(
    alg: FfiStr<'_>,
    ephemeral: i8,
    out: *mut LocalKeyHandle,
) -> ErrorCode {
//...
}
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-226)
┆Issue Number: UNIFFI-226

**Comment by mhammond** [comment]
I don't think that's possible or something we'd want to support. We see FfiStr as an implementation detail and ideally we'd end up removing `ffi_support` entirely at some point. Can you describe in more detail what problem you are trying to solve (ie, why your udl file doesn't just use `string`)

**Comment by conanoc** [comment]
@mhammond Any suggestions?

**Comment by mhammond** [comment]
Presumably that function does something like converting `alg` to a string, then calling a function which takes the string and returns a `LocalKeyHandle`? So I'd suggest you expose *that* function via uniffi. IOW, your manually written ffi_support based functions can just become a wrapper around a more uniffi-friendly function. Obviously the exact shape will depend on how things are laid out in your crates - ie, if you are trying to go the other way (ie, a uniffi-exposed function is what makes that call), then it's the same basic idea - your crate has the uniffi-friendly function which manually uses ffi_support to be able to call the extern function.

**Comment by mhammond** [comment]
UniFFI doesn't have a goal of making a C compatible API - it has a goal of allowing foreign languages to call Rust. It so happens that today it does that via a C API using specific types, but that's an implementation detail we don't want to commit to. It's the same as if you wanted to use our RustBuffer directly - we want to be free to change that detail at any time.
