### ISSUE TITLE
Error mapping for io::Error?

### ISSUE THREAD

**Issue by julian-baumann** [mozilla/uniffi-rs#1475]
Is there any convenient way of defining an `io::Error` in the UDL language? Or do I have to create a new custom Error type and replace all occurrences in the rust code?
Would come in handy for traits like `Write` or `Read`, which return `io::Result`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-238)
┆Issue Number: UNIFFI-238

**Comment by mhammond** [comment]
Most of these errors have types which aren't able to be used with uniffi. The way we use it is generally to have an error enum and lean into `thiserror` - something like:
```
#[derive(Debug, thiserror::Error)]
pub enum ExternalError {
  #[error("IO Error: {reason}")]
  IOError { reason: String },
  ...
}
```

Then a `From` - `impl From<io::Error> for ExternalError { ... }`. You should then be able to use, say, `Ok(foo.read()?)` on the functions exposed by uniffi to perform the conversion.
