### ISSUE TITLE
Is it possible to disable clippy rules for included scaffolding?

### ISSUE THREAD

**Issue by stan-irl** [mozilla/uniffi-rs#1476]
I'm trying to setup some fairly strict rules on my codebase:
```
cargo clippy -- --all-targets --all-features -- \
	-D warnings \
	-D clippy::all \
	-D missing_docs \
	-D clippy::missing_docs_in_private_items \
	-D clippy::pedantic \
	-W clippy::nursery \
	-W clippy::cargo
```

The problem is that wherever I include scaffolding will fail because the generated code doesnt satisfy these rules. For example my lib.rs looks like this:
```
//! This crate contains a test component to use as a placeholder
use log::debug;

/// A basic no-op function that is
/// exposed through the interface
pub fn do_something() {
    debug!("Something");
}

/// A function that will always panic
///
/// # Panics
///
/// Will always panic
pub fn crash_now() {
    panic!("down i go...")
}

uniffi::include_scaffolding!("foo");
```

I can fix this by disabling these lints at the module level but that kinda defeats the purpose of setting them in the first place. the implementations need to be in the same place as `uniffi::include_scaffolding!()` so theres no way I can enforce stricter linting on my own code then you do in the scaffolding unless I use another layer of indirection which is also undesirable.

I've been trying stuff like:

```
#[allow(clippy::pedantic, clippy::missing_const_for_fn)]
uniffi::include_scaffolding!("foo");
``` 

but that doesnt work either. Do you have any recommendations for how to deal with this?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-239)
┆Issue Number: UNIFFI-239

**Comment by stan-irl** [comment]
My main concern right now is that I cant run with `-D missing_docs`  which means that I have no way to enforce comments on the APIs I'm  exposing

**Comment by mhammond** [comment]
I don't think we have a good story for this, but I think we'd be fine with unconditionally adding "reasonable" clippy exclusions, of which `missing-docs` would seem to qualify,

**Comment by stan-irl** [comment]
No worries. I'll add it on monday. it should just be a one-liner right?

**Comment by mhammond** [comment]
You might need a few one them - eg, one for function, enums, structs, etc?

**Comment by mhammond** [comment]
(OTOH though, I wonder why anyone would *ever* want to see clippy errors in uniffi-generated code? Should we see if we can kill them all?)

**Comment by stan-irl** [comment]
> (OTOH though, I wonder why anyone would *ever* want to see clippy errors in uniffi-generated code? Should we see if we can kill them all?)

This is personally what I think. I think it's pretty easy to kill them but maybe you guys use them for verification or something internally??

**Comment by stan-irl** [comment]
ooh this is smart. i will try it out. thanks for the heads up! I think we can close this then?

**Comment by stan-irl** [comment]
I will reopen if I run into other issues with this.
