### ISSUE TITLE
Ability to throw different kinds of exceptions/errors

### ISSUE THREAD

**Issue by raweber42** [mozilla/uniffi-rs#1504]
In my project we need a way of saying that a function can return multiple different error types, so that another team can just watch out for let's say three different exceptions in a try/catch way instead of having to parse through the sub-types of just one error type (with type-casting etc..) .

Is there a way to say something in the udl file like:
```
[Throws=Error1, Throws=Error2]
Status get__status(string tid);
```

If not: Is this a feature we could add?
Thanks in advance!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-248)
┆Issue Number: UNIFFI-248

**Comment by mhammond** [comment]
Enums are typically used in this scenario. I might be missing the point though, as I don't see how that would work in Rust - what does the Rust signature of `get__status()` look like?
