### ISSUE TITLE
Swift bindings does not compile

### ISSUE THREAD

**Issue by conanoc** [mozilla/uniffi-rs#1505]
`uniffi-bindgen generate` succeeded in generating Swift bindings, but they make compile errors when they are included in an app:

![capture](https://user-images.githubusercontent.com/11764352/229416234-8a385562-52b9-479d-9813-1023e6eaca23.jpeg)

Error messages are:
```
Cannot find 'void' in scope
'>' is not a postfix unary operator
Cannot find '_Nonnull' in scope
```

I ran this to generate Swift bindings:
```
cargo run --bin uniffi-bindgen generate uniffi/askar.udl --language swift -o out --lib-file target/debug/libaries_askar.dylib
```

The async function `askar_store_open()` is defined like this:
```Rust
#[uniffi::export]
pub async fn askar_store_open(
    spec_uri: String,
    key_method: Option<String>,
    pass_key: Option<String>,
    profile: Option<String>,
) -> Result<Arc<AskarStore>, ErrorCode> {
// ...
}
```

And `AskarStore` struct is defined in UDL:
```
interface AskarStore {};
```

I'm referring the main branch of uniffi-rs like this:
```
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", optional = true }
uniffi_bindgen = { git = "https://github.com/mozilla/uniffi-rs.git", optional = true }
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-249)
┆Issue Number: UNIFFI-249

**Comment by badboy** [comment]
this can be simplified to

```rust
#[derive(uniffi::Object)]
pub struct Object;

#[uniffi::export]
pub async fn get_object() -> Arc<Object> {
    Arc::new(Object)
}
```

The return type gets written here: https://github.com/mozilla/uniffi-rs/blob/e8e5ff6a6cfe1adc18956e12d05b319b1210698e/uniffi_bindgen/src/bindings/swift/templates/TopLevelFunctionTemplate.swift#L25

`Arc` is expressed as `void*_Nonnull`.

cc @Hywan would you be able to take a look?

**Comment by Hywan** [comment]
I will, but not before 3 weeks. Does it work?

**Comment by badboy** [comment]
> I will, but not before 3 weeks. Does it work?

Sure thing! Thanks.

**Comment by Hywan** [comment]
Can you assign the task to me maybe?
