### ISSUE TITLE
Async function panic

### ISSUE THREAD

**Issue by conanoc** [mozilla/uniffi-rs#1513]
When I called an async function from Swift, I got the following error:
```
Test Case '-[AskarTests.StoreTests testInsertUpdate]' started.
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime',
/Users/conanoc/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-core-0.5.13/src/pool/inner.rs:330:5
```

Possibly incompatible with sqlx 0.5.13?
sqlx dependency is defined like this:
```
[dependencies.sqlx]
version = "0.5.13"
default-features = false
features = ["chrono", "runtime-tokio-rustls"]
optional = true
```

Any guide to avoiding this?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-251)
┆Issue Number: UNIFFI-251

**Comment by pablogeek** [comment]
how can I do this with udl file?

**Comment by mhammond** [comment]
> how can I do this with udl file?

I don't think it's possible to specify the async runtime in UDL.

**Comment by pablogeek** [comment]
so, if I am using udl file, do I need to get rid of it first to use this anotation?

**Comment by mhammond** [comment]
You probably do not need to get rid of your UDL entirely, but that one specific object should be declared using procmacros, and probably still referenced in the UDL via https://mozilla.github.io/uniffi-rs/latest/udl/ext_types.html. However, if you don't really need UDL, moving everything to procmacros might well be easier and better over the longer term.

**Comment by mhammond** [comment]
> In our case we can't remove the UDL as we need it to generate the Kotlin bindings. It doesn't seem like we can use external types as we get this error "External missing kind".

You can generate kotlin without the UDL - you pass the built library instead.

> Workaround we are using is to have 2 UDL files, one as before that is used to generate Kotlin bindings, and one to use with include_scaffolding!() with all the objects we used procmacros instead for removed. This resulted in checksum errors, 

Sorry you are needing to do that 😱 It sounds like something else is going wrong - we really should be able to avoid that.

**Comment by chris13524** [comment]
> You can generate kotlin without the UDL - you pass the built library instead.

Thanks for the tip! We moved to this approach and it's much nicer anyway to generate the bindings with macros and ditch the UDL file. Thanks!
