### ISSUE TITLE
Swift warnings " keyword 'foo' does not need to be escaped in argument list"

### ISSUE THREAD

**Issue by ijc** [mozilla/uniffi-rs#1522]
I see these warning in practice in my project where they cause xcode to show a yellow wanting triangle on every build which is a little distracting (but it's not a blocker/fatal error).

There's also quite a lot of them in the `docker/deploy-dockerhub.sh` tests, for example:
```console
$ cargo test -p uniffi-fixture-regression-callbacks-omit-labels
...
running 1 test
   Compiling uniffi-fixture-regression-callbacks-omit-labels v0.22.0 (/mounted_workdir/fixtures/regressions/swift-callbacks-omit-labels)
    Finished dev [unoptimized + debuginfo] target(s) in 0.41s
/mounted_workdir/target/tmp/uniffi-fixture-regression-callbacks-omit-labels-ad67bc1edfaf9509/regression_test_callbacks_omit_labels.swift:433:13: warning: keyword 'name' does not need to be escaped in argument list
            `name`: FfiConverterString.read(from: &buf)
            ^    ~
                 
/mounted_workdir/target/tmp/uniffi-fixture-regression-callbacks-omit-labels-ad67bc1edfaf9509/regression_test_callbacks_omit_labels.swift:531:13: warning: no calls to throwing functions occur within 'try' expression
            try swiftCallbackInterface.`didReceiveFriendRequest`(
            ^
test uniffi_foreign_language_testcase_test_swift ... ok
```

Ideally the codegen would only quote things which need quoting (might be compilcated?) or the warning would be suppressed for the file in question (although my googling suggests there's not a pragma-like mechanism to achieve this).

I'm following the [book's](https://mozilla.github.io/uniffi-rs/swift/xcode.html) advice on xcode integration so my "Compile Sources" phase only has the udl file in it and not the swift file so I don't know how/where I could add a compiler option to suppress the warning, but another option might be to document how to do that.

**Comment by mhammond** [comment]
There's no good way to kill those warnings - #1460 is a dupe, and there the agreement seems to be that we need to hard-code a list of actual keywords and only escape them.
