### ISSUE TITLE
Can I somehow represent &str in enums?

### ISSUE THREAD

**Issue by gyzerok** [mozilla/uniffi-rs#1526]
Hello everyone! Was really happy to find your project, it saves me so much time and headache. Love the effort!

I am writing a cross-platform library to use on iOS, Android and web which parses strings using `nom` and returns list of tokens:
```rust
// simplified example

pub enum Token = {
  Plain { text: String },
  Linebreak,
}

pub fn parse(input: String) -> Vec<Token> {}
```

Ideally I'd use `&str` instead of `String` where possible to improve performance. Which means that my code should look like:
```rust
pub enum Token<'a> = {
  Plain { text: &'a str },
  Linebreak,
}

pub fn parse(input: &str) -> Vec<Token<'_>> {}
```

However I have problems using `uniffi` for such signatures. It says `enum interface variant fields must not have attributes`.

Here is how I imagine this should be written in UDL:
```
namespace text_me {
  sequence<Token> parse([ByRef] string input);
};

[Enum]
interface Token {
  Plain([ByRef] string text);
  LineBreak();
};
```

Is there any workaround for this? Maybe I should design my data structures differently?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-255)
┆Issue Number: UNIFFI-255

**Comment by mhammond** [comment]
Lifetimes aren't supported and probably never will be as the concept doesn't really map to any of the foreign languages

**Comment by gyzerok** [comment]
I see, thank you!
