### ISSUE TITLE
Uniffi expects library with name uniffi_<name>.so

### ISSUE THREAD

**Issue by vrrashkov** [mozilla/uniffi-rs#1533]
I am not sure if my setup is not correct but here is what I have. 

![image](https://user-images.githubusercontent.com/1792272/236673122-2cfdc081-980d-451a-a902-24f9455af472.png)

Also I am using rust for android and this is my cargo setup and as you can see the libtokens.so is in the project successfully.

![image](https://user-images.githubusercontent.com/1792272/236673266-2cf608ad-a27a-4d08-a1b6-7a42a72c94c6.png)

But when I run the app, not sure why it gives me error that it expects libuniffi_tokens.so and not the libtokens.so

![image](https://user-images.githubusercontent.com/1792272/236673288-bb60b7f9-61ab-4b78-815e-fad7530eb1e0.png)

Not sure what I am missing or doing wrong here.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-258)
┆Issue Number: UNIFFI-258

**Comment by tarikeshaq** [comment]
Hi! This is likely because the generated kotlin code is attempting to open a library called `libuniffi_{cratename}.so`. 

That's the default the Kotlin generated code attempts to open. You can configure the library name by setting the `cdylib_name` value in your `uniffi.toml`.

For example, the following configures the generated kotlin code to load a library named `libmegazord.so`: https://github.com/mozilla/application-services/blob/736b5ed3fe0ccafd66bf17768ef1c5cc4b5779c4/components/fxa-client/uniffi.toml#L3

**Comment by vrrashkov** [comment]
Thank you for the fast response.  This indeed fix the issue but a new one appeared.

![image](https://user-images.githubusercontent.com/1792272/236761161-0653e23f-bda9-4872-82de-d1cee050b0e9.png)

From what I saw this is due to miss match between version of uniffi-bindgen.  I tried to install the 0.22.0

`cargo install --force --version 0.22.0 uniffi_bindgen`

`uniffi_build = { version = "0.22.0", features = ["builtin-bindgen"] }`

But the error is still the same.  I researched and from this issue (#1190)  saw that to ensure the versions I should use this directly:

https://github.com/mozilla/application-services/tree/main/tools/embedded-uniffi-bindgen

I have not tried that yet but wanted to check if this is still the case and there is no other solution to this?

**Comment by badboy** [comment]
Using your own wrapper a la the `embedded-uniffi-bindgen` is indeed the recommended, and from 0.23 actualy only, way to do this.

**Comment by vrrashkov** [comment]
I put the embedded uniffi but still getting the same error. Here is the code I currently have.

```
android.libraryVariants.all { variant ->
    def uniffiGeneratedPath = "${buildDir}/generated/source/uniffi/${variant.name}/java"
    def t = tasks.register("generate${variant.name.capitalize()}UniFFIBindings", Exec) {
        workingDir project.rootDir
        commandLine 'cargo', 'run', '--package', 'embedded-uniffi-bindgen', 'generate', "${project.rootDir}/rust/tokens/src/tokens.udl", '--language', 'kotlin', '--out-dir', "${uniffiGeneratedPath}"
        outputs.dir "${uniffiGeneratedPath}"
        // Re-generate if the interface definition changes.
        inputs.file "${project.rootDir}/rust/tokens/src/tokens.udl"
        // Re-generate if our uniffi-bindgen tooling changes.
        inputs.dir "${project.rootDir}/rust/tools/embedded-uniffi-bindgen/"
        // Re-generate if our uniffi-bindgen version changes.
        inputs.file "${project.rootDir}/Cargo.lock"
    }
    variant.registerJavaGeneratingTask(t.get(), new File(uniffiGeneratedPath))

    variant.javaCompileProvider.get().dependsOn(t)
    def sourceSet = variant.sourceSets.find { it.name == variant.name }
    sourceSet.java.srcDir new File(uniffiGeneratedPath)
    // XXX: I've been trying to make this work but I can't, so the compiled bindings will show as "regular sources" in Android Studio.
    idea.module.generatedSourceDirs += file("${uniffiGeneratedPath}/uniffi")
}
```

This is the cargo for the embedded uniffi

```
[package]
name = "embedded-uniffi-bindgen"
version = "0.1.0"
authors = ["The Firefox Sync Developers <sync-team@mozilla.com>"]
edition = "2021"
license = "MPL-2.0"
publish = false

[dependencies]
anyhow = "1"
camino = "1.1.1"
# TODO: Depend on `uniffi`, but avoid the clap dependency.
uniffi_bindgen = { version = "0.23.0", default-features = false }
```

This is the Cargo from my main package:
```

[package]
name = "tokens"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
uniffi = { version = "0.23.0" }

[build-dependencies]
uniffi_build = { version = "0.23.0", features = ["builtin-bindgen"] }

# static lib is for ios
[lib]
crate-type = ["lib", "cdylib"]
name = "tokens"

```

When building the kotlin code is being generated successfully as you can see:

![image](https://user-images.githubusercontent.com/1792272/236823679-8d8b0bd4-7317-4646-abd8-3018b585d604.png)

But still I am getting the same error.

![image](https://user-images.githubusercontent.com/1792272/236823772-3cb36394-ce49-41f0-9a6e-3c7eeb5f0fd7.png)

**Comment by vrrashkov** [comment]
I did clean both and rebuild multiple times, but still the error persists. It might be something I am missing for sure as I am pretty new in rust. Here is the full project if you want to check.

https://github.com/vrrashkov/Tokens

It's nothing special I am just trying to run a simple function "add".

**Comment by badboy** [comment]
You're missing the `uniffi::include_scaffolding!("tokens");` line in your `src/lib.rs`.
uniffi-bindgen will generate the FFI-compatible API, but that needs to end up in your final build. Without the compiled library will not have the required symbols.

**Comment by vrrashkov** [comment]
Thank you I guess I forgot to add that part. Other than adding the scaffolding I encountered another issue after that this one here [#118](https://github.com/mozilla/rust-android-gradle/issues/118#issuecomment-1487844850) and used this fix. 

So finally the setup is done, thank you for the time and help :)
