### ISSUE TITLE
Lossy, silent `float` → `int` conversion for `int*` parameters in Python

### ISSUE THREAD

**Issue by heinrich5991** [mozilla/uniffi-rs#1544]
It seems the Python bindings lossily convert `float` to `int`, and now that I look at it, would also convert strings to `int`. E.g. with the example from the tutorial
```udl
namespace math {
  u32 add(u32 a, u32 b);
};
```
it'd mean that the call `math.add("1234", 5.678)` would succeed and return `1239`. This is unexpected for me, because Python usually is type-safe to a degree. Functions taking integers don't work on strings or floats, as an example, see e.g. `chr`:
```py
>>> math.add("1234", 5.678)
1239
>>> chr("1234")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object cannot be interpreted as an integer
>>> chr(5.678)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer
```

I'd suggest to follow the example of Python's built-in functions and return an error for these cases. This would be a **backward-incompatible change**.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-267)
┆Issue Number: UNIFFI-267

**Comment by mhammond** [comment]
I agree this is a fairly large foot-gun and something we should fix.

**Comment by heinrich5991** [comment]
> I believe we do a similar coercion for [each numeric type and bool](https://github.com/mozilla/uniffi-rs/blob/58e0a24dbcd2785c71dd2ccffd99f892abf9e785/uniffi_bindgen/src/bindings/python/gen_python/primitives.rs#L58-L69). There's also a [coercion for optionals](https://github.com/mozilla/uniffi-rs/blob/58e0a24dbcd2785c71dd2ccffd99f892abf9e785/uniffi_bindgen/src/bindings/python/gen_python/compounds.rs#LL36C1-L43C2) that seems like a no-op to me.
> 
> What's the use case for these? My feeling right now is we should remove the coerce code.

Python does some coercion on its own, but it uses the `__index__()` magic method for coercing objects to integers. This works on 0-dimensional numpy arrays for example, but fails for floats.

**Comment by mhammond** [comment]
My involvement in python these days is really limited to pywin32, so TIL about `__index__` and the fact later versions don't even call `__int__` any more :) However, my gut feeling is that object->numeric conversions does make some sense, but builtin->builtin conversions make less sense. IIRC, the C API methods (eg, `PyLong_AsLong` etc) "do the right thing" here, whereas I'm really not sure how to spell some of these in a pythonic API (ie, `int()` isn't correct as we are discussing). Maybe we just manually reimplement the "expected" semantics, where "expected" is something like "as defined by the c api"?

**Comment by jeddai** [comment]
It was added here: https://github.com/mozilla/uniffi-rs/commit/fdef1c3cf652bf94fb5298af51dc047d6b62cdab#diff-ece71c4a83a17544c6f0c12c32ac25caec9661cd783aea4377d7f20043253948

**Comment by heinrich5991** [comment]
@badboy Do you remember the reason for adding this coercion? Could it be replaced by a stricter version like `.__index__()`?

**Comment by badboy** [comment]
> It was added here: [fdef1c3#diff-ece71c4a83a17544c6f0c12c32ac25caec9661cd783aea4377d7f20043253948](https://github.com/mozilla/uniffi-rs/commit/fdef1c3cf652bf94fb5298af51dc047d6b62cdab#diff-ece71c4a83a17544c6f0c12c32ac25caec9661cd783aea4377d7f20043253948)

We had coercion before that, see https://github.com/mozilla/uniffi-rs/commit/fdef1c3cf652bf94fb5298af51dc047d6b62cdab#diff-e9c52b12e49715fece4de9daf4a3cd5b57e039add4a05399452c9a8cf796df25L361
I just changed where that is handled.

I don't know the exact reasoning but I figured the idea is to guarantee somewhat coherent types when passing on data.
I don't know `__index__` so I can't say if that's more correct for integers.

This is definitely a bit of a footgun right now (and hey, #1172 would help, as long as you use a type checker).
I think introducing proper runtime type checks where necessary is now the right thing though.

**Comment by badboy** [comment]
```python
>>> True.__index__()
1
>>> (1).__index__()
1
>>> (1.2).__index__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'float' object has no attribute '__index__'. Did you mean: '__init__'?
>>> "foo".__index__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute '__index__'. Did you mean: '__init__'?
>>> {}.__index__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute '__index__'. Did you mean: '__init__'?
>>> ().__index__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tuple' object has no attribute '__index__'. Did you mean: '__init__'?
>>> [].__index__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute '__index__'. Did you mean: '__iadd__'?
```

For integers at least this would exclude everything but numbers and booleans, so that's good.

**Comment by jeddai** [comment]
> We had coercion before that, see https://github.com/mozilla/uniffi-rs/commit/fdef1c3cf652bf94fb5298af51dc047d6b62cdab#diff-e9c52b12e49715fece4de9daf4a3cd5b57e039add4a05399452c9a8cf796df25L361
I just changed where that is handled.

Ah gotcha, sorry I missed that.
