### ISSUE TITLE
`callback interface` returning `void` causes "reading the unit type is not allowed"

### ISSUE THREAD

**Issue by ijc** [mozilla/uniffi-rs#1547]
A `callback interface` method which returns void is resulting in `reading the unit type is not allowed` when lifting the result.

This started in #1515 and persists at current main 58e0a24dbcd2785c71dd2ccffd99f892abf9e785.

The commit message for 884403ddb0e994e1807b49119e9ec2090e2ac27e mentions using a `u8` as a placeholder for `void` returns from async functions, but these are not async so I'm not sure what is going wrong but maybe it's to do with those changes.

I have pushed a reproducer to: https://github.com/mozilla/uniffi-rs/compare/main...ijc:uniffi-rs:add-test-for-callback-returning-void (first commit is based at a93713ac0c87d7a5dc69763e143cc2f39e34f3c6 where it passes, then master is merged ontop to demonstrate the failure). I'll convert that to a PR if I can spot the issue.

/cc @bendk.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-266)
┆Issue Number: UNIFFI-266

**Comment by ijc** [comment]
This works but I'm a bit unsure since it undoes part of the intention of 884403ddb0e994e1807b49119e9ec2090e2ac27e. I wondered if something somewhere should be calling `lower_return` instead of `try_read` but not sure what/where.

```diff
--- a/uniffi_core/src/ffi_converter_impls.rs
+++ b/uniffi_core/src/ffi_converter_impls.rs
@@ -139,7 +139,7 @@ unsafe impl<UT> FfiConverter<UT> for () {
     }
 
     fn try_read(_: &mut &[u8]) -> Result<()> {
-        panic!("reading the unit type is not allowed")
+        Ok(())
     }
 
     fn lower_return(_: ()) -> Result<Self::ReturnType, RustBuffer> {
```

**Comment by bendk** [comment]
I think the fact that the method also throws an error is key here.  The [callback interface template code](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/scaffolding/templates/CallbackInterfaceTemplate.rs#L71-L83) has a special case for void returns, but not for void returns + an error.

The simplest solution would be to add a `invoke_callback_void_return_with_error()` function and call it from the template.  But I've been meaning to simplify that using the `FfiConverter` trait.  I'm going to try to implement that now.
