### ISSUE TITLE
Adding types defined in external crates using `--library` flag

### ISSUE THREAD

**Issue by thunderbiscuit** [mozilla/uniffi-rs#1563]
I'm trying to build a uniffi example where a `calendar` library depends on an enum type `ClockType` defined in a separate library. My example/sandbox repository is [here](https://github.com/thunderbiscuit/uniffi-examples/) and the specific PR where I add this example [is here](https://github.com/thunderbiscuit/uniffi-examples/pull/2).

I have read the [latest doc sections on this](https://mozilla.github.io/uniffi-rs/tutorial/foreign_language_bindings.html#running-uniffi-bindgen-using-a-library-file) added in #1516, and seen the example in [fixtures/ext-types](https://github.com/mozilla/uniffi-rs/tree/main/fixtures/ext-types). But after much stumbling about and fiddling with the crates I still can't get this library to work...

My latest iteration throws the following error when attempting to generate the bindings file:
```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: cargo metadata returned 0 packages for crate name clock_ffi'
```

I assume this is because the clock_ffi crate is not actually published but is rather a local crate and the tool is not picking up on that fact (does that make sense?) but I'm not sure how to help it find what it needs.

My current workflow is the following:
```shell
cd ./6-multiple-libraries/
cargo build
cargo run --package uniffi-bindgen -- generate --library ./target/debug/libcalendarffi.dylib --language kotlin --out-dir ./calendar-kotlin/lib/src/main/kotlin --no-format
```

If this compiles I should be able to build the Kotlin lib and run the tests using
```shell
cd ./6-multiple-libraries/calendar-kotlin/
./gradlew buildKotlinLib
./gradlew test
```

Any tips for me on how to get unstuck here would be super appreciated!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-273)
┆Issue Number: UNIFFI-273

**Comment by stan-irl** [comment]
I was getting this when my crate type was `rlib`, not `lib`. Internally [uniffi-bindgen is filtering](https://github.com/mozilla/uniffi-rs/pull/1516/files#diff-a2c8329d265afcb1ea0c4ba6f2ab1bb5cf71ab6be23d2a8a8cdc437adb5ca671R157) for `lib`.

 I fixed it by setting my Config.toml to
```
[lib]
name = "clock_ffi"
crate-type = ["lib", "cdylib"]
```

**Comment by thunderbiscuit** [comment]
Thank you! This totally solved my issue. Example is now complete and functional [here](https://github.com/thunderbiscuit/uniffi-examples/tree/master/6-multiple-libraries).

It does bring up the fact that I am not yet clear on what exact crate types (and why) should be defined in my `Cargo.toml`, and whether they should be different types between the "dependency" and the "final lib" (some info [on this page](https://mozilla.github.io/uniffi-rs/tutorial/Prerequisites.html?highlight=cd#build-your-crate-as-a-cdylib) but it's not complete). I'll open up a separate issue on this because I don't think it's defined clearly in the docs.
