### ISSUE TITLE
`#[uniffi(flat_error)]` is misnamed

### ISSUE THREAD

**Issue by mhammond** [mozilla/uniffi-rs#1565]
As I tried to demonstrate in #1564, I think using `flat_error` in this context is very misleading - mainly because the same concept in `uniffi_bindgen` is also extremely misleading! However, this is user-exposed.

`#[uniffi(flat_error)]` doesn't actually say anything about the error - about whether it is flat or not. It doesn't even change things to ensure the error is lowered as flat - any such errors are unconditionally lowered as though each variant had a single associated string, and also forces that the variant implement `to_string()`! The only way to get truly flat errors is *to not* use this attribute!

What this actually means is something like `#[uniffi(lower_with_string_variants)]` but I don't really like that. Or maybe `lower_as_to_string` to try and lessen the surprise of such errors needing to implement `Display`? . So I guess I have 2 questions:
* What's a better name!
* @jplatte, do you think we can just change it (ie, make it a breaking change for procmacro users), or must we do a deprecation dance?

**Comment by bendk** [comment]
`lower_as_string` is fine with me.  However, I kind of want to kill the entire concept and replace it using some of our newer features.  So maybe we should keep the name around for now and work out how to replace/deprecate it for `v0.25`.  I don't feel too strongly either way though.

**Comment by jplatte** [comment]
We have transitioned a handful of error enums to the proc-macro frontend that use this, I implemented it for that.
