### ISSUE TITLE
Write in the manual how to transpose cargo doc to product API binding documentation.

### ISSUE THREAD

**Issue by gogo2464** [mozilla/uniffi-rs#1571]
Hello,

I would like to document my python api with uniffi. Could we create something in order to document the new code please?

Best regards.

**Comment by badboy** [comment]
Is #200 covering what you request here?

**Comment by gogo2464** [comment]
Probably. Thanks @badboy I probably missed that I could do:

https://github.com/mozilla/uniffi-rs/issues/200#issuecomment-1469934813 

due to the lack of doc in the book.

Let's add it.

**Comment by badboy** [comment]
Closing this in favor of #200 then. Right now we have nothing landed. Docs should go along with code that we land for it though.
