### ISSUE TITLE
Generate bindings for kotlin requires a cdylib, but .dll was given

### ISSUE THREAD

**Issue by soupslurpr** [mozilla/uniffi-rs#1581]
Hi, I am on the latest commit of uniffi-rs, I'm on Windows. I am encountering an issue when trying to do cargo run --bin uniffi-bindgen generate --crate transcriber --language kotlin --out-dir out --library \Users\user\projects\transcriber\target\debug\transcriber.dll

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Generate bindings for kotlin requires a cdylib, but \Users\user\projects\transcriber\target\debug\transcriber.dll was given', C:\Users\user\.cargo\git\checkouts\uniffi-rs-6f89edd2a1ffa4bd\49f6033\uniffi\src\lib.rs:36:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\uniffi-bindgen.exe generate --crate transcriber --language kotlin --out-dir out --library \Users\user\projects\transcriber\target\debug\transcriber.dll` (exit code: 101)
```

My Cargo.toml has 
[lib]
crate-type = ["lib", "cdylib"]

I have tried the other files in the build folder such as libtranscriber.d, libtranscriber.rlib, transcriber.d, transcriber.dll.exp, transcriber.dll.lib, and transcriber.pdb, but they all say "Unknown library format".

So I don't see why I am getting this error, please help.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-279)
┆Issue Number: UNIFFI-279

**Comment by soupslurpr** [comment]
`cargo run --bin uniffi-bindgen generate src/transcriber.udl --language kotlin` successfully works btw

**Comment by badboy** [comment]
This is a bug in `calc_cdylib_name`:

https://github.com/mozilla/uniffi-rs/blob/49f603387f0a99ca31e439871f6695568bee873d/uniffi_bindgen/src/library_mode.rs#L105-L114

We're trying to strip a `lib` prefix, but that will return `None` for Windows libraries, because they don't start with `lib`.
I'll send a PR shortly.

**Comment by soupslurpr** [comment]
Thank you
