### ISSUE TITLE
Is there is a way to include Rust documentation I have in my lib code to the generated code Kotlin & Swift?

### ISSUE THREAD

**Issue by hamada147** [mozilla/uniffi-rs#1612]
I've built a Rust lib that I'm sharing with Kotlin (JVM & Android) and Swift (iOS & macOS) using UniFFI, and I'm trying to include the documentation in the generated Kotlin & Swift code. Can this documentation be included along with the generated code?

**Comment by badboy** [comment]
Not currently. See https://github.com/mozilla/uniffi-rs/issues/200
