### ISSUE TITLE
Support rendering simple newtypes as the inner type?

### ISSUE THREAD

**Issue by ijc** [mozilla/uniffi-rs#1639]
I'm working with some generated code which makes extensive use of newtypes to give e.g. each string field in a struct a distinct type. I'd like to expose all these via proc macros.

So there is lots of:

```rust
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub struct Foo(String);
```
and then used as fields `struct Bar { foo: Foo, ... }` etc.

Since I'm rewriting things any way (to add the `#[derive(uniffi::Foo)]` macros) I'm able to inject an impl:

```rust
quote! {
    unsafe impl uniffi::FfiConverter<crate::UniFfiTag> for #ident {
        type FfiType = <#ty as uniffi::FfiConverter<crate::UniFfiTag>>::FfiType;

        const TYPE_ID_META: uniffi::MetadataBuffer = uniffi::MetadataBuffer::from_code(uniffi::metadata::codes::TYPE_CUSTOM)
            .concat_str(#ident_str)
            .concat(<#ty as uniffi::FfiConverter<crate::UniFfiTag>>::TYPE_ID_META);

        fn lower(obj: Self) -> Self::FfiType {
            <#ty as uniffi::FfiConverter<crate::UniFfiTag>>::lower(obj.0)
        }

        uniffi::ffi_converter_default_return!(crate::UniFfiTag);

        fn try_lift(v: Self::FfiType) -> Result<Self, uniffi::deps::anyhow::Error> {
            <#ty as uniffi::FfiConverter<crate::UniFfiTag>>::try_lift(v).map(Self)
        }

        fn write(obj: Self, buf: &mut Vec<u8>) {
            <#ty as uniffi::FfiConverter<crate::UniFfiTag>>::write(obj.0, buf)
        }

        fn try_read(buf: &mut &[u8]) -> Result<Self, uniffi::deps::anyhow::Error> {
            <#ty as uniffi::FfiConverter<crate::UniFfiTag>>::try_read(buf).map(Self)
        }
    }
}
```

Could we consider adding this to the proc macros themselves and autogenerating into the scaffolding, either as an implicit thing for any struct with a single anonymous field or perhaps as an explicit `#[derive(unifii::Struct(transparent))]` type thing perhaps?

**Comment by mhammond** [comment]
> Since I'm rewriting things any way (to add the #[derive(uniffi::Foo)] macros) I'm able to inject an impl:

You will always need to add that `derive`, so can't you also inject the impl via a local procmacro or similar?

I don't quite understand the use-case though - it sounds like you are trying to have uniffi generate code for some other code generator. Is it possible to restate it in a way that has a common use-case, or restated in a way that someone else could say "yes, that sounds like it might be useful in some general cases"?

**Comment by ijc** [comment]
> You will always need to add that derive, so can't you also inject the impl via a local procmacro or similar?

We could, I was mostly wondering if this would be useful to others.

> I don't quite understand the use-case though - it sounds like you are trying to have uniffi generate code for some other code generator. Is it possible to restate it in a way that has a common use-case, or restated in a way that someone else could say "yes, that sounds like it might be useful in some general cases"?

We are going from a schema language schema  (we haven't picked yet, lets say jsonschema for the sake of argument) of a type via some existing tool for generating Rust types from that schema but we also want to use them in our FFI API so are adding the derives (and this `impl`) by rewriting programmatically.

I think that's a bit of a niche case though, really what I was thinking, but not saying clearly, with this issue was that new types were a fairly common idiom in Rust and if I was introducing one by hand in my code I'd like to be able to  `#[derive(uniffi::SomeThing)]` instead of writing it myself (either by hand or by adding a proc macro to my workspace).

Adjusting/expanding the example from the [New Type Idiom](https://doc.rust-lang.org/rust-by-example/generics/new_types.html) chapter of Rust By Example I think it is reasonable to want to do:

```rust
#[derive(uniffi::SomeThing)]
struct Years(i64);

#[derive(uniffi::SomeThing)]
struct Days(i64);

#[uniffi::export]
fn old_enough(age: &Years) -> bool {
    age.0 >= 18
}

#[derive(uniffi::Record)]
struct Person {
    name: String
    age: Years
    attendance: Days
}
```

Writing that I realised that maybe `Years` and `Days` could be `#[derive(uniffi::Object)]` but then IIRC they'd have to be put in an `Arc` in the record.

**Comment by mhammond** [comment]
> Writing that I realised that maybe `Years` and `Days` could be `#[derive(uniffi::Object)]`

I guess these are also close to a `#[derive(uniffi::Record)]`, it's just that the fields are not named?

**Comment by mhammond** [comment]
A guess a bigger question though is what semantics the foreign bindings should have. If they should be opaque, then this example really just looks like a [custom type](https://github.com/mozilla/uniffi-rs/blob/main/fixtures/ext-types/guid/src/lib.rs#L2)

**Comment by mhammond** [comment]
> I think from an FFI PoV they should behave just like the inner type, not be opaque.

So in your example, Python code would see `Years` as a tuple? What would languages without a tuple concept do instead?

**Comment by mhammond** [comment]
Oops, I guess that's what you meant by:

> Depending on the target language that might mean the "real distinct type" nature is lost and they are just like plain aliases,

But this seems strange to me - either the "inner" part is valuable enough for languages like Python such that it makes sense to expose the inner part - but this leaves the other languages effectively unable to use the type as that "important" capability can't be expressed - or the inner details aren't so valuable that it means those other languages work fine, in which case we need to ask: why bother exposing the inner details to Python?

**Comment by ijc** [comment]
The inner type here is `i64` not a tuple. The outer type is a "[Tuple Struct](https://doc.rust-lang.org/book/ch05-01-defining-structs.html#using-tuple-structs-without-named-fields-to-create-different-types)". In essence a new type is a specific use case of a tuple struct with a single field[^0]. The point of a new type here is to create "an i64 which is distinct in the type system from any other i64", i.e. it stops the programmer from using `Years` where `Days` was needed.

So I would expect this to be exposed to FFI as whatever an `i64` is exposed as, so I guess as some sort of number for Python, a `Long` to Kotlin or an `Int64` in Swift. 

That's probably as good as it gets for Python. I'm no expert but Kotlin seems to have a thing call "[Value Classes](https://quickbirdstudios.com/blog/kotlin-value-classes/)" which look like they might have some overlap with the new type concept in Rust so maybe we would expose as a "Value Class of a Long"?

[^0]: There are other uses of tuple structs, which is why this thing would have to be opt-in, if you are using a tuple struct as something other than a "make this a distinct new type" idiom you might not want to expose the inner.

**Comment by mhammond** [comment]
> The inner type here is i64 not a tuple.

Thanks, I did understand that. What I didn't understand is that you wanted to special-case the 1 item tuple struct. I'd have thought something like, say, `Point(i64, i64)` would be just as useful here?

> So I would expect this to be exposed to FFI as whatever an i64 is exposed as

I don't quite understand - an i64 is exposed as an i64. But this still sounds like a `CustomType` to me - [here](https://github.com/mozilla/uniffi-rs/blob/main/examples/custom-types/src/custom-types.udl#L4-L5) we have a type called `Handle` which is moved over the FFI as an i64 and where the Rust type definition is `struct Handle(pub i64);`

**Comment by ijc** [comment]
>  I'd have thought something like, say, Point(i64, i64) would be just as useful here?

That's another useful use of tuple structs but I don't think that counts as the "New Type" idiom?

> I don't quite understand - an i64 is exposed as an i64. But this still sounds like a CustomType to me 

Thanks, that does indeed look close to what I am suggesting.

It looks like custom types current require UDL? Or did f0041800c48293d631a2f425861726a5440e245b add support for custom types via proc-macros too? (I can't quite tell, the commit is about external types and I'm not sure how close the relationship with custom types is, I think it might be enabling consuming but not defining them?).

I guess with the direction of the project towards enabling greater use of the proc macros that support will happen eventually if it isn't already there.

If we assume that proc-macro support for defining a custom type without UDL then I guess what I'm suggesting here amount to having the macros also be able to (optionally) generate the `impl UniffiCustomTypeConverter` in some cases (I'm suggesting for new types, but perhaps there are other tractable cases?).

**Comment by mhammond** [comment]
> It looks like custom types current require UDL?

Yeah, that's correct. External types different - they typically are "normal" uniffi types which are defined in a different crate or different UDL namespace, so are still quite opaque to the codegen.

> I guess with the direction of the project towards enabling greater use of the proc macros that support will happen eventually if it isn't already there.

The idea is that eventually there would be parity, so yeah.

> If we assume that proc-macro support for defining a custom type without UDL then I guess what I'm suggesting here amount to having the macros also be able to (optionally) generate the impl UniffiCustomTypeConverter in some cases

That sounds reasonable, but is only 1/2 the battle, right? The entire point of using the new type idiom would be defeated if the foreign bindings just got the plain-old builtin type, right? ie, you'd still need to do the dance on the foreign side to ensure the type is distinct over there too?

**Comment by ijc** [comment]
You are correct that as is the benefit is mainly on the Rust side. I don't think that makes it worthless (it's not an uncommon occurrence with FFI type things I guess). It would be awesome if it could leverage any similar language feature on the FFI side though!

For sure you wouldn't want to use it for anything more than the "stricter type alias" use case -- certainly not if you were encapsulating in order to maintain invariants!

Anyway, it sounds like overall there isn't much appetite for the idea, so we can close this if you like.

**Comment by mhammond** [comment]
> Anyway, it sounds like overall there isn't much appetite for the idea, so we can close this if you like.

Generating `UniffiCustomTypeConverter` in some cases does seem reasonable to me, so I'd be fine with having this issue track that. That doesn't sound useful to you though until proc_macros have support for custom types, but might still be worth exploring.

**Comment by ijc** [comment]
Yeah, I think proc macro support for custom types is a prerequisite.

**Comment by mhammond** [comment]
#1661 adds procmacro support for custom types and explicitly supports the "new type" idiom - I'd love your feedback on whether this helps your use-case!

**Comment by ijc** [comment]
@mhammond I'm away from my dev system for the next two weeks, but just looking at the pr it looks like it would work great.

Procmacro support for custom types more generally looks super useful too, many thanks!

**Comment by ijc** [comment]
@mhammond #1661 works very nicely.

The only quirk is that I had to add a `use crate::UniffiCustomTypeConverter` to the sub-mod which the new derives. I'll make a PR.
