### ISSUE TITLE
mention uniffi_macros = "*" in the rust book

### ISSUE THREAD

**Issue by gogo2464** [mozilla/uniffi-rs#1645]
since 0.23 uniffi_macros = "*" must be included in Cargo.toml with 

[dependencies]
uniffi = {version = "*", features = [ "cli" ]}
uniffi_macros = "*"
uniffi_bindgen = "*"

in order to avoid a uniffi_bindgen build fail with:

error[E0425]: cannot find function `uniffi_bindgen_main` in crate `uniffi`
 --> uniffi-bindgen.rs:2:13
  |
2 |     uniffi::uniffi_bindgen_main()
  |             ^^^^^^^^^^^^^^^^^^^ not found in `uniffi`

IT sounds necessary. Fell free to tell me if you have same issue. I may document it and be assigend in the issue if necessary.

**Comment by mhammond** [comment]
I don't think that's true, eg, [here's a Cargo.toml referencing 0.24](https://github.com/mozilla/application-services/blob/main/components/fxa-client/Cargo.toml) without any such requirement.

**Comment by gogo2464** [comment]
Strange. If you think so you may be right.

**Comment by YuchenJin** [comment]
Also facing this with uniffi==0.24.3, adding uniffi_macros="*" did fix this.

**Comment by andywwright** [comment]
@gogo2464 I have the same issue. PLEASE add this in the book

**Comment by gogo2464** [comment]
I may do this this week.

**Comment by mhammond** [comment]
See above - `uniffi_macros = "*"` should not be needed, so we'd be unlikely to take a patch which recommends it without a detailed explanation which explains why it's not used either inside the repo or by Mozilla's use of the repo.

**Comment by hhanh00** [comment]
> I don't think that's true, eg, [here's a Cargo.toml referencing 0.24](https://github.com/mozilla/application-services/blob/main/components/fxa-client/Cargo.toml) without any such requirement.

I don't see where this project calls `uniffi_bindgen_main`. In any case, the problem goes away if you include the "cli " feature.

**Comment by gogo2464** [comment]
> @gogo2464 I have the same issue. PLEASE add this in the book

Hello.

I am sorry that I did not do it yet. Do you still would like I do it? I could add it to the book REALLY this week if you like.

**Comment by hhanh00** [comment]
It is not necessary to have `uniffi_macros="*"` but you need `features=["cli"]` and the book mentions it on the command line of `cargo run`
