### ISSUE TITLE
Should defaults for non-primitive types continue to be supported?

### ISSUE THREAD

**Issue by 0xOmarA** [mozilla/uniffi-rs#1652]
I'm opening this issue as recommended by @badboy in #1649 to continue the discussion on whether UniFFI should continue to support defaults for non-primitive types or should it be restricted to primitive types only having defaults.

As a quick summary of why we're discussing this, it looks like defaults for non-primitives do not interface nicely with the Python bindings. The approach taken in the Python bindings generator works but it leads to some issues with type hints that we need to get around by using decorators to disable type checks for certain regions on the Python code. 

@mhammond suggested that UniFFI could stop supporting defaults for non-primitive types if this isn't something that people are currently using. 

My opinion on this: I personally tend to always avoid defaults in method or function arguments and typically model such behavior through a builder pattern way of constructing objects or through a constructor function that does not have the argument the caller wishes to default. So, I would personally vote for the removal of non-primitive defaults and examining whether defaults for primitives are valuable enough to continue supporting. 

How does everybody feel about this?

**Comment by mhammond** [comment]
> @mhammond suggested that UniFFI could stop supporting defaults for non-primitive types if this isn't something that people are currently using.
> 
> My opinion on this:

We need to answer that first question before opinions are particularly valuable - obviously no one will be forced to use these defaults.

To answer the first, can we answer these questions:
* Are they documented anywhere?
* Do any examples or fixtures or anything else actually use them in our repo?
If the answers to the above are "no", then it's probably worth checking if they actually work :)

**Comment by badboy** [comment]
> Do any examples or fixtures or anything else actually use them in our repo?

[Yes](https://github.com/mozilla/uniffi-rs/blob/e9193ca95b8116e504e5ef2a6b3d0916f7146dfe/examples/rondpoint/src/rondpoint.udl#L93)

**Comment by mhammond** [comment]
> Yes

Thanks, I had a quick look some time ago and failed to see that. So long as languages take a little care (eg, see the discussion in #1649) I don't see how this is actively a bad thing, so I'm struggling to find a reason to justify the removal of a feature that works and is in our examples. I can't see it [in the docs](https://mozilla.github.io/uniffi-rs/udl/functions.html#optional-arguments--default-values) so if we agree to keep it we should be sure to document it? (and indeed, far more about default values is missing from the docs - eg, no discussion of the "radix" etc magic which we support)

**Comment by 0xOmarA** [comment]
In regards to this, I mainly stated this option in my PR due to this [comment here](https://github.com/mozilla/uniffi-rs/pull/1649#issuecomment-1634181931). However, I personally do not have any strong feelings as to whether defaults for non-primitives should be supported or not. I may lean slightly towards them not being supported just to make things simpler, however, this isn't something I feel strongly about. So, I'm okay with either decision the team makes.

**Comment by mhammond** [comment]
Thanks - seeing as there is some support in our examples for this I really don't think we can justify removing this support without a really compelling reason. So let's close this and I opened #1653 to better document and test the existing support.
