### ISSUE TITLE
[Throws=..] attribute is not checked

### ISSUE THREAD

**Issue by arg0d** [mozilla/uniffi-rs#1656]
The title is pretty self explanatory. The following UDL file does not trigger any kind of errors by uniffi. It seems like the contents of `Throws` attribute are completely unchecked, because you can put whatever string value you want in there, and bindgen won't see any issues. Error are only detected when compiling generated Rust scaffolding or foreign language bindings code.

```
namespace error {
    [Throws=anyRandomString]
    void test();
};
```

In more exotic case, you may have a seemingly valid looking UDL file, and the scaffolding code might compile fine, but the resulting foreign language bindings may be broken: https://github.com/mozilla/uniffi-rs/issues/1067.

**Comment by mhammond** [comment]
I can no longer repro this - I now get `unknown type for error: anyRandomString`
