### ISSUE TITLE
failed to resolve: could not find `async_compat` in `deps` could not find `async_compat` in `deps`

### ISSUE THREAD

**Issue by soupslurpr** [mozilla/uniffi-rs#1688]
Hello, when using #[uniffi::export(async_runtime = "tokio")] on an async function, when building I get the following error:

failed to resolve: could not find `async_compat` in `deps`
could not find `async_compat` in `deps`

Thanks.

**Comment by badboy** [comment]
Did you enable the `tokio` feature on the `uniffi` dependency?

**Comment by soupslurpr** [comment]
Ahh, that fixed it! Thank you. Could this be mentioned in the documentation?
