### ISSUE TITLE
error[E0412]:cannot find type `UniFfiTag` in the crate root

### ISSUE THREAD

**Issue by 94Rahul** [mozilla/uniffi-rs#1695]

**Comment by mhammond** [comment]
There are many errors you can make which will cause this, so please give us the exact code you are using.

**Comment by 94Rahul** [comment]
I don't know how, but now I don't get this error in my code.

**Comment by RCasatta** [comment]
in my case was simply missing the call to 

`uniffi::setup_scaffolding!();`

**Comment by august-feng** [comment]
It's mentioned in the [docs](https://mozilla.github.io/uniffi-rs/latest/tutorial/Rust_scaffolding.html#setup-for-crates-using-only-proc-macros), but a little bit late imo for folks who are a bit too eager to resolve errors as they come up.

edit: I stand corrected. It's immediately hinted under the [proc macros](https://mozilla.github.io/uniffi-rs/latest/tutorial/udl_file.html#proc-macros) example.
