### ISSUE TITLE
Build error on iOS simulator in Xcode

### ISSUE THREAD

**Issue by YuchenJin** [mozilla/uniffi-rs#1698]
Hi! I tried following this [user guide](https://mozilla.github.io/uniffi-rs/swift/xcode.html) to integrate with Xcode, and tried building the code on the iOS simulator in Xcode. I targeted `aarch64-apple-ios-sim` when compiling the Rust crate to generate the static library (the `.a` file), and followed the steps in "[Generating the bindings](https://mozilla.github.io/uniffi-rs/swift/xcode.html#generating-the-bindings)", but in the end, I got a bunch of errors such as the following one when building the project in Xcode: 

> Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::at(unsigned long) const

I noticed one comment in the codebase is interesting and might be related: https://github.com/mozilla/uniffi-rs/blob/fde6d8842b24fd14b759afdca91161fac79a3efe/examples/app/ios/xc-universal-binary.sh#L64

Could someone explain what this comment means and guide me through the process of building libstd? Additionally, if anyone has insights or suggestions regarding the errors I encountered on the iOS simulator, your help would be greatly appreciated. Thank you!

**Comment by badboy** [comment]
That comment is outdated, the required target shipped a while ago and building for the iOS simluator on M1/M2 is possible using any recent stable Rust.

The error message looks weird and seems unrelated to any Rust code.
Can you show a full example, maybe as a git example repository that reproduces this? Otherwise it will be hard to help.

**Comment by YuchenJin** [comment]
Hi @badboy, thanks for your help! 

We got rid of one of our Rust code's dependencies, and it works perfectly on iOS simulator in Xcode! I like this uniffi project and appreciate your great work!
