### ISSUE TITLE
Use trace level logging in generated code

### ISSUE THREAD

**Issue by praveenperera** [mozilla/uniffi-rs#1702]
Is it possible to not have one function log every time its called?

I have a very simple function 

```rust
#[uniffi::export]
pub fn pod_restart_count(pod: Pod) -> i32 {
    pod.total_restart_count()
}
```

Its called a lot of times and drowns out all the other logs, would it be possible to opt out of logging on a per function basis?
<img width="1033" alt="Screenshot 2023-08-10 at 6 45 24 PM" src="https://github.com/mozilla/uniffi-rs/assets/1775346/861ec1b6-efd5-47f2-bb72-475543fcd6f7">

**Comment by badboy** [comment]
We unconditionally log at debug level (though maybe this really should be trace level), however depending on what log implementation you use you can raise the minimal log level for a particular module.
In my project we use a submodule for the generated code:

```
mod ffi {
    use super::*;
    uniffi::include_scaffolding!("glean");
}
```

and then filter this in the different log configurations: https://github.com/mozilla/glean/blob/main/glean-core/src/lib.rs#L710-L743

**Comment by praveenperera** [comment]
@badboy that's a good idea, I'll move the noisy functions to a different module and set the log level there.

But I agree I think `trace` might be a better level for these logs.

**Comment by ilikepi63** [comment]
Is this issue still open? Could I submit a PR?

**Comment by mhammond** [comment]
Yep, a PR would be welcome!

**Comment by praveenperera** [comment]
Fixed by: https://github.com/mozilla/uniffi-rs/pull/2275
