### ISSUE TITLE
Using 2 different Uniffi libraries in Swift causes duplicated symbols.

### ISSUE THREAD

**Issue by goncalo-frade-iohk** [mozilla/uniffi-rs#1710]
Hi guys. I know there is a issue similar for this: https://github.com/mozilla/uniffi-rs/issues/1670

But its not the same, Im having an issue when I try to use 2 Uniffi libraries on my iOS project I get duplicated symbols, the problem is that they are not Uniffi symbols, but `Rust`.

Just so you understand after I create the targets I create an XCFramework, and then a Swift Package with the bindings provided, I do the same for each library.

But when I use both and try to run on a device or simulator the symbol problem appears. Now this makes total sense since the static libraries go with the build.

How can I work out this? Does anyone had the same problem?

This are the duplicated symbols:

```
duplicate symbol '___rust_foreign_exception'
duplicate symbol '_rust_begin_unwind'
duplicate symbol '___rdl_alloc_zeroed'
duplicate symbol '___rdl_realloc'
duplicate symbol '___rdl_dealloc'
duplicate symbol '___rdl_alloc'
duplicate symbol '_rust_panic'
duplicate symbol '___rust_drop_panic'
duplicate symbol '___rg_oom'
duplicate symbol '___rdl_oom'
```

And this are the uniffi projects im trying to use in the same app:
https://github.com/input-output-hk/anoncreds-rs
https://github.com/sicpa-dlab/didcomm-rust

**Comment by arg0d** [comment]
Make sure both of your libraries are built using the same Rust version. These errors happen when 2 static libraries are built using different Rust versions, and is not related to Uniffi.
