### ISSUE TITLE
Usage of traits

### ISSUE THREAD

**Issue by akashgurava** [mozilla/uniffi-rs#1711]
I have the below rust code:
```rust
use std::sync::Arc;

uniffi::setup_scaffolding!();

#[uniffi::export]
pub trait Person: Send + Sync + std::fmt::Debug {
    fn name(&self) -> String;
}

#[uniffi::export]
pub fn greet(person: Arc<dyn Person>) {
    println!("Hello!! {}", table.name())
}
```
I want to implement Person to a Swift Class like
```swift
class Man: PersonProtocol {
    func name() -> String {
        ""
    }
}
// THIS IS ERRORING AS Cannot convert value of type 'Man' to expected argument type 'Person'
greet(person: Man())
```

How to fix this error?

**Comment by mhammond** [comment]
We don't support this yet. The closest we have to allowing foreign code to implement a trait and pass it in to Rust is a "callback interface" - see, eg, https://github.com/mozilla/uniffi-rs/blob/e20b9c2b72144ef51a381c6b321ac810a4fbfdbe/fixtures/proc-macro/src/callback_interface.rs#L8 and https://github.com/mozilla/uniffi-rs/blob/e20b9c2b72144ef51a381c6b321ac810a4fbfdbe/fixtures/proc-macro/tests/bindings/test_proc_macro.swift#L40.
