### ISSUE TITLE
provide more example in the multiple constructor documentation when the constructors have custom names

### ISSUE THREAD

**Issue by gogo2464** [mozilla/uniffi-rs#1721]
I am frustruating when I code builders because I would like to avoid to use a mutex for a constructor with a custom name. Then I did:

```
interface Alphabet {
    constructor(sequence<Encoding> encoding);
    [Name=new_empty]
    constructor();
    [Name=full_hexadecimal_alphabet]
    constructor();
    sequence<Encoding> get_encoding();
};
```

But when I call full_hexadecimal_alphabet in python such as:

```python
from cryptatools_core import *

a = Alphabet([])
a = a.full_hexadecimal_alphabet()
hex_alphabet = a.get_encoding()
assert hex_alphabet == [1], f"cipher={hex_alphabet} incorrect alphabet."
print("plain = {0}. OK!".format(hex_alphabet))
```

then I got the error:

```
Traceback (most recent call last):
  File "C:\XXX\...\XXX\cryptatools-rs\cryptatools-core\binding-testing\testing.py", line 136, in <module>
    a = a.full_hexadecimal_alphabet()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Alphabet' object has no attribute 'full_hexadecimal_alphabet'
```

I think there could be a lack of documentation in this chapter: https://mozilla.github.io/uniffi-rs/udl/interfaces.html?highlight=constructor#alternate-named-constructors it does not have any example from rust code and in python call. We currently just have the udl file.

Could you provide more usage example please?

**Comment by mhammond** [comment]
A constructor means the method is available on the class, not an instance - eg, `Alphabet.full_hexadecimal_alphabet()` would work. You are trying to call a constructor on an instance of the object, which doesn't make sense.

For a builder pattern, you don't want constructors, you want regular methods that happen to return `Self` - eg, you might have

```
interface Something {
  constructor();
  Something with_name(String name);
};
```
which Python code might call with `ob = Something().with_name("foo")` which would give you `ob` as being a `Something`.

**Comment by gogo2464** [comment]
great!!! thank you!!!

Do you think there could be a need for example in the uniffi-rs official doc?

**Comment by mhammond** [comment]
I don't think so - nothing here is uniffi-specific.
