### ISSUE TITLE
Implement async trait interfaces

### ISSUE THREAD

**Issue by bendk** [mozilla/uniffi-rs#1729]
We currently support async Rust functions, let's also add support for:
  - Async methods in trait interfaces (probably using the `async_traits` crate).
  - Foreign language defined async methods (depends on #1578)

We could also implement async callback interface methods, but once we implement 1578 I think they're going to be just a worse version of trait interfaces.  Maybe we should just deprecate callback interfaces and push users towards using trait interfaces.

@mhammond points out that we may get core support for async trait methods soon, and when it does we should start using that rather than `async_traits`.   Lets put this whole thing behind an experimental feature flag so that users who use it won't be blindsided by that change.

**Comment by CaioSym** [comment]
Is there a roadmap for this feature to be implemented or pointers on how to do so. Really need this for a project and would be happy to contribute tho not super sure where to start!

**Comment by mhammond** [comment]
fixed by #1981

**Comment by shaiguelman** [comment]
Is there currently a plan for supporting async foreign-implemented traits? It's exactly what we need for our use case

**Comment by dignifiedquire** [comment]
@mhammond is there an issue for async foreign-implemented traits? didn't find anything about it

**Comment by dignifiedquire** [comment]
nvm, it just works

```rust
#[uniffi::export(with_foreign)]
#[async_trait::async_trait]
pub trait SubscribeCallback: Send + Sync + 'static {
    async fn event(&self, event: Arc<LiveEvent>) -> Result<(), CallbackError>;
}
```

```kotlin
class Subscriber : SubscribeCallback {
    suspend override fun `event`(`event`: LiveEvent) {
        // ..
    }
}
```
