### ISSUE TITLE
Unit tests for lower/lift pairs in each of the backends

### ISSUE THREAD

**Issue by jhugman** [mozilla/uniffi-rs#174]
Currently our testing story is sporadic.

This issue should exercise the lower/lift pairs (i.e. round tripping through the `RustBuffer`) of the basic types i.e. primitives, strings, sequences, maps etc; for each of the backend languages, and the rust scaffolding.

Ideally we should be able use the same data set used to test in each of the backends.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-4)
┆Issue Number: UNIFFI-4

**Comment by rfk** [comment]
I think we have a pretty good handle on this these days with the `rondpoint` and `coveralls` tests, closing it out.
