### ISSUE TITLE
create javascript binding support

### ISSUE THREAD

**Issue by gogo2464** [mozilla/uniffi-rs#1741]
thanks for your answer @badboy : https://github.com/mozilla/uniffi-rs/issues/991

I may implement javascript bindings in uniffi-rs.

Could it be merged or will it be in a remote repo like uniffi-go and uniffi-cs please?

**Comment by badboy** [comment]
We prefer external implementations, as we don't have the resources to maintain additional bindings we don't use ourselves

**Comment by badboy** [comment]
Note that depending on your actual target (node? deno? web?) this overlaps with #1424 whereas the Rust parts are compiled to WASM and the generated JS code talks through JSON. Or if Node is your only target one could generate [Node-API](https://nodejs.org/api/n-api.html)-using code.

**Comment by gogo2464** [comment]
sure no problem! 

I target mainly node and a bit of web. let me create an external repository!

**Comment by mhammond** [comment]
Once you get something working, let us know so we can link to it, but I don''t think there's anything left to do for this issue currently.
