### ISSUE TITLE
Is there a way to access a file from Rust code?

### ISSUE THREAD

**Issue by soupslurpr** [mozilla/uniffi-rs#1743]
Hi, I'm trying to use UniFFI to generate Kotlin bindings so I can make an Android app for running a large language model using the candle Rust library. For loading the model file I've had to use include_bytes! to include it in the compiled library but is there a way for the Rust code to access files on the Android filesystem so I could maybe download the model later or ask the user to provide the model? I tried converting the file to a UByte list in Kotlin and passing it as a parameter but it gets out of memory.

**Comment by badboy** [comment]
Sure, the Rust parts are compiled to native code, you're free to use any I/O you need. You will probably need to stay within your app's sandbox though.
If you can open the file on the Kotlin side you already have a path and you can pass that to Rust and open it there.

All in all this is not really a UniFFI issue, so I'll go ahead and close this issue.

**Comment by soupslurpr** [comment]
Could you show me an example string of a path? I already tried the path but it didn't seem to work. I opened a file using the Android Storage Access Framework and passed the path to Rust, but I'm suspecting that I may have to use the folder access operation and not a specific file maybe. I also tried loading a file from the Android assets directory by passing the path and failed, might have used a wrong path since I think I tried something like file://android_asset/file.bin. Thanks.

**Comment by soupslurpr** [comment]
Getting a file descriptor int in the Kotlin code then passing it as a parameter worked. I can get the File by using std::fs::File::from_raw_fd
