### ISSUE TITLE
create tutorial on how to dev an external bindgen language for uniffy-rs

### ISSUE THREAD

**Issue by gogo2464** [mozilla/uniffi-rs#1744]
Hello. I would like to dev an external C bindings for uniffy-rs. I only met https://github.com/mozilla/uniffi-rs/blob/main/docs/contributing.md as documentation.

It could be cool to create step by step tutorial on adding new languages. We might even document how uniffi-rs has even been created in order to let the reader create uniffy like program for another languages.

I am writing bindgens so I could improve this issue with PRs.

**Comment by MeerKatDev** [comment]
The way I would do this is just try and copy the existing bindgens 😄 it might be more complex to write a guide on how to do that. Maybe some suggested macrosteps, but a full-fledged tutorial seems excessive

**Comment by gogo2464** [comment]
I do not think it is excessive to write developper documentation.

Swig has done so: https://www.swig.org/Doc4.1/SWIGDocumentation.html#Extending

**Comment by gogo2464** [comment]
Then assign me to this issue please. :) I do not promise nothing. I will try something in some month.

**Comment by gogo2464** [comment]
I may open a PR. this is not my priority. I may come back in some mounths.
