### ISSUE TITLE
Expose Rust struct that contains a method returning a byte slice `&[u8]`.

### ISSUE THREAD

**Issue by mainrs** [mozilla/uniffi-rs#1756]
What would the UDL interface method signature look like? `[ByRef]` cannot be used on methods and I need an `interface` type since the structs I want to expose contain methods.

**Comment by badboy** [comment]
You cannot return references into foreign languages. That would require lifetime tracking which is impossible across the language boundaries.

**Comment by badboy** [comment]
If you return a bunch of references from your API, then yes, you will need to wrap them to make them usable with UniFFI.
