### ISSUE TITLE
Duplicate definition when testing fixtures/proc-macro using go generator

### ISSUE THREAD

**Issue by dignifiedquire** [mozilla/uniffi-rs#1759]
I am working on [updating the go implementation](https://github.com/NordSecurity/uniffi-bindgen-go/pull/13) and running into the issue that the way the names are defined in `fixtures/proc-macro` I end up with a duplicate definition in the go code. 

The source is this method
- this method https://github.com/mozilla/uniffi-rs/blob/main/fixtures/proc-macro/src/lib.rs#L125 and
- this trait https://github.com/mozilla/uniffi-rs/blob/main/fixtures/proc-macro/src/callback_interface.rs#L8

Due to the golangs naming conventions I end up with 

```go
func TestCallbackInterface(cb TestCallbackInterface) { /* .. */ }
```

and 

```go
type TestCallbackInterface interface {
  /* .. */
}
```

The easiest from my side would be to simply rename one of the two, but I was wondering if there is another way this should be solved?

**Comment by mhammond** [comment]
I don't think it makes sense for UniFFI to try and avoid this, so I'd think renaming one of the other is perfectly reasonable.

**Comment by dignifiedquire** [comment]
thanks, will make a PR
