### ISSUE TITLE
Kotlin backend generates invalid code for Record with no fields

### ISSUE THREAD

**Issue by jplatte** [mozilla/uniffi-rs#1760]
Reproducer:

```rust
#[derive(uniffi::Record)]
pub struct MyEmptyRecord {
}
```

[Official docs](https://kotlinlang.org/docs/data-classes.html) for "data classes" that UniFFI is apparently outputting mentions

> The primary constructor needs to have at least one parameter.

Error message, simplified from real-world occurrence:

```
e: file://path/to/api.kt:11003:65 Expecting an expression
e: file://path/to/api.kt:10992:33 Data class must have at least one primary constructor parameter
e: file://path/to/api.kt:17459:22 Overload resolution ambiguity:
```

**Comment by julioromano** [comment]
Empty rust structs should be translated to [kotlin data objects](https://kotlinlang.org/docs/object-declarations.html#data-objects). Though they require kotlin 1.9.
Best would be to translate empty structs to `object` for kotlin <1.9 and to `data object` for kotlin >= 1.9.

**Comment by jplatte** [comment]
Fixed in https://github.com/mozilla/uniffi-rs/pull/1781.
