### ISSUE TITLE
Error in generated Swift file

### ISSUE THREAD

**Issue by martinmose** [mozilla/uniffi-rs#1762]
Hello,

Firstly, I'd like to mention that I'm new to Rust. I'm embarking on a project that aims to share code between iOS and Android platforms.

I've hit a snag I can't seem to overcome.

After meticulously going through the documentation and experimenting with the provided examples.
I have the following:

```
#[derive(uniffi::Object)]
pub struct Megaphone;

#[uniffi::export]
impl Megaphone {
    pub async fn say_after(self: Arc<Self>) -> String {
        "Hello world".to_string()
    }
}
```

I encountered some compilation errors in the generated .swift file, as depicted here:
![Screenshot 2023-09-22 at 16 20 12](https://github.com/mozilla/uniffi-rs/assets/621570/73e4021c-e42b-4d2f-b364-8b19e3c39fed)

Notably, other functions are working seamlessly. It's only when I introduce this line:

```
#[derive(uniffi::Object)]
pub struct Megaphone;
```

that I encounter these challenges.

Any guidance or insight would be greatly appreciated.

**Comment by mhammond** [comment]
If you are using the release version of UniFFI, it might be that your crate name and namespace name on your UDL aren't identical. This requirement no longer exists in the main branch.

**Comment by martinmose** [comment]
I use:
`uniffi = { git = "https://github.com/mozilla/uniffi-rs/", branch = "main", features = [ "build", "bindgen", "cli" ] }`
And I don't have a UDL file. I use `uniffi::setup_scaffolding!();`

Because I want the async support.

**Comment by mhammond** [comment]
huh, that should be ok then, and seems identical to [one of our fixtures](https://github.com/mozilla/uniffi-rs/blob/main/fixtures/simple-iface/src/lib.rs) - so I'm really not sure what's going on.

**Comment by mhammond** [comment]
So taking futures as an example, in the generated futures.swift we can see:

`try! rustCall { uniffi_uniffi_futures_fn_free_megaphone(pointer, $0) }` - the name reflects a hard-coded "uniffi_" prefix, followed by the crate name for that example ("uniffi_futures") followed by the name.

In the same directory as that .swift there's futuresFFI.h, which has `void uniffi_uniffi_futures_fn_free_megaphone(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status);`

How does that differ in your case? ie, are there references to `fn_free_megaphone` in both cases, but with different prefixes? Or missing in the .h entirely? Or does it look the same? (Note the comments in the top of the .swift which conditionally includes that .h - maybe that's not being hit for you?)

**Comment by martinmose** [comment]
That's an insightful point – I hadn't considered checking that detail. In the beginning of the `.swift` file, I've got:
```
#if canImport(my_ticket_sharedFFI)
import my_ticket_sharedFFI
#endif
```
Upon inspecting the `.xcframework`, I noticed that both `aarch64-apple-ios`and `ios-arm64_x86_64-simulator` contain a header file with the following entries:
```
void uniffi_my_ticket_shared_fn_free_megaphone(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);

void uniffi_my_ticket_shared_fn_method_megaphone_say_after(void*_Nonnull ptr, size_t uniffi_executor, UniFfiFutureCallbackRustBuffer _Nonnull uniffi_callback, void* _Nonnull uniffi_callback_data, RustCallStatus *_Nonnull out_status
);

uint16_t uniffi_my_ticket_shared_checksum_method_megaphone_say_after(void
    
);
```

What would be the next steps or recommendations?"

**Comment by mhammond** [comment]
In my example, the generated `futuresFFI.h` existed in the same directory as the generated .swift file - is that true for you?

> Upon inspecting the .xcframework, I noticed that both aarch64-apple-iosand ios-arm64_x86_64-simulator contain a header file with the following entries:

Hrm, I'm afraid I don't know enough about Swift to know what that means - best I can tell, that futures example doesn't have a .xcframework?

It might be useful to see if you can make it work by using swift the same way our fixtures do, but other than pointing you at the examples/app/ios directory I don't think I'm able to help you diagnose issues with an xcframework.

**Comment by martinmose** [comment]
That's accurate on my end, and the content I mentioned in my previous message is present as well. Thank you for your efforts! 💪
