### ISSUE TITLE
Do external types require adding the associated binaries?

### ISSUE THREAD

**Issue by thunderbiscuit** [mozilla/uniffi-rs#1764]
I've been building a series of [uniffi examples](https://thunderbiscuit.github.io/uniffi-examples/examples/multiple-libraries.html). I recently realized that the example I use for leveraging external types does not work if I need the type reexposed and available to my users unless I build the dylib for that dependency and include it in my packaging. I'm wondering if I misunderstand some of the steps or configuration to make this work, as I initially thought the types defined in my dependency and used with the `[External="libraryname"]` annotation would be available by default. 

A complete example of what I mean is [here](https://github.com/thunderbiscuit/uniffi-examples/tree/master/6-multiple-libraries). The `clock` library defines a type I want usable in my `calendar` library. If you run the [Kotlin tests on the external-types branch](https://github.com/thunderbiscuit/uniffi-examples/blob/external-types/6-multiple-libraries/calendar-kotlin/lib/src/test/kotlin/org/examples/calendar/CalendarTest.kt), you'll find that the first test passes but the second fails with error
```sh
java.lang.UnsatisfiedLinkError: Unable to load library 'clock_ffi':
...
```

To make the test pass, you must build the clock_ffi library and include the dylib in the classpath. I'm not sure if this is really a requirement or simply an issue of misconfiguring the build. The clock package attempts to load a library called clock_ffi, but should the dependency not already be included statically inside the `libcalendarffi.dylib` binary?

Let me know if I misunderstood the docs or if it's explained somewhere I haven't seen. Could that be an issue with my `calendar-ffi/uniffi.toml` file?

**Comment by mhammond** [comment]
Ouch - https://mozilla.github.io/uniffi-rs/udl/ext_types_external.html has a link to https://github.com/mozilla/uniffi-rs/blob/main/fixtures/ext-types/lib/uniffi.toml which is a 404. So the docs are very poor :( Does it work if you remove that file?

**Comment by thunderbiscuit** [comment]
No unfortunately if I remove the uniffi.toml file my error stays the same.

Essentially I need to build/add both dylib binaries to the package at the moment. But is that how it's supposed to work? And sidenote: is that maybe related to the Megazord workflow you have where you combine some of the binaries into one? (I forget where I initially read about this Megazord and now I can't find it back... let me know if you know the file/doc I'm talking about).

**Comment by mhammond** [comment]
A "megazord" is really just exactly what you are trying to do here - a way of bundling multiple FFI-backed crates into a single .so.

In that scenario, we need every component to know that its .so is this megazord. However, clock's [uniffi.toml](https://github.com/thunderbiscuit/uniffi-examples/blob/external-types/6-multiple-libraries/clock-ffi/uniffi.toml) tells it the .so is `clock_ffi` - but both calendar and clock need to agree.

IIUC, if you use "library mode" to build things, you don't need to specify these values in uniffi.toml - the .so name you specify will be used for all crates found. This is how the ext-types example gets away without a uniffi.toml.
