### ISSUE TITLE
How to use external crates

### ISSUE THREAD

**Issue by thewh1teagle** [mozilla/uniffi-rs#1771]
I have library I wrote which have code similar to this:

`lib.rs`

```rust
use hidapi::{HidDevice, HidApi};

pub struct Controller {
    pub device: HidDevice
}
impl Controller {
    pub fn new(device: HidDevice) -> Self { device }
}
pub fn get_device() -> Option<hidapi::HidDevice> { ... }
```

How can I describe it in `UDL` and call it from `python`? `hidapi::HidDevice` is external crate.

**Comment by mhammond** [comment]
You probably need to use a [custom type](https://mozilla.github.io/uniffi-rs/udl/custom_types.html) - if the type from the external crate can't be represented as a builtin type you will probably need to use a wrapper - a locally defined type which contains that type and exposes the functionality you need in a uniff-compatible way - eg, a "new type" wrapper like https://mozilla.github.io/uniffi-rs/proc_macro/index.html#the-unifficustom_type-and-unifficustom_newtype-macros
