### ISSUE TITLE
url::Url example says the trait `FfiConverterArc<UniFfiTag>` is not implemented for `url::Url`     |

### ISSUE THREAD

**Issue by KronicDeth** [mozilla/uniffi-rs#1772]
I'm trying to use the `url::Url` example in the docs like so

Trying to add `uniffi` support to https://github.com/liveview-native/phoenix-channels-client in `src/socket.rs`
```
#[uniffi::export]
impl Socket {
    ...
        /// The `url` passed to [Socket::spawn]
    pub fn url(&self) -> Arc<Url> {
        self.url.clone()
    }
    ...
}    
```

In `src/ffi.rs`
```
uniffi::custom_type!(Url, String);

impl UniffiCustomTypeConverter for Url {
    type Builtin = String;

    fn into_custom(string: Self::Builtin) -> uniffi::Result<Self> {
        Url::parse(&string).map_err(From::from)
    }

    fn from_custom(url: Self) -> Self::Builtin {
        url.to_string()
    }
}
```

but in `src/socket.rs` I get this error

```
error[E0277]: the trait bound `url::Url: FfiConverterArc<UniFfiTag>` is not satisfied
   --> src/socket.rs:242:1
    |
242 | #[uniffi::export]
    | ^^^^^^^^^^^^^^^^^ the trait `FfiConverterArc<UniFfiTag>` is not implemented for `url::Url`
    |
    = help: the following other types implement trait `FfiConverterArc<UT>`:
              channel::Channel
              http::Response
              JSON
              Socket
    = note: required for `Arc<url::Url>` to implement `FfiConverter<UniFfiTag>`
    = note: this error originates in the attribute macro `uniffi::export` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Do I need to do something else to be able to return the `Arc<Url>` from `Socket::url`?

**Comment by mhammond** [comment]
You don't want `Arc<Url>`, just plain `Url` - `Arc<>` is only used when passing objects/interfaces, but in this example it's a plain old string.

**Comment by linabutler** [comment]
Hi @KronicDeth, thanks for the issue! It's the `Arc` that's tripping it up: `Socket::url` returns an `Arc<Url>`, but `UniffiCustomTypeConverter` is implemented for `Url`, not `Arc<Url>`.

If you change `Socket::url` to return a `Url`:

```rs
/// The `url` passed to [Socket::spawn]
pub fn url(&self) -> Url {
    (*self.url).clone()
}
```

I think it should work!

Gory details: I don't think it's possible to safely implement `UniffiCustomTypeConverter` for an `Arc<T>`. An `Arc` is a pointer to a specific location in memory, so the type converter would need to roundtrip that _pointer_ through foreign code—not just the value it points to. UniFFI does this in its generated bindings for `interface` / object types, using the unsafe `Arc::{into_raw, from_raw}` on the Rust side, and a wrapper class on the foreign side, but we can't do that in a safe and generic way for custom types.

**Comment by linabutler** [comment]
Oops, sorry, I saw @mhammond already replied as I was typing my comment! 😅

**Comment by KronicDeth** [comment]
@linabutler the pre-`uniffi` code returned `Arc<Url>` to try to be memory efficient, but you and @mhammond make a good point that it has to make a `String` over the FFI even if we use `java.net.Url` in Kotlin or `URL` in Swift, so it really doesn't matter being efficient with `Arc<Url>`.
