### ISSUE TITLE
regression: conflicting implememtations of HashMap on v0.25.0

### ISSUE THREAD

**Issue by flisky** [mozilla/uniffi-rs#1796]
The compile error happens after uniffi v0.25 upgrade.

* rust type: `type Headers = std::collections::HashMap<CompactString, CompactString>`

* defined a custom type in udl
```
[Custom]
typedef record<string, string> Headers;
```

* impl UniffiCustomTypeConvert:
```rust
impl UniffiCustomTypeConverter for Headers {
    type Builtin = HashMap<String, String>;

    fn into_custom(val: Self::Builtin) -> uniffi::Result<Self> {
        Ok(val.iter().map(|(k, v)| (k.into(), v.into())).collect())
    }

    fn from_custom(obj: Self) -> Self::Builtin {
        obj.iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }
}
```

the compile error log:
```
error[E0119]: conflicting implementations of trait `LowerReturn<UniFfiTag>` for type `HashMap<compact_str::CompactString, compact_str::CompactString>`
   -->...uniffi-be5223de7a71838f/out/engine_uniffi.uniffi.rs:824:1
    |
824 | ::uniffi::custom_type!(r#Headers, std::collections::HashMap<String, String>);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: conflicting implementation in crate `uniffi_core`:
            - impl<K, V, UT> LowerReturn<UT> for HashMap<K, V>
              where HashMap<K, V>: Lower<UT>;
    = note: this error originates in the macro `$crate::derive_ffi_traits` which comes from the expansion of the macro `::uniffi::custom_type` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I have to use `hashbrown::HashMap` instead of `std::collections::HashMap` to make it pass.

**Comment by mhammond** [comment]
Why does this need to be a custom type? Can't you use `record<string, string>` in the rest of the UDL?

**Comment by flisky** [comment]
Ahh, it's a good question. Because the type is defined in the core crate, and uniffi (among wasm/napi/...) is a wrapper for the core. It could use `HashMap<String, String>`, and feel free to close the issue because it's a good to have, not must to have.

**Comment by mhammond** [comment]
Thanks for getting back to us. This really is just asking for a "plain old" typedef rather than a custom type. I suspect we'd be up for a good PR which did that, but suspect we will not do it and that was never the intent of this capability, so I'm closing it.
