### ISSUE TITLE
Improve docs around building / scaffolding when using proc macros

### ISSUE THREAD

**Issue by ianthetechie** [mozilla/uniffi-rs#1816]
When investigating + patching my own project as a result of #1804, I came across the following areas for improvement. 

1. As far as I can tell, it is not strictly necessary to have a `build.rs` file with a call to `generate_scaffolding` anymore (see [Rust Scaffolding](https://github.com/mozilla/uniffi-rs/blob/eb97592f8c48a7f5cf02a94662b8b7861a6544f3/docs/manual/src/tutorial/Rust_scaffolding.md)) if you are using proc macros exclusively rather than UDL.
2. The [proc macros build workflow](https://github.com/mozilla/uniffi-rs/blob/eb97592f8c48a7f5cf02a94662b8b7861a6544f3/docs/manual/src/proc_macro/index.md?plain=1#L24C7-L24C7) doesn't make it clear how to generate mixed UDL and proc macro bindings. I never did figure this out myself, but I assume it's possible.
3. Closely related to 2, I never figured out how to generate the bindings without switching to library mode. I glossed over that section initially because it didn't register as important, but it turns out to be crucial at least as far as I can tell once you drop UDL completely.

I'd be happy to open a PR if the team could confirm the details, but for now they are all a bit fuzzy to me.

**Comment by mhammond** [comment]
now I think more about it re (2), some magic is sometimes needed for them to interop - eg, see https://github.com/mozilla/uniffi-rs/blob/main/uniffi_macros/src/lib.rs#L172
