### ISSUE TITLE
Using ByteBuffer for Strings

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/uniffi-rs#182]
One issue we had to deal with when implementing strings in #25 is what to use to represent them. We chose the way it is done in Application Services, which is to use `ffi_support::FfiStr`. This abstraction is great because it saves us some memory allocations and abstracts the null-terminated string that is passed in.

The drawback is it creates asymmetry with strings, we end up lifting a `&str` but lowering a `String`. This is alright and we can live with it, BUT, when we have strings as a part of a `Record`, since a record is serialized into a `ByteBuffer`, the string has to as well.

Now, this creates an extra layer of asymmetry with strings, to sum it up:

- When a string is taken as an argument, we map an `ffi_support::FfiStr` to a `&str`
- When a string is returned, we map a `String` to a `*mut c_char` and provide a free function the caller can use, so that they don't need to do any copying
- When a string is a part of a record/sequence we serialize the string into the ByteBuffer that the record is serialized into

This creates a lot of confusion but saves us performance in the case that strings are being passed in or returned directly.

If we are to use ByteBuffers for Strings everywhere, we'd have exactly one way to deal with strings, BUT, it would mean multiple copying (As we already do with Records and Sequences anyways)

Thoughts?

Hopefully whatever we can come up with can help solve #181 in a better way

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1583)

**Comment by tarikeshaq** [comment]
Also wanted to note that if we do deem the performance/memory loss OK, then this would also get rid of the `RawPointer` hack I put in place for the `free` functions

**Comment by rfk** [comment]
I support this in the interests of simplicity, and I think it will be relatively low-cost to revisit this decision at a later time when we better understand how to manage the tradeoffs around owned-vs-borrowed data.

**Comment by rfk** [comment]
> If we are to use ByteBuffers for Strings everywhere,

Also, it's not clear if we have to actually use `ByteBuffer` for this, or if it would suffice to always use `String` as the type on the rust side, and have `impl TryFromFFI for String` create and return a new owned `String`. (Might save a copy, but not remove the `RawPointer` hack).
