### ISSUE TITLE
Exporting object with named lifetime - Implicit elided lifetime not allowed here

### ISSUE THREAD

**Issue by jmshrv** [mozilla/uniffi-rs#1822]
I'm trying to export an object for FFI, and that object depends on a value which needs a specific lifetime. Here is some example code:

```rust
#[derive(uniffi::Object)]
pub struct Environment<'a> {
    unicorn: Unicorn<'a, ()>,
}

impl<'a> Environment<'a> {
    /// Creates a new environment for the given architecture/mode. You probably want [Arch::ARM] and
    /// [Mode::LITTLE_ENDIAN].
    pub fn new(arch: Arch, mode: Mode) -> Result<Environment<'a>, uc_error> {
        let unicorn = Unicorn::new(arch, mode)?;

        Ok(Environment { unicorn })
    }
}
```

(Unicorn is from [unicorn-engine](https://crates.io/crates/unicorn-engine))

With this, I get the following error:

```
error[E0726]: implicit elided lifetime not allowed here
  --> src/environment.rs:10:12
   |
10 | pub struct Environment<'a> {
   |            ^^^^^^^^^^^ expected lifetime parameter
   |
help: indicate the anonymous lifetime
   |
10 | pub struct Environment<'_><'a> {
   |      
```

The code also has issues with concurrency as `Unicorn` uses `Rc`, but I'm figuring this out first. Does uniffi support named lifetimes?

**Comment by mhammond** [comment]
UniFFI does not support lifetimes at all because there's no way they can be enforced by arbitrary foreign bindings.

**Comment by jmshrv** [comment]
Ah that makes sense, I'll find a way to work around needing lifetimes :)
