### ISSUE TITLE
Kotlin exported error enum code showing errors

### ISSUE THREAD

**Issue by soupslurpr** [mozilla/uniffi-rs#1830]
Its my first time trying to return a Result with uniFFI, I'm using proc macros only. The generated Kotlin bindings have errors in the generated Kotlin code for the RenderException enum I have for the error.

```
Type mismatch.
Required:
KClass<out Throwable>
Found:
KClass<RenderException>
```

```
Type mismatch.
Required:
CallStatusErrorHandler<TypeVariable(E)>
Found:
RenderException.Companion
```

This is in https://github.com/soupslurpr/BeauTyXT/blob/954fc0ac2147904505c93136321d6dac80bfc725/app/src/main/kotlin/dev/soupslurpr/beautyxt/beautyxt_rs.kt#L1305C1-L1312C2

Please help, thanks.

**Comment by mhammond** [comment]
Can you please share your .rs?

**Comment by soupslurpr** [comment]
Sure, the Rust library is located here: https://github.com/soupslurpr/BeauTyXT/tree/954fc0ac2147904505c93136321d6dac80bfc725/beautyxt_rs

**Comment by mhammond** [comment]
Where exactly is the Rust function which is failing?

**Comment by soupslurpr** [comment]
The Rust function that returns a RenderException here: https://github.com/soupslurpr/BeauTyXT/blob/954fc0ac2147904505c93136321d6dac80bfc725/beautyxt_rs/src/typst.rs#L233

**Comment by mhammond** [comment]
huh - there's nothing obvious I can see there. The enum variant holds a record, but I don't see why that doesn't work (and the error message gives me no reason to believe that's the problem here) . https://github.com/mozilla/uniffi-rs/blob/main/fixtures/proc-macro/src/lib.rs#L191 is quite close - I wonder if it's possible for you to try and provoke the same error in that fixture?

**Comment by soupslurpr** [comment]
Sure, I'll try

**Comment by soupslurpr** [comment]
How do I run it? I've been trying but confused how to do it properly

**Comment by mhammond** [comment]
from the root of the uniffi directory you want `cargo run -p uniffi-fixture-proc-macro`

**Comment by mhammond** [comment]
oops, `cargo test -p uniffi-fixture-proc-macro`

**Comment by soupslurpr** [comment]
I get 

```
---- uniffi_foreign_language_testcase_test_proc_macro_kts stdout ----
Creating testing out_dir: C:\Users\user\projects\uniffi-rs\target\tmp\uniffi-fixture-proc-macro-8095b2f89d4f56a8    
Error: Failed to spawn `kotlinc` to compile the bindings

Caused by:
    program not found
```

but I have kotlinc installed and kotlinc works on the terminal

**Comment by soupslurpr** [comment]
Can I access the generated bindings manually?

**Comment by mhammond** [comment]
I can't explain why uniffi will not be able to spawn `kotlinc` if the same terminal from where you execute `cargo` can. You can find all the generated bindings under `target` - eg, `find target -name "*.kts"` or similar should show them.

**Comment by soupslurpr** [comment]
Found it, has no errors

**Comment by mhammond** [comment]
Yeah, we know it has no errors because it's run by our CI. The question will be how to change it in the smallest possible way so that it *does* have your error.

**Comment by soupslurpr** [comment]
Oh nooo it was my fault, I put uniffi::Enum instead of uniffi::Error on the RenderException enum 😅

**Comment by soupslurpr** [comment]
Sorry for the waste of your time, it works fine now
