### ISSUE TITLE
question: is there a way to extract or generate python interface file (*.pyi)?

### ISSUE THREAD

**Issue by dev-m1-macbook** [mozilla/uniffi-rs#1835]
Hello!

I've used this project for bridging rust --> swift, and really enjoyed its typesafe swift-lang binding generation.

Now I have a python project that wants to use rust, and I'm wondering if there's a way to generate `*.pyi` file for this. (I did generate a *.so file)

there seem to be some way in https://github.com/mozilla/uniffi-rs/tree/main/uniffi_bindgen/src/bindings)/python , but I can't find how to invoke python interface file generation.

Could you point to some hint / sample snippet or project?

Thank you in advance!

**Comment by mhammond** [comment]
Nope, we do not generate .pyi file. We do try and generate the appropriate type hints directly in the .py file though.

**Comment by dev-m1-macbook** [comment]
ok I just tried again using some other tutorial, 
and got a `.py` file with all the func types as you said!

(I guess I was looking for the wrong combination (`.so` + `.pyi`)😅)

thanks for the quick reply!
closing
