### ISSUE TITLE
[Discuss] UniFFI with Serde

### ISSUE THREAD

**Issue by itrumper** [mozilla/uniffi-rs#1856]
First, thank you for creating this crate. It is awesome to see Rust libraries be able to be more closely integrated with foreign languages with less overhead. However, I am in a situation where I had developed a Rust library and now want to expose it to other languages (C#, Python). I am finding the experience of UniFFIng the library to be a challenge architecturally and I was hoping to get feedback on my methods as well as present an idea to determine its validity.

I am finding that most of my Rust structs are not supported by the proc-macros, because constructors do not return objects wrapped in an `Arc`. I have not wanted to write UDL for the reasons articulated in the getting started guide, in short, duplicating effort. So, as I understand it, I either need to write the UDL (which may not support all the features I want) or I need to write new Rust structs that are supported by the proc-macros and create a translation layer. Both sound painful and involve lots of code duplication.

In thinking about this problem, I have wondered if it is possible to use `serde` as the first layer of translation, and then implement the UniFFI `export` (or relevant trait) on the internal representation from `serde`. This way, any Rust type that implements `Serialize` and `Deserialize` would be supported across the FFI. There is still the layer for function calls that would need to be annotated, but the arguments would have the same support.

Is this idea even feasible? I don't know the internals of either crate, but from a user perspective, this would make the process of UniFFIng a crate much more ergonomic.

**Comment by mhammond** [comment]
Hi, nice to see you.

You don't actually need to choose between UDL and proc-macros, and each of them has support for things the other doesn't - including the ability to auto-wrap the constructor in the `Arc`, so if you need that, just use UDL for that object. There's a bug on file to support that for proc-macros too, but that might be a while.

You can use serde via a string (we even have [custom types](https://mozilla.github.io/uniffi-rs/udl/custom_types.html) which can make this quite a natural json experience), but we can't generate foreign bindings for serde supporting objects, so you always need to use our procmacros and/or UDL to describe the API.

Can you describe your use-case a bit more? What do you existing Rust types look like?

**Comment by itrumper** [comment]
Thank you for the information. I had understood from the documentation that UDL and the proc-macros were compatible, but I wanted to avoid writing as much UDL as possible given the duplication, but it seems like most of my types would benefit from it most.

For example, I commonly use structs as variants within enums:
```Rust
struct CaseA {};
struct CaseB {};

enum Cases {
    A(CaseA),
    B(CaseB),
}
```

This does not appear to be a supported pattern by UDL or the proc-macros. Is my understanding correct?
Similarly, many of the methods that I would ideally like to expose take mutable references of the structs, which I can understand why it is not possible to do so using UniFFI. This leads me to think that I will need to implement a translation layer between my existing Rust data and the foreign language, and therefore have duplicated data.

Using serde via a string and custom types is an intriguing idea, I will look into this more. Thank you!

**Comment by mhammond** [comment]
Enums can hold records (eg, https://github.com/mozilla/uniffi-rs/blob/main/fixtures/coverall/src/coverall.udl#L64C1-L68C1) but only those "known to" UniFFI. A struct with mutable refs will certainly need something to help make it UniFFI compatible, and yeah, some duplication when exposing a "natural rust" API over an FFI is inevitable.

**Comment by itrumper** [comment]
Ah! That's great to know! I apologize, I was going off of the documentation for [enum](https://mozilla.github.io/uniffi-rs/udl/enumerations.html) which says that only named enums with named fields are supported, and similarly in the proc-macro section for the [`Enum`](https://mozilla.github.io/uniffi-rs/proc_macro/index.html#the-uniffienum-derive) derive. This makes re-using my existing data structures much more viable, thank you for the clarification.

I will try using this pattern, and once I have an understanding of it, I would like to make a PR for the getting started guide to showcase how it can be done.

**Comment by itrumper** [comment]
It seems that the proc-macro method does not support enums with structs as variants:
<img width="654" alt="Screenshot 2023-11-20 at 7 39 07 AM" src="https://github.com/mozilla/uniffi-rs/assets/130265521/2ce96ad1-c985-415c-ae13-89ea0270763f">

**Comment by itrumper** [comment]
I have also not been able to get [external types](https://mozilla.github.io/uniffi-rs/udl/ext_types.html#types-from-procmacros-in-this-crate) to work with proc-macros. The following UDL generates the error `Attribute identity Identifier not supported: "Rust"` when `uniffi::generate_scaffolding()` is called in my build.rs file.

```UDL
namespace aurora_tools {};

[Rust="record"]
typedef extern Rectangle;

[Rust="record"]
typedef extern Ellipse;

[Rust="record"]
typedef extern Annulus;

[Enum]
interface Shape {
    Rectangle(Rectangle r);
    Ellipse(Ellipse e);
    Annulus(Annulus a);
};
```

In my Rust code I have annotated the `Rectangle`, `Ellipse`, and `Annulus` structs with `#[derive(uniffi::Record)]`, but it seems like the issue is with the building, and so the annotations shouldn't matter.

**Comment by mhammond** [comment]
> It seems that the proc-macro method does not support enums with structs as variants:

It should, but as noted, they do need to be named.

> [Rust="record"]

Sadly our doc versioning story isn't great - that annotation only works on the main branch.

> In my Rust code I have annotated the Rectangle, Ellipse, and Annulus structs with #[derive(uniffi::Record)], but it seems like the issue is with the building, and so the annotations shouldn't matter.

You are going to have trouble trying to derive record *and* have it as a custom type. Examples of procmacros defining custom types can be found [here](https://github.com/mozilla/uniffi-rs/blob/89da6dbd3183eec6fe9e114c9a6475f5ceafc85c/fixtures/ext-types/proc-macro-lib/src/lib.rs#L82-L85)

**Comment by itrumper** [comment]
> It should, but as noted, they do need to be named.

I think this was my original understanding, which implies that the scenario I currently have, and is considered idiomatic Rust, does not work directly with UniFFI. The example I outlined above does not work as written. Instead, it would have to be:

```Rust
struct CaseA {};
struct CaseB {};

enum Cases {
    A {a: CaseA},
    B {b: CaseB},
}
```

which would require re-writing or duplicating all of my Rust library to be UniFFI compatible. Do you see a different way to handle this situation that I am missing?

>You are going to have trouble trying to derive record and have it as a custom type. Examples of procmacros defining custom types can be found [here](https://github.com/mozilla/uniffi-rs/blob/89da6dbd3183eec6fe9e114c9a6475f5ceafc85c/fixtures/ext-types/proc-macro-lib/src/lib.rs#L82-L85)

Thank you for the link, I will look into this if I can solve the first issue of how best to re-use my existing Rust data.

**Comment by mhammond** [comment]
> Do you see a different way to handle this situation that I am missing?

No, I'm afraid I can't see anything that isn't going to require either changes to your code, some degree of duplication, or changes to UniFFI itself.

**Comment by itrumper** [comment]
Thank you for the clarification. I will likely create another layer of Rust data structures that conform to the UniFFI standards and then annotate the with the proc-macros provided. I'm going to close the issue as I think we have covered all aspects of my question here.
