### ISSUE TITLE
UDL docstrings missing from generated Kotlin

### ISSUE THREAD

**Issue by sebastient** [mozilla/uniffi-rs#1892]
I added docstrings to the UDL following the instructions in the user manual but they do not appear in the generated Kotlin code.  It isn't clear if additional setup is required.  I am using the latest 0.25.3 version.

https://mozilla.github.io/uniffi-rs/udl/docstrings.html

**Comment by mhammond** [comment]
I'm very sorry, but the docs reflect the current git main branch and not released versions - I'm thinking about how we might fix that.
