### ISSUE TITLE
Ways to skip methods when exporting `Object` impl?

### ISSUE THREAD

**Issue by saks** [mozilla/uniffi-rs#1910]
I've been preparing a project for migration to the latest ~~uniffy~~`uniffi` version and decided to check if we can move away from `udl` file definitions. What I found was that some of the methods defined in `impl` blocks for structs exported as `Object` where designed to be used by rust code only. In other words some methods were not designed be exported using `uniffi`. I was looking for ways to "skip" or "ignore" some methods but found that `#[uniffi::export]` would go through all of the methods regardless of their visibility.

I could certainly look into sending a PR that would skip `pub(crate)` methods as one way to achieve what we need but I wanted to see what are the general design considerations regarding this issue. Were there any plans or thoughts on this topics discussed previously?

Thank you!

**Comment by badboy** [comment]
*uniffi.

You can split up your `impl` blocks. Have one annotated with export and another one for internal stuff.

**Comment by saks** [comment]
Thank you @badboy, should have thought about it myself :+1:
