### ISSUE TITLE
Public Community Slack?

### ISSUE THREAD

**Issue by Sajjon** [mozilla/uniffi-rs#1913]
It would cool with a public Slack workspace for the community, for discussion of both development of UniFFI and where community can ask each other for help. Ever given that a thought? 

[Pointfree](https://www.pointfree.co/) has been using it successfully for over 6 months, resulting in less Github issues, more engagement and more community contributions.

WDYT?

Merry Christmas btw!

**Comment by mhammond** [comment]
Merry Christmas!

We are on Matrix - https://matrix.to/#/#uniffi:mozilla.org - so there seems a good chance Slack would split the community rather than help it?

**Comment by Sajjon** [comment]
Ah how silly of me! I missed that Matrix chat was mentioned in README, I guess my eyes were searching for "Slack". 

Ive joined Matrix!
