### ISSUE TITLE
Extend async support to constructors

### ISSUE THREAD

**Issue by yukibtc** [mozilla/uniffi-rs#1919]
Hi, trying to convert my bindings to async I noticed that async constructors and traits aren't supported. 
Is possible to add support to async constructors and traits or is a "limitation" of foreign languages?
Thanks

**Comment by skeet70** [comment]
Exporting async trait implementations does work right now, though exporting the actual async trait for foreign implementation doesn't (#1729) and is blocked on stable async traits. It seems like the async trait stabilization that just happened in Rust 1.75 doesn't have functionality that would be needed to make uniffi exportable async traits work, so it's probably going to have to be an [async_trait](https://docs.rs/async-trait/latest/async_trait/) based implementation if it's done before the Rust implementation is improved.

**Comment by mhammond** [comment]
async traits are on main, so this is now just ctors
