### ISSUE TITLE
Python test of examples/traits failed 

### ISSUE THREAD

**Issue by DogLi** [mozilla/uniffi-rs#1921]
run `cargo test` in `example/traits`

```
  File "uniffi-rs/examples/traits/tests/bindings/test_traits.py", line 15, in <module>
    assert(press(PyButton()).name() == "PyButton")
           ^^^^^^^^^^^^^^^^^
  File "trader/uniffi-rs/target/tmp/uniffi-example-traits-6dcc8aab0f582c35/traits.py", line 929, in press
    _UniffiConverterTypeButton.lower(button)))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uniffi-rs/target/tmp/uniffi-example-traits-6dcc8aab0f582c35/traits.py", line 900, in lower
    return value._pointer
           ^^^^^^^^^^^^^^
AttributeError: 'PyButton' object has no attribute '_pointer'
test uniffi_foreign_language_testcase_test_traits_py ... FAILED
```

The version of python is:
```
Python 3.11.4 (main, Dec 19 2023, 10:56:13) [Clang 16.0.6 ] on darwin
```

`PyButton` was expected to be the extension of `Button` class in Python and be used in the Rust function `press` as the `Arc<dyn Button>` , but failed.

**Comment by mhammond** [comment]
This works for us, including in our CI. I think you are on a later python version though, so if you are able it would be interesting to know if the problem is related to that.

**Comment by badboy** [comment]
I cannot reproduce this on my mac on either Python 3.11 nor 3.12
Did you try with a clean checkout?
If this continues to fail can you provide the full content of uniffi-rs/target/tmp/uniffi-example-traits-6dcc8aab0f582c35/traits.py ?

**Comment by DogLi** [comment]
it works after I update to the latest code.

**Comment by RCasatta** [comment]
I finished here because I have the same error in some test code, updating uniffi on main (f3f7cccfc1dc5adb65d85473830a229b87244dd6) doesn't seem to solve in my case but I am using proc macros to define the trait. Something like:

```rust
#[uniffi::export]
pub trait MyTrait: Send + Sync {
    fn my_trait(&self) -> String;
}

#[uniffi::export]
pub fn ciao(my_trait: Arc<dyn MyTrait>) -> String {
    my_trait.my_trait()
}

```

```python
import ks_bindings as ks

class TestMyTraitPython(ks.MyTrait):
  def my_trait(self):
    return "banana"    

if __name__ == '__main__':
    a = TestMyTraitPython()
    print(ks.ciao(a))
```

**Comment by badboy** [comment]
heh, we figured it out: the code is missing the `with_foreign` option there.

```patch
--- src/lib.rs
+++ src/lib.rs
@@ -1,6 +1,6 @@
 uniffi::setup_scaffolding!();

-#[uniffi::export]
+#[uniffi::export(with_foreign)]
 pub trait MyTrait: Send + Sync {
     fn my_trait(&self) -> String;
 }
```
