### ISSUE TITLE
Python Docstring can produce invalid code

### ISSUE THREAD

**Issue by Hinton** [mozilla/uniffi-rs#1927]
Docstrings in the python generator can produce invalid code. One scenario I've found is when the comment ends with `"`. However presumably starting with a quote would also produce invalid code.

```rust
/// A comment, example "Test"
```

```python
"""A comment, example "Test""""
```

Python uses triple double quotes around docstrings, and since the rust docstring ends with a double quote the generated python code has four quotes which results in a syntax error.

I believe there are a few ways to resolve this, but I would be curious if there are any preference for which approach.

1. Treat docstirngs that starts/ends with an "invalid" character as multi-line.
```python
"""
A comment, example "Test"
"""
```

2. Insert new a character after the docstring, like ` ` or `.`, `"""A comment, example "Test" """`

**Comment by mhammond** [comment]
Please wait and see if there are other comments with different opinions, but I'd be inclined to suggest we just unconditionally make all docstrings multi-line, which offers consistency and should side-step the problem entirely without needing to declare what's "special"

**Comment by Hinton** [comment]
It might be worthwhile to filter out `"""` if it occurs in the docstrings. The comment would be less helpful but at least it will compile.

Technically `'''` is also valid to use for enclosure and we could attempt to be clever and switch to use `'''` in that scenario. It won't help if both `"""` and `'''` exists in the comment though.

**Comment by mhammond** [comment]
Can we quote all quotes (heh) in the string - ie:

```
>>> repr(""" foo \"\"\" """)
'\' foo """ \''
>>> repr(""" foo \"\" """)
'\' foo "" \''
>>> repr(""" foo \" """)
'\' foo " \''
```
it looks like that will do the right thing for all the cases we care about?

**Comment by Hinton** [comment]
Looks like it. Not the prettiest though. What about always using multiline, and escaping if it's 3 or more quotes? That feels like it has a very slim probability of actually happening.

**Comment by mhammond** [comment]
I don't think the prettiness of the generated code is a concern TBH - the generated python is already quite messy, so I'm more concerned about the semantics being correct and the implementation being sane. What you describe can probably do be though, so SGTM.

**Comment by Hinton** [comment]
Comments should show up in the code editor which regular code doesn't. So I think it's worthwile to optimize slightly to ensure the comments are as readable as possible.

**Comment by mhammond** [comment]
How comments show up in a code editor via intellisense aren't going to be impacted by extra escapes in the raw string - the object's `__doc__` is identical either way. I also expect all editors will perform extra normalization, such as massaging the leading spaces at the start of each line.
