### ISSUE TITLE
Passing via ByteBuffer leaks memory

### ISSUE THREAD

**Issue by rfk** [mozilla/uniffi-rs#194]
As noted in @tarikeshaq's review of https://github.com/mozilla/uniffi-rs/pull/192.

When passing rich structures such as `Record` or `Sequence` *in* to Rust from the foreign language bindings, AFAICT the procedure goes like this:

* Foreign language allocates a `RustBuffer` into which to serialize the structure.
* Foreign language copies data into the `RustBuffer`.
* Foreign language passes the `RustBuffer` to Rust as an argument over the FFI.
* Rust copies data out of the `RustBuffer` into live Rust objects
* Rust discards the `RustBuffer` without freeing the underlying memory, because [`ffi_support::ByteBuffer` does not impl `Drop`](https://docs.rs/ffi-support/0.4.0/ffi_support/struct.ByteBuffer.html#caveats).

That seems suboptimal.

We need to dig into the precise details of `ByteBuffer` on the rust side and see what we need to do in order to free the underlying bytes.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1593)

**Comment by rfk** [comment]
Poking in the code for `ByteBuffer` on the rust side, I'm actually not sure if this is true.

The `destroy` method for `ByteBuffer`, which is what we'd call if we wanted to manually drop the buffer, is implemented by [calling `self.into_vec()` and dropping the result](https://github.com/mozilla/application-services/blob/46e92e24abd29642c26c60020a9f04566680e3eb/components/support/ffi/src/lib.rs#L465).

When we lift values out of the `RustBuffer`, we do so by [explicitly calling `buf.into_vec()`](https://github.com/mozilla/uniffi-rs/blob/8daccdb683768a93ccaa807725f0031e648df10b/uniffi/src/support/mod.rs#L82) and then allowing the resulting `Vec` to go out of scope, which should cause it to be dropped.

So...I think maybe we're OK here, and the docs for `ByteBuffer` should be updated to reflect that converting to a `Vec` will handle the memory cleanup via drop.

@thomcc could you please lend your wisdom here?

**Comment by thomcc** [comment]
Yeah, this is probably a slight footgun, but it's to avoid the much larger footgun of accidentally dropping the ByteBuffer if it stores data either not owned by Rust, or owned by rust that isn't intended to be dropped then. This is a pretty common footgun in FFI contexts (see the last paragraphs of https://without.boats/blog/two-memory-bugs-from-ringbahn/), even outside of the stated concerns in the Caveats documentation that discusses this some: https://docs.rs/ffi-support/0.4.0/ffi_support/struct.ByteBuffer.html#caveats 

Anyway, the preferred way of dropping a ByteBuffer is to call [ByteBuffer::destroy](https://docs.rs/ffi-support/0.4.0/ffi_support/struct.ByteBuffer.html#method.destroy), although this is equivalent (and implemented by) converting to a vec, which it sounds like we're doing.

It is probably worth updating the docs to mention this, though.

**Comment by rfk** [comment]
With the above ffi-support PR landed, concrete action for us here is to update to use the new version and its ``ByteBuffer::destroy_into_vec` method (which is the same as the one we're currently using, but with a more descriptive name)

**Comment by rfk** [comment]
Closed by https://github.com/mozilla/uniffi-rs/pull/210
