### ISSUE TITLE
Proc Macros: the trait bound `str: LiftRef<UniFfiTag>` is not satisfied

### ISSUE THREAD

**Issue by LBeernaertProton** [mozilla/uniffi-rs#1949]
I've have been experimenting with uniffi-rs proc macos and I seem unable to make the following snippet work:

```
#[uniffi::export]
pub fn test(name:&str) {

}
```

The code above fails with the following error:
```
the trait bound `str: LiftRef<UniFfiTag>` is not satisfied
```

According to [this page](https://mozilla.github.io/uniffi-rs/udl/builtin_types.html) in the guide, it should be possible to have functions with `&str` and `&[T]`.

Is this feature set currently missing from the proc macros perhaps?

**Comment by mhammond** [comment]
Sadly our online docs aren't versioned, but I think you will find this only works on current git main. A new release with this capability should be out within a week.

**Comment by mhammond** [comment]
Thanks for getting back - I'm fairly sure it is fixed in git, so we let's just reopen it if we find it is not.
