### ISSUE TITLE
What are the advantages of using an external crate for hash instead of the one from the std

### ISSUE THREAD

**Issue by stormshield-gt** [mozilla/uniffi-rs#1958]
Just out of curiosity, what are the advantages of using an external crate [siphasher](https://github.com/jedisct1/rust-siphash) instead of using the hash from the std, which also use this algorithm?

**Comment by badboy** [comment]
That's spelled out in the commit where we switched to it: https://github.com/mozilla/uniffi-rs/commit/6033f776c2
libstd exposes _a_ hasher, but does not guarantee it will be the same forever. It happens to be a siphasher right now, but it already changed at least once.

**Comment by stormshield-gt** [comment]
Thanks for the clarification, I've should have git blame the code.

Do we need a cryptographic secure hash like sip hasher here or for we could use for instance non-cryptographic hash like [rustc_hash](https://docs.rs/rustc-hash/latest/rustc_hash/)?
I suppose this is not used in performance critical code and obviously you seem to care about stability so I'm not asking to change it, just if we could.

**Comment by badboy** [comment]
No, this is merely a safeguard against different UniFFI versions in use.
The input is fully determined by the code that's statically there and compiled, so DoS resistance is not an issue really.
All we need is that it's stable across bit width and endianness, and given siphash's use inside libstd it's a reasonable and trustworthy choice
