### ISSUE TITLE
Python bindings missing threading import

### ISSUE THREAD

**Issue by itrumper** [mozilla/uniffi-rs#1967]
After generating the bindings for Python using UniFFI in library mode, I see a warning from the linter that states `"threading" not defined`, which looks to come from some auto-generated scaffolding to do pointer management. See `threading.Lock()` in the `__init__` method. I think the fix is just to `import threading`, but I also want to make sure something isn't going on that I'm missing and will cause unforeseen bugs down the line at runtime. Thanks!

```Python
class _UniffiPointerManagerGeneral:
    """
    Manage giving out pointers to Python objects on non-CPython platforms

    This has the same API as _UniffiPointerManagerCPython, but doesn't assume we're running on
    CPython and is slightly slower.

    Instead of using real pointers, it maps integer values to objects and returns the keys as
    c_size_t values.
    """

    def __init__(self):
        self._map = {}
        self._lock = threading.Lock()
        self._current_handle = 0

    def new_pointer(self, obj):
        with self._lock:
            handle = self._current_handle
            self._current_handle += 1
            self._map[handle] = obj
        return handle

    def release_pointer(self, handle):
        with self._lock:
            return self._map.pop(handle)

    def lookup(self, handle):
        with self._lock:
            return self._map[handle]
```

**Comment by badboy** [comment]
yeah looks like we're only importing it here: https://github.com/mozilla/uniffi-rs/blob/26a2fef271e78e9be3cfa5385d96e2c130eaf219/uniffi_bindgen/src/bindings/python/templates/CallbackInterfaceRuntime.py#L1

but it's also used here: https://github.com/mozilla/uniffi-rs/blob/26a2fef271e78e9be3cfa5385d96e2c130eaf219/uniffi_bindgen/src/bindings/python/templates/PointerManager.py#L46

I think a double-import is no problem in Python (though don't tell the linter), so we could add it to PointerManager too.

**Comment by mhammond** [comment]
huh - I didn't understand how our tests worked, but apparently that class is only used "on non-CPython platforms". Given we don't test any of them I do wonder how well that works in practice.

> I think a double-import is no problem in Python

While that's true, we do also have [`add_import()`](https://github.com/mozilla/uniffi-rs/blob/26a2fef271e78e9be3cfa5385d96e2c130eaf219/uniffi_bindgen/src/bindings/python/templates/CustomType.py#L33) which should ensure it's only imported once (and IIRC, also ensures they are at the top of the file)
