### ISSUE TITLE
Python doesn't generate return type of async functions

### ISSUE THREAD

**Issue by giarc3** [mozilla/uniffi-rs#1970]
If I export a function with a signature of
```
#[uniffi::export]
fn double(num: u32) -> u32
```
then it generates Python with a function signature of
```
def double(num: "int") -> "int":
```
---
But if I change the Rust to an `async` function, it generates
```
def double(num: "int"):
```
with no return type specified. This leads to Python documentation saying the return type is `Coroutine[Any, Any, Any]` and warnings whenever I try to access fields on the returned value.

**Comment by mhammond** [comment]
Sadly we don't have many tests here so I'm not easily able to verify what the correct thing to generate is - I *think* it should generate `-> "Awaitable[int]"` - is that correct? Can you verify by hand-editing the generated .py that does what you expect?

**Comment by mhammond** [comment]
(alternatively, I think we could arrange to generate an `async` fn there, which, IIUC, would be happy with `-> "int"`)

**Comment by giarc3** [comment]
I believe that adding `async` and indicating the return type as normal is the correct thing to do here. I hand-edited the generated code and confirmed that it matched my expectation when calling the function

**Comment by mhammond** [comment]
I thought changing to async will also require the final return to be "return await" or similar?

**Comment by giarc3** [comment]
You're correct, that's also necessary. The return statement it generated for me is a call to `_uniffi_rust_call_async`, so it should change to `return await _uniffi_rust_call_async`

**Comment by giarc3** [comment]
Completed by https://github.com/mozilla/uniffi-rs/pull/1984
