### ISSUE TITLE
Create contributing.md

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/uniffi-rs#199]
The project is still young, and a lot can change, but it might be worthwhile to create this document 😄.

It should highlight all a contributor needs to get set up, this includes:
- All the compilers/libraries they need, these are highlighted in the examples' README.md's, example:
> If you want to try it out, you will need:
    - The Kotlin command-line tools, particularly kotlinc.
    - The Java Native Access JAR downloaded and its path added to your $CLASSPATH environment variable.
    - Python 3
    - The Swift command-line tools, particularly swift, swiftc and the Foundation package.
- Maybe a quick overview of the project structure:
  - How the tests are set up in examples
  - Where to find the bindings, templates, and general interfaces
  - Where the parsing happens
- Possibly move some of the implementation details in our [README.md](https://github.com/mozilla/uniffi-rs/blob/main/README.md) there?

Also, any recommendations to what should be included in the document are welcome!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-8)
┆Epic: local development, ci and release (backlog)
┆Issue Number: UNIFFI-8

**Comment by rfk** [comment]
Oh hey! We have one of these now! Ref https://github.com/mozilla/uniffi-rs/blob/main/docs/contributing.md
