### ISSUE TITLE
Example: How to run the trait function defined in rust instead the implementation in caller?

### ISSUE THREAD

**Issue by hainesc** [mozilla/uniffi-rs#1993]
I was doing something similar with the example of trait, where in the driver code, let's say swift or python, I read the config and construct a trait, for simple, if I read word `go`, I make a `GoButton` as defined in the rust code, If I read a `stop`, I make a `StopButton`. and then run its `name()` function which defined in the trait. It not the same with the example in test, where we have to implement `PyButton` and its trait function, here is `name()`, I 'd to run the function defined in rust.

```
# Test a button implemented in Python
class PyButton(Button):
    def name(self):
        return "PyButton"

assert(press(PyButton()).name() == "PyButton")
```
```
pub trait Button: Send + Sync {
    fn name(&self) -> String;
}

struct GoButton {}

impl Button for GoButton {
    fn name(&self) -> String {
        "go".to_string()
    }
}

struct StopButton {}

impl Button for StopButton {
    fn name(&self) -> String {
        "stop".to_string()
    }
}
```

cc @bendk @mgeisler for help, thanks!

**Comment by mhammond** [comment]
You'd need to expose a function from Rust, say, `fn get_go_button() -> Arc<dyn Button> { Arc::new(GoButton) }`. Once you've called that you could use `GoButton` and `StopButton` interchangeably when interacting with other Rust code (ie, any other function which takes a `dyn Button` as a param would accept either)

**Comment by hainesc** [comment]
> You'd need to expose a function from Rust, say, `fn get_go_button() -> Arc<dyn Button> { Arc::new(GoButton{}) }`. Once you've called that you could use `GoButton` and `StopButton` interchangeably when interacting with other Rust code (ie, any other function which takes a `dyn Button` as a param would accept either)

Thanks for your reply, I will have a try.
