### ISSUE TITLE
Tests broken in kotlin project using uniffi 

### ISSUE THREAD

**Issue by shaiguelman** [mozilla/uniffi-rs#1995]
I have some Android instrumented tests our project that uses uniffi. They currently work on release 26.0.0 but they are broken when downloading the main branch directly. When running the instrumented tests I receive the error:

`Class content provided for type descriptor uniffi.greco_core.UniffiRustFutureContinuationCallback actually defines class uniffi.greco_core.uniffiRustFutureContinuationCallback`

I was able to fix this issue by manually changing the code in the generated file from 
`internal object uniffiRustFutureContinuationCallback: UniffiRustFutureContinuationCallback` to 
`internal val uniffiRustFutureContinuationCallback = object : UniffiRustFutureContinuationCallback`. 
An alternative is to change the name of the object so it doesn't match the interface exactly. There used to be a typo which is why this error did not appear before (since the object and interface had slightly different names) but that was fixed in this PR: https://github.com/mozilla/uniffi-rs/commit/d4c38acc07224e3af48acc2c8a2d29aec7b92362#diff-81df8a62bb029daa169f73441b69dd1b6a49c2c79cc2a750ee578d6cb9c9bf47R9

I'm happy to perform the work to fix this myself if given the go ahead, although it will take me a while to get set up if you need this fixed more urgently.

**Comment by mhammond** [comment]
Can you please try and repro it in one of our fixtures or examples (maybe "futures")?

**Comment by stan-stately** [comment]
can confirm im seeing this as well and renaming fixes the issue.

**Comment by mhammond** [comment]
I'm sure this bug exists and I'm sure the fix will be easy, all we need is a repro!

**Comment by jmartinesp** [comment]
I believe this an Android-only issue, so the only way to reproduce it is to either launch an app or some instrumented tests in a project with some Rust library built with the latest sources. If it's ok to provide an external project for repro, I might be able to get something up today/early tomorrow.

**Comment by mhammond** [comment]
ah, I misunderstood - I assumed it would be able to be reproduced with just kotlin. I don't think it's necessary to introduce an Android example for this issue, partially because it's really not clear how we'd exercise it in CI. It just would have made it far more obvious about exactly what needs to be renamed. I'm reluctant to put up a PR based on a guess though, so if you can put one up and verifies it fixes your issue I'd be happy to review it.

**Comment by stan-stately** [comment]
PR: https://github.com/mozilla/uniffi-rs/pull/2002
