### ISSUE TITLE
Can you pass functions as arguments to uniffi?

### ISSUE THREAD

**Issue by tomadimitrie** [mozilla/uniffi-rs#2003]
For example, let's take the following trait:
```rs
#[uniffi::export]
trait FFIView: Send + Sync {
    fn render(&self, function: fn());
}
```

Currently this gives the following compilation error: 
```
the trait bound `fn(): Lift<UniFfiTag>` is not satisfied
```

I understand that this is a pretty complicated issue and most probably cannot be done directly, but I was wondering if there is any workaround

**Comment by badboy** [comment]
You should be able to do that using [`callbacks`](https://mozilla.github.io/uniffi-rs/udl/callback_interfaces.html) or really just [`traits implemented by foreign languages`](https://mozilla.github.io/uniffi-rs/foreign_traits.html)

**Comment by tomadimitrie** [comment]
@badboy that might work, but I have something like this in mind:
I am building an UI framework, so let's take a Button for example (I'm on mobile right now so apologies for potential compilation errors):

```rs
#[derive(uniffi::Record)]
struct Button {
    on_click: fn()
}

#[uniffi::export]
fn app() -> Button {
    Button { 
        on_click: || {}
    }
}
```

Swift will call the `app()` function, parsing the result and displaying a `UIButton` or whatever. When the native button is pressed, I need to call the Rust implementation of the handler (the struct field). 

Yes, I know I can use an Object for this, but the idea is that the handler should be provided by the user. I was also thinking of this:

```rs
// make Button an Object instead of a Record

#[uniffi::export]
impl Button {
    fn on_click(&self) {
        (self.on_click)();
    }
}
```

But I was wondering whether there is a better solution for this

**Comment by badboy** [comment]
If the `on_click` callback is implemented on the Rust side anyway, there's no need to pass it over to the foreign-language side.
In that case an object is the better way to handle this.

**Comment by mhammond** [comment]
I think we gave a good workaround, and we aren't going to make functions first-class, so let's close this.
