### ISSUE TITLE
anyhow on uniffi 0.26.1

### ISSUE THREAD

**Issue by ulibte** [mozilla/uniffi-rs#2006]
I am learning how to use uniffi. i am reading the docs, and i am having a problem with throwing errors when i try to replicate the docs.

so i created a new rust package with cargo new and i just copied the code of the docs into this rust package. it worked when i use cargo build to compile on the uniffi version 0.25.3, but then i changed the version to 0.26.1, and it's giving me an error.

Maybe i am doing something wrong, or the new version changed something that the docs don't mention. so i am posting this issue here, and sorry if i am doing something wrong.

below is the error:

```
error: failed to run custom build command for `adder v0.1.0 (/volume/adder)`

Caused by:
  process didn't exit successfully: `/volume/adder/target/debug/build/adder-4379610d6dc82aae/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=./src/adder.udl
  cargo:rerun-if-env-changed=UNIFFI_TESTS_DISABLE_EXTENSIONS

  --- stderr
  thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_bindgen-0.26.1/src/interface/mod.rs:1024:14:
  unknown throw type: Some(Object { module_path: "adder", name: "MyError", imp: Struct })
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

here is all the files: 
[adder.tar.gz](https://github.com/mozilla/uniffi-rs/files/14474766/adder.tar.gz)

below is the main code i used:

#### src/adder.udl
```
namespace adder {
  u32 add(u32 left, u32 right);

  [Throws=MyError]
  void oops();
};

[Traits=(Debug)]
interface MyError {
  string message();
};
```

#### src/lib.rs
```
uniffi::include_scaffolding!("adder");

use std::sync::Arc;

pub fn add(left: u32, right: u32) -> u32 {
    left + right
}

#[derive(Debug, thiserror::Error)]
#[error("{e:?}")] // default message is from anyhow.
pub struct MyError {
    e: anyhow::Error,
}

impl MyError {
    fn message(&self) -> String {
        self.to_string()
    }
}

impl From<anyhow::Error> for MyError {
    fn from(e: anyhow::Error) -> Self {
        Self { e }
    }
}

fn oops() -> Result<(), Arc<MyError>> {
    let e = anyhow::Error::msg("oops");
    Err(Arc::new(e.into()))
}
```

#### Cargo.toml
```
[package]
name = "adder"
version = "0.1.0"
edition = "2021"

[lib]
name = "adder"
crate-type = ["cdylib"]

[dependencies]
uniffi = { version = "0.26.1" }
anyhow = "1"
thiserror = "1.0"

[build-dependencies]
uniffi = { version = "0.26.1", features = ["build"] }

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
```

**Comment by mhammond** [comment]
I can't explain what you saw - neither 0.25 nor 0.26 support interfaces as errors, this was only introduced very recently and is not yet in a release, although the docs can be found at https://github.com/mozilla/uniffi-rs/blob/main/docs/manual/src/udl/errors.md#interfaces-as-errors. To use this capability you would need to use uniffi directly from the git main branch.

**Comment by ulibte** [comment]
thank you for your response XD, and sorry for any confusion.

**Comment by ulibte** [comment]
Thank you for your response and sorry for any confusion.
