### ISSUE TITLE
How to mutate the bytes/vec passed to the Rust side?

### ISSUE THREAD

**Issue by irvingoujAtDevolution** [mozilla/uniffi-rs#2011]
I have a rust function like this
```
#[uniffi::export]
pub fn push_some_data(mut buf: Vec<u8>) -> Option<u32> {
    for _ in 0..65536 {
        buf.push(42);
    }
    None
}
```

and after I compile, generate the bindings etc. I try to use it with python functions

```

import sys
import os
bindings_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'bindings', 'python'))
sys.path.append(bindings_path)
import bytes_intense

arr = bytes([1, 2, 3, 4, 5])
bytes_intense.push_some_data(arr)
print(arr)

```

but the array remains unchanged, is it expected?

**Comment by mhammond** [comment]
That is expected - under the hood we copy the Python sequence contents into a new Rust vec. There are no plans to change this, because it's almost impossible to have a Rust Vec<> be an "alias" over all supported foreign bindings. You'd need to return it or similar.
