### ISSUE TITLE
Async Callback / Async Trait

### ISSUE THREAD

**Issue by jasl8r** [mozilla/uniffi-rs#2012]
I'm having trouble creating a trait with and async function.  It looked like from the conversation this was intended to be implemented in #1834 but I'm not sure if it was done.  I tried to play with the UDL to get it to work as an async callback, but that does not work either.

```javascript
[Trait]
interface AudioStream {
    [Async]
    void send_packet(bytes packet);
};
```

In part this fails due to improper code gen creating a `fn async...` instead of `async fn...`, but making that simple fix and adding the `#[async_trait]` marker is not really a solution.  The the presumably proper error message of `async trait methods are not supported` appears.

If I tweak the UDL into an async callback the problem that remains is `lifetimes do not match method in trait` and with `cargo-expand` we can see that the async trait becomes:

```rust
fn send_packet<'life0, 'async_trait>(
        &'life0 self,
        packet: Vec<u8>,
    )
```

while the impl remains the untweaked:

```rust
fn send_packet(&self, packet: Vec<u8>
```

Are async traits supposed to work?

**Comment by bendk** [comment]
This hasn't been released yet, so you'd need to use the `main` branch to test it out.

We have a long-standing issue where we build our docs from `main` but users are actually using the latest released version.  I made https://github.com/mozilla/uniffi-rs/issues/2016 to address that.

**Comment by CaioSym** [comment]
@bendk Do you know when the next release will be? I see docs for how to cut a release but not sure I follow what the release cadence is. Would love to use this but targeting main seems a little brittle.

**Comment by bendk** [comment]
The current plan is to merge the last PR in the [0.27 label](https://github.com/mozilla/uniffi-rs/labels/v0.27) and then release.  I'm hoping to get it out tomorrow or Wednesday.

**Comment by skeet70** [comment]
@CaioSym @jasl8r have you tried this with the current release?

**Comment by CaioSym** [comment]
@skeet70 Currently using 0.27.1 and things look good on my end. Everything compiles and no new issues runtime wise so far. That being said, obligatory disclaimer that my project is not in a production stage yet :)

**Comment by bendk** [comment]
Awesome, I guess we can close this one.

**Comment by jasl8r** [comment]
Sorry @bendk, yes this is all set now and I'm making use of it, thanks!

**Comment by bendk** [comment]
No problem at all, glad it's working well for you.
