### ISSUE TITLE
Make ForeignBytes Mutable.

### ISSUE THREAD

**Issue by irvingoujAtDevolution** [mozilla/uniffi-rs#2014]
Hello There, 

I am not sure if you have plan to support this kind of operation, as this increases risk in memory safety. However, this could have a huge improvement in performance for bytes intense applications.

Currently, this is [what exposed](https://docs.rs/uniffi/0.25.3/uniffi/struct.ForeignBytes.html) . This is by design immutable. One could mutate it using unsafe block and operations, however this behavior would be undefined and subject to changes in the ForeignBytes implementation. I would propose to add a method `as_mut_slice`, to have the caller get's access to the underlying pointer safely.

Thank you for you consideration. Looking forward to hear back from you.

**Comment by mhammond** [comment]
This is being discussed in both #1974 and #1485 - I don't think it's worth keeping a third open so I'll close this, but the tl;dr is that we understand the desire but have no plans at this stage.
