### ISSUE TITLE
Documented attribute macro `uniffi::method` is missing

### ISSUE THREAD

**Issue by cowlicks** [mozilla/uniffi-rs#2031]
I was following [the documentation](https://mozilla.github.io/uniffi-rs/proc_macro/index.html?highlight=method#renaming-functions-methods-and-constructors) for how to rename a method. But it does not work. it seems like the macro just does not exist. Also renaming a costructor seems to fail too

The following code fails:
```rust
#[derive(uniffi::Object)]
struct Foo(u64);

#[uniffi::export]
impl Foo {
    #[uniffi::constructor(name = "new")]
    fn ffi_new() -> Self {
        todo!()
    }

    #[uniffi::method(name = "something")]
    async fn ffi_get(&self, key: &[u8]) -> u64 {
        todo!()
    }
}
```

This fails with:
```
error: attribute arguments are not currently recognized in this position
  --> src/ffi.rs:20:7
   |
20 |     #[uniffi::constructor(name = "new")]
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: could not find `method` in `uniffi`
  --> src/ffi.rs:25:15
   |
25 |     #[uniffi::method(name = "something")]
   |               ^^^^^^ could not find `method` in `uniffi`

```

**Comment by jplatte** [comment]
It sounds like you're probably not using the latest git version. The online documentation currently always reflects that, rather than the latest release. See also #2016.

**Comment by cowlicks** [comment]
Indeed that is the problem. Thank you
