### ISSUE TITLE
uniffi-rs 0.27 throw error with Constructor return type must be Arc<Self>

### ISSUE THREAD

**Issue by SoloJiang** [mozilla/uniffi-rs#2051]
## Screenshot
<img width="1135" alt="image" src="https://github.com/mozilla/uniffi-rs/assets/14757289/e74fab7e-532a-46a8-b121-46c239accd7a">

It's compile successful with 0.26.1

## Minial Case

```rust
#[derive(uniffi::Object)]
pub struct Client {
}

#[uniffi::export]
impl Client {
    #[uniffi::constructor]
    pub fn new() -> Self {
      Self{}
    }
}
```

**Comment by SoloJiang** [comment]
I have tried use Arc<Self> instead of Self, it's error too.

**Comment by mhammond** [comment]
You need `Arc<>` - see https://mozilla.github.io/uniffi-rs/proc_macro/index.html#the-uniffiexport-attribute and for a concrete example, see https://github.com/mozilla/uniffi-rs/blob/dddcf4f677ea9f455e0637c3fc8679a39f9a2ddb/fixtures/proc-macro/src/lib.rs#L88-L92. The `Arc<>` is not needed when declaring the object in UDL - is it possible you changed from udl to procmacros?

**Comment by SoloJiang** [comment]
I'm using procmacros not udl file, the error occurred when used procmacros. In the docs, Arc<> and Self is either supported. Avoid the cause of Self usage, I tried Arc, however it was failed too.

**Comment by SoloJiang** [comment]
But uniffi-rs v0.26.1 is ok with the same code

**Comment by mhammond** [comment]
What's the exact error you get when using `Arc<Self>`?

**Comment by SoloJiang** [comment]
The same error.

**Comment by mhammond** [comment]
I suspect there might be something else going on then - are you quite sure you are generating the bindings with the new uniffi version? As I linked above, we have many tests in the repo for this, all of which work.

**Comment by SoloJiang** [comment]
Okay I can post my example repo for u tomorrow, I'm in night currently😓

**Comment by SoloJiang** [comment]
My repo: https://github.com/SoloJiang/uniffi-rs-constructor-return-type

You can try `cargo swift package -p=ios`

When you downgrade uniffi-rs version to 0.26.1, it will be success.

**Comment by SoloJiang** [comment]
<img width="1120" alt="image" src="https://github.com/mozilla/uniffi-rs/assets/14757289/bc9dcf06-7d25-4086-9810-208cd540eb16">

**Comment by mhammond** [comment]
This would appear to be an interop issue with `cargo swift`?

**Comment by SoloJiang** [comment]
Yes, I use cargo-swift to transform swift package now. May you think it's bug of cargo-swift? But the uniffi -rs older version is ok

**Comment by mhammond** [comment]
I'm sorry but I've no idea if it is a bug in cargo-swift as I don't know anything about it. However, if your error message is saying "constructor must return an Arc<>" when it *is* returning an Arc<> then it seems like something we don't understand is going on. For us to take this further we probably need either a patch to our existing tests which demonstrate the problem, or a reproduction in another repo that uses UniFFI as documented.

**Comment by bendk** [comment]
I believe this is supported and the only issue is the macro error is confusing.   I agree with @mhammond that this looks like an interop issue:
  - We have a [fixture that tests this](https://github.com/mozilla/uniffi-rs/blob/5854aef638b52feec73bdd0936eb28ab8804a639/fixtures/proc-macro/src/lib.rs#L94-L100)
  - If I check out your repo, `cargo build` succeeds it's only when I run `cargo swift` that I get errors.

**Comment by SoloJiang** [comment]
I know your meaning. I don't know much about ffi before it.So I will try custom gen swift package without use cargo-swift. If I find the bug of cargo-swift, I will take a pr to fix. Thanks.

**Comment by mhammond** [comment]
Sorry for the confusion - as Ben points it, it *should* be possible to return plain `Self` - we still don't understand the root of your problem though, but adding the `Arc<>` wrapper should not be necessary.

**Comment by mhammond** [comment]
We'd be happy adding some optional tests using cargo-swift.

**Comment by SoloJiang** [comment]
Alright this is cargo-swift compatible problem. https://github.com/antoniusnaumann/cargo-swift/commit/f8535b9e3d8568bc0732f407b8f643070049a5d1
