### ISSUE TITLE
Code generation failing in Python

### ISSUE THREAD

**Issue by weslenng** [mozilla/uniffi-rs#206]
I'm trying to do #202 but `cargo run -- generate` fail with:

```sh
thread 'main' panicked at '[TODO: coerce_py(Sequence(Record("TodoEntry")))]', uniffi/src/bindings/python/gen_python.rs:97:18
```
- Mac OS Mojave 10.14.6
- Python 3.8.3

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1626)

**Comment by tarikeshaq** [comment]
Hi @weslenng! Thanks for uncovering this! it's a by-product of not having support for sequences yet in Python 😢 I added a comment in #202 that might help unblock you if you were on it. Let me know if you have any questions!

**Comment by rfk** [comment]
Hi @weslenng, just want to give you a heads-up as well, we recently landed a pretty significant restructuring of the code in https://github.com/mozilla/uniffi-rs/pull/205. I don't think it should affect much of the details of what you're working, but it has probably moved some of the files around!

**Comment by weslenng** [comment]
> Hi @weslenng, just want to give you a heads-up as well, we recently landed a pretty significant restructuring of the code in #205. I don't think it should affect much of the details of what you're working, but it has probably moved some of the files around!

Hi, I took a look at #205 and it was a really interesting code restructuring.
I'll start doing on top of it, thank you for letting me know!
