### ISSUE TITLE
Deriving `uniffi::Record` together with `ZeroizeOnDrop` does not compile. Solvable?

### ISSUE THREAD

**Issue by Sajjon** [mozilla/uniffi-rs#2080]
I've recently tried to add [Zeroize](https://crates.io/crates/zeroize) on my UniFFI records / enums, like so:

```rust
#[derive(
    Zeroize,
    ZeroizeOnDrop,
    Clone,
    uniffi::Record,
)]
pub struct Mnemonic {
    pub words: Vec<BIP39Word>, // BIP39Word: Zeroize, Clone, uniffi::Record
}
```

Results in compilation error: 
```
cannot move out of type `Mnemonic`, which implements the `Drop` trait
move occurs because `obj.words` has type `Vec<BIP39Word>`, which does not implement the `Copy` trait
```

Hmm.... is this even solvable?

**Comment by jplatte** [comment]
UniFFI could certainly generate code that works without destructuring, but for zeroize in particular I think you'd be defeating the purpose of that derive since UniFFI would be creating copies of the bytes that don't get zeroized on drop.

**Comment by Sajjon** [comment]
> but for zeroize in particular I think you'd be defeating the purpose of that derive since UniFFI would be creating copies of the bytes that don't get zeroized on drop.
Right that is what I feared, but maybe some optimization could be done in "that realm", e.g. if UniFFI could check if the Source or Target implements Zeroize and could use it on any copies, so that only the the resulting Target / Source contains those bytes, but any "ephemeral copies" are zeroed out during the conversion?

**Comment by Sajjon** [comment]
> It's impossible for a macro to check whether a trait is implemented, trait solving happens after macro expansion (trait solving depends on the output of all macros in a given source tree incl. dependencies).

Right that makes sense, thanks for explaining @jplatte ! I'm still fairly new to Rust (started in December last year) and have only beeng doing macros since February.

> It would be possible to introduce #[uniffi(zeroize)] as a helper attribute though

Yes that would really be amazing! I might try to give a PR a go later on!

**Comment by mhammond** [comment]
I'd suggest you start with a justification first - I can only speak for myself, but @jplatte is correct regarding appetite - I doubt we want to support every cool-sounding crate out there. In this specific case, the hurdle to overcome is already noted above - uniffi makes *many* copies of records with the expectation that many of them live in the foreign code - in these scenarios, zeroize seems, frankly, pointless.

**Comment by hherb** [comment]
Adding a concrete data point from a secrets-manager (client-only password vault) that hit exactly this, in case it's useful for re-weighing the opt-in `#[uniffi(zeroize)]` idea @jplatte floated above.

Our case is narrower than the `ZeroizeOnDrop`-on-`Record` framing this issue opened with, and sidesteps @mhammond's "many copies live in foreign code" objection: we only care about the **inbound, transient** direction — a user-entered master password / BIP-39 recovery phrase travelling foreign → Rust as `bytes`, used once to derive a key, then gone. There's no long-lived foreign-held copy we'd be failing to zeroize; the concern is purely the *marshalling residue* left in freed-not-yet-reused heap.

Concretely, for a `bytes` argument there are two copies neither side can reach:
1. Swift side — `FfiConverterRustBuffer.lower` builds `var writer = createWriter()` (`[UInt8]`), appends the plaintext, and hands it to `RustBuffer(bytes:)`. That `writer` array is freed without overwrite. The caller can zeroize its own `Data`, but not this generated intermediate.
2. Rust side — the lifted `Vec<u8>` can be zeroized by the callee, but the backing `RustBuffer` is freed via `uniffi_rustbuffer_free` → `RustBuffer::destroy` → `drop(destroy_into_vec())`, a plain `Vec<u8>` drop with no scrub, and that free happens in generated scaffolding *before* the callee runs.

A scrubbing global allocator covers (2) but not (1), and is a heavy global knob for one argument. So an opt-in per-argument/per-type attribute that (a) zeroizes the foreign writer buffer after lowering and (b) routes the Rust-side free through a zeroizing path would be the only thing that closes it. Fully understand if the appetite still isn't there — we've documented it as an accepted FFI-boundary limitation on our side either way. Mostly registering that there's at least one real consumer for whom the transient-secret case (as opposed to "zeroize everything") is the motivating one.

**Comment by mhammond** [comment]
Would https://github.com/mozilla/uniffi-rs/pull/2878 change this in any way?

**Comment by hherb** [comment]
> Would [#2878](https://github.com/mozilla/uniffi-rs/pull/2878) change this in any way?

Oh yes! Thanks for pointing this out. Looking forward to a release containing this, solves most of my concerns.
