### ISSUE TITLE
Clarify `check_library_path` semantics

### ISSUE THREAD

**Issue by mhammond** [mozilla/uniffi-rs#2095]
[This library mode check](https://github.com/mozilla/uniffi-rs/blob/e98f98a1957d197241ce7325ff1881dd97a37987/uniffi_bindgen/src/bindings/python/mod.rs#L53) is unclear. Every language has an identical check, except Swift which is a noop.

It looks like it's really just checking in a round-about way that `library_mode::calc_cdylib_name` didn't return `None` - but why trait and that fact Swift is the only thing that does not check? And in my local test, Swift doesn't fail if you do. I got a bit lost in blame, so @bendk do you have recollections about this?

**Comment by bendk** [comment]
Yeah, that's definitely unclear.  My half memory / half guess is that Swift doesn't need the check because it can work with static linking.

**Comment by mhammond** [comment]
This was answered in https://github.com/mozilla/uniffi-rs/pull/2094#discussion_r1591365779
