### ISSUE TITLE
Issues while importing and using a created swiftmodule

### ISSUE THREAD

**Issue by parthdt** [mozilla/uniffi-rs#2099]
Hello,

I've been tinkering with `uniffi` recently, since I might be using it for My Master Thesis Project.
I would use it for using rust code inside of a swift project.

To understand the whole process, I've tried to compile the `arithmetic` example, to a `swiftmodule` using the guide here: [Compiling a Swift module](https://mozilla.github.io/uniffi-rs/swift/module.html).

I'm successfully able to do this, and a `arithmetic.swiftmodule` is created.    
Now, similar to the tests for swift here: [Swift Tests for arithmetic](https://github.com/mozilla/uniffi-rs/blob/main/examples/arithmetic/tests/bindings/test_arithmetic.swift), when I try to import this module in REPL, I get the following error:
```
swift -I . -L . -la -Xcc -fmodule-map-file=/home/dresden/fuzzing/uniffi-rs/out/arithmeticFFI.modulemap -repl
Welcome to Swift version 5.10 (swift-5.10-RELEASE).
Type :help for assistance.
  1> import arithmetic
  2> add(a:1,b:2)
error: Couldn't lookup symbols:
  arithmetic.add(a: Swift.UInt64, b: Swift.UInt64) throws -> Swift.UInt64
  arithmetic.add(a: Swift.UInt64, b: Swift.UInt64) throws -> Swift.UInt64

  2> :q

```

Also, if I try to directly run the `test_arithmetic.swift`, another error is generated:
```
swift -I . -L . -larithmetical -Xcc -fmodule-map-file=/home/dresden/fuzzing/uniffi-rs/out/arithmeticFFI.modulemap ../examples/arithmetic/tests/bindings/test_arithmetic.swift
JIT session error: Symbols not found: [ $s10arithmetic15ArithmeticErrorON, $s10arithmetic3add1a1bs6UInt64VAF_AFtKF, $s10arithmetic3div8dividend7divisors6UInt64VAF_AFtF, $s10arithmetic3sub1a1bs6UInt64VAF_AFtKF, $s10arithmetic5equal1a1bSbs6UInt64V_AFtF ]
Failed to materialize symbols: { (main, { __swift_instantiateConcreteTypeFromMangledName, $ss5Error_pMD, main, symbolic ______p s5ErrorP, got.$ss5ErrorMp }) }
```

I'm not sure what the problem is, since the same workflow works with python, so could it be a swift issue, or maybe I'm doing a wrong step somewhere? 

Any help would be highly appreciated 😄 

Best,
Parth

**Comment by mhammond** [comment]
I don't know much about swift, but it might help to see if our test harness works for you - executing something like `UNIFFI_TESTS_DISABLE_EXTENSIONS=rb,py,kt,kts cargo test` from that example's directory should run our swift test. If that works then I guess you'd be looking for differences in the command-lines used. If that doesn't then I've no real idea other than it would appear to be related to your local environment somehow?

@Sajjon is a user of this lib who works with swift a lot, so maybe he can help?

**Comment by parthdt** [comment]
Hi guys,

Thanks a lot for your responses.

@mhammond The Swift tests are passing, no problems there. I can't seem to recreate it while importing the module myself though.
Before this, I had issues while actually compiling the `swiftmodule`. To solve this, I also thought about the command line, and then matched it as in the [Uniffi Test Bindings Generation](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/swift/test.rs).   

This solved the compilation issue, so I'm sure that's not the problem. I'll definitely try clearing out the environment vars though.

@Sajjon I agree, it does look weird. I had a similar issue with Swift 5.7, which is when I thought to update it to Swift 5.10. Same issues here. As suggested, I might try Swift 6.0 trunk dev.

I feel like the issue could also be in some small thing that I might be missing somewhere. Since `cargo test` is working. I'll dig deeper 😄

**Comment by parthdt** [comment]
Small update gents,

When I try to run the compiled `arithmetic.swiftmodule` in repl using:
```
swift -I . -L . -la -Xcc -fmodule-map-file=/home/dresden/fuzzing/uniffi-rs/out/arithmeticFFI.modulemap -repl
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb.embedded_interpreter'
error: This version of LLDB does not support DWARF version 5 or later.
Welcome to Swift version 5.10 (swift-5.10-RELEASE).
Type :help for assistance.
  1> import arithmetic 
  2> let ans = try! add(a:1,b:2) 
ans: UInt64 = <extracting data from value failed>

error: Couldn't lookup symbols:
  arithmetic.add(a: Swift.UInt64, b: Swift.UInt64) throws -> Swift.UInt64
  arithmetic.add(a: Swift.UInt64, b: Swift.UInt64) throws -> Swift.UInt64

```
I get some errors, BUT!, when I try to run a `test.swift` file containing:
```
import arithmetic

let ans = try! add(a: 2, b: 4)
print(ans)
```
Everything goes well:
```
swift -I . -L . -la -Xcc -fmodule-map-file=/home/dresden/fuzzing/uniffi-rs/out/arithmeticFFI.modulemap test.swift 
6
```

As a complete swift noobie, I'm not sure why this behaviour happens. Seems to be an issue with `repl`.

**Comment by Sajjon** [comment]
I've been using Swift for 10 years, and actually never ever used REPL. And I haven't heard any of my senior Swift colleagues using REPL either. So I think there might be a risk of it not being a focus by Apple, since AFAIK it is not so popular a tool.
