### ISSUE TITLE
how to send Rust opaque type to Kotlin

### ISSUE THREAD

**Issue by Sherlock-Holo** [mozilla/uniffi-rs#2105]
```rust
struct FfiTcpStack {
    // private fields
}

unsafe impl<UT> FfiConverter<UT> for FfiTcpStack {
    type FfiType = *const c_void;

    fn lower(obj: Self) -> Self::FfiType {
        let obj = Box::new(obj);

        Box::into_raw(obj) as _
    }

    fn try_lift(v: Self::FfiType) -> anyhow::Result<Self> {
        let obj = unsafe { Box::from_raw(v as *mut FfiTcpStack) };

        Ok(*obj)
    }

    fn write(_obj: Self, _buf: &mut Vec<u8>) {
        panic!("can't not write")
    }

    fn try_read(_uf: &mut &[u8]) -> anyhow::Result<Self> {
        panic!("can't not read")
    }

    const TYPE_ID_META: MetadataBuffer = MetadataBuffer::new();
}

#[uniffi::export]
fn create_ffi_tcp_stack() -> Result<FfiTcpStack, MyError> {
    todo!()
}
```

I want to export my type as an opaque type and send it to Kotlin, then Kotlin side can use it to do somethings, it is better if can call `FfiTcpStack` methods

but now there are some problems:

`unsafe impl<UT> FfiConverter<UT> for FfiTcpStack` is it a correct codes?

and

cargo clippy report error

```
#[uniffi::export]
    | ^^^^^^^^^^^^^^^^^ the trait `uniffi::LowerReturn<UniFfiTag>` is not implemented for `tcp_stack::FfiTcpStack`, which is required by `std::result::Result<tcp_stack::FfiTcpStack, tcp_stack::Error>: uniffi::LowerReturn<UniFfiTag>`
```

if all of them are wrong :(, how to do this correctly?

**Comment by Sherlock-Holo** [comment]
by the way I hope I can avoid write udl files

**Comment by Warez-L** [comment]
Did you tried:
```rs
#[derive(uniffi::Object)] 
struct FfiTcpStack {
    // private fields
}
```

More info:
https://mozilla.github.io/uniffi-rs/udl/interfaces.html

**Comment by Sajjon** [comment]
interested in doing networking calls on the FFI side? have a look at my project Sargon: 

Rust Side
https://github.com/radixdlt/sargon/blob/ac/system_with_drivers/src/system/drivers/networking_driver/networking_driver.rs

Swift side: https://github.com/radixdlt/sargon/blob/ac/system_with_drivers/apple/Sources/Sargon/Drivers/Networking/NetworkingDriver%2BURLSession.swift

You will also find me having implemented other "drivers" (FileStorage, UserDefaults, Logging etc)

**Comment by Sherlock-Holo** [comment]
thanks, `uniffi::Object` is what I need

**Comment by Sherlock-Holo** [comment]
> interested in doing networking calls on the FFI side? have a look at my project Sargon: 
> 
> Rust Side
> https://github.com/radixdlt/sargon/blob/ac/system_with_drivers/src/system/drivers/networking_driver/networking_driver.rs
> 
> Swift side: https://github.com/radixdlt/sargon/blob/ac/system_with_drivers/apple/Sources/Sargon/Drivers/Networking/NetworkingDriver%2BURLSession.swift
> 
> You will also find me having implemented other "drivers" (FileStorage, UserDefaults, Logging etc)

👍 I will see if I can learn something from it
