### ISSUE TITLE
Online docs have no language syntax highlighting

### ISSUE THREAD

**Issue by mhammond** [mozilla/uniffi-rs#2106]
eg, the Rust snippet at https://mozilla.github.io/uniffi-rs/Getting_started.html and for all our snippets.

I [tried using `codehilite` with `markdown_extensions` in `mkdocs.yml`](https://github.com/mozilla/uniffi-rs/blob/989db8cb71b2471dd561e4d6aad0d8e91001789b/mkdocs.yml#L18-L21) but it didn't work and I gave up.

**Comment by badboy** [comment]
That's because [support for it has been removed from the material theme a while ago](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#codehilite).
I have a patch ready to get the newer thing working.
