### ISSUE TITLE
Generating FFI bindings for dependent crates into one single Swift / Kotlin file?

### ISSUE THREAD

**Issue by imWildCat** [mozilla/uniffi-rs#2117]
Hello!

I'm wondering whether this can also be achieve using the current version of uniffi. If not, I would love to contribute.

I'd like to generate types from a dependency of my cargo workspace.

I notice that under the current `fixtures` folder, if I run

It will generate multiple swift files with same setup:

```sh
cargo run --features=uniffi/cli --bin uniffi-fixtures-futures generate  -l swift -o ./tmp --library 'path/to/uniffi-rs/target/debug/libuniffi_ext_types_lib.dylib' 
```

```swift
private extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }
```

```sh
➜  tmp git:(main) ✗ ls
custom_types.swift                 ext_types_customFFI.h              imported_types_sublib.swift        uniffi_one_nsFFI.h
custom_typesFFI.h                  ext_types_customFFI.modulemap      imported_types_sublibFFI.h         uniffi_one_nsFFI.modulemap
custom_typesFFI.modulemap          imported_types_lib.swift           imported_types_sublibFFI.modulemap
customtypes                        imported_types_libFFI.h            uniffi
ext_types_custom.swift             imported_types_libFFI.modulemap    uniffi_one_ns.swift
```

this would be a conflict.

Is there any method to "merge" these generated files into a single Swift source file?

**Comment by mhammond** [comment]
It's not currently possible, but on the latest main it would be much easier to make changes to allow that than on earlier versions.

> It will generate multiple swift files with same setup:
> this would be a conflict.

This shouldn't be a problem as `RustBuffer` is private - many of our fixtures (and production use) rely on this working, most notably [ext-types](https://github.com/mozilla/uniffi-rs/tree/main/fixtures/ext-types/lib)

**Comment by imWildCat** [comment]
thanks! how about Kotlin in this case?

**Comment by imWildCat** [comment]
I see. Thank you!
