### ISSUE TITLE
iOS Framework Expected in: /usr/lib/libc++.1.dylib

### ISSUE THREAD

**Issue by songhuaixu** [mozilla/uniffi-rs#2124]
```
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /private/var/containers/Bundle/Application/9BCB1E96-1365-4516-B9BE-854D1E99C150/Example.app/Frameworks/RustDemo.framework/RustDemo
  Expected in: /usr/lib/libc++.1.dylib
 in /private/var/containers/Bundle/Application/9BCB1E96-1365-4516-B9BE-854D1E99C150/Example.app/Frameworks/RustDemo.framework/RustDemo
```

**Comment by mhammond** [comment]
Sorry but we've no idea about your package or your environment. Are you able to reproduce this in any of our examples?

**Comment by badboy** [comment]
fwiw just doing a websearch for that symbol reveals a lot of issue reports for all sorts of projects. Seems most often this was some incompatibility between macOS versions.

**Comment by songhuaixu** [comment]
> fwiw just doing a websearch for that symbol reveals a lot of issue reports for all sorts of projects. Seems most often this was some incompatibility between macOS versions.

Yes, that's true. Thank you
