### ISSUE TITLE
Crates.io shows 0.27.2 but the associated tag doesn't exist

### ISSUE THREAD

**Issue by thunderbiscuit** [mozilla/uniffi-rs#2137]
As I updated our codebase to what I thought was the latest release (`0.27.1`), my IDE pointed out that there was a `0.27.2` version out. This is indeed the latest version on [crates.io](https://crates.io/crates/uniffi), but the tag does not exist on the repo nor in the changelog. Just pointing this out; it was a bit suspicious and I pinned our dependency to `0.27.1` for the moment.

**Comment by badboy** [comment]
Woops, might have been missed as part of the release process. We'll get that sorted.

**Comment by badboy** [comment]
Release commit: https://github.com/mozilla/uniffi-rs/commit/992844631c7b6934d70ae9d8fc5c55773560aa1b

**Comment by badboy** [comment]
properly pushed now: https://github.com/mozilla/uniffi-rs/releases/tag/v0.27.2
