### ISSUE TITLE
Advice on creating external bindings for a comment type system only

### ISSUE THREAD

**Issue by mikavilpas** [mozilla/uniffi-rs#2144]
Hello! I am looking for a way to use uniffi for generating [Lua Language Server type annotations](https://luals.github.io/wiki/annotations/) from rust code. I would like to ask for any advice or observations that might help 🙂 

My goal is to add a way for rust projects that use [mlua](https://github.com/mlua-rs/mlua) or a similar rust+lua bindings library to generate a (non executable) type definition file that the lua language server can use to provide LSP features such as autocompletion and type checking.

Lua is inherently dynamically typed, and this type definition file will never actually be _run_ - the comment based type system is only parsed by the LSP when developing. The approach is similar to TypeScript using jsdoc comments and [.d.ts declaration files](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) to augment javascript code with type information.

Uniffi looks great to me for this purpose - I think I could use the procedural macro system and maybe create new external bindings for creating these type annotations. I'm guessing that many things are simpler due to not having to actually run any interoperating code.

If you have the time, I would love to hear if this sounds like a sensible approach. Am I missing some important things that might become an issue? Could there be a better option?

Thanks in advance!

**Comment by mhammond** [comment]
I can't see why that wouldn't work, although it will have costs - for example, UniFFI will generate the Rust side of the FFI, even though there will be zero "foreign" implementations of the FFI. You will also be limited to things UniFFI implements, which seems likely to not perfectly match what mlua supports. At that point you'd probably start to ask why not just lust implement lua uniffi bindings ;)

(I did ponder creating a generic "docs" bindings for uniffi, with the intent being that the output would just be (say) language-agnostic markdown and different languages could just re-use these generic docs. Where that fell apart was the realization that some bindings "rename" the API - eg, Kotlin will transform "some_func()" to "someFunc()" and generic docs couldn't reasonably capture that, so therefore those docs would not be that useful for Kotlin (and similar languages). I'm not sure if Lua has the same considerations.)

**Comment by mikavilpas** [comment]
That sounds pretty good to me! Appreciate the response.

> it will have costs - for example, UniFFI will generate the Rust side of the FFI, even though there will be zero "foreign" implementations of the FFI

Do you mean to say that the cost is increased binary size and additional compilation time? Or are there runtime effects as well?

I'm thinking that if these costs are not acceptable for users, maybe these effects could be turned off using cargo's conditional compilation features such as [cfg_attr](https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg_attr-attribute). That would mean UniFFI support could be "activated" at build time to generate the types, and otherwise it would do nothing.

I have no idea if this could actually work, but I guess it's going to be a fun experiment 🙂 

> (I did ponder creating a generic "docs" bindings for uniffi, with the intent being that the output would just be (say) language-agnostic markdown and different languages could just re-use these generic docs. Where that fell apart was the realization that some bindings "rename" the API - eg, Kotlin will transform "some_func()" to "someFunc()" and generic docs couldn't reasonably capture that, so therefore those docs would not be that useful for Kotlin (and similar languages). I'm not sure if Lua has the same considerations.)

Just to comment on this idea for fun, I think I see what you mean. Having to add support for an identifier/mapping system that's general enough for all possible binding systems sounds like a bad time. Maybe it's also better for all the languages to have them use their own ecosystems' documentation generation tools.

**Comment by mhammond** [comment]
> Do you mean to say that the cost is increased binary size and additional compilation time? Or are there runtime effects as well?

Just the former - although other restrictions will be enforced - eg, if you want to express something supported by mlua but not supported by uniffi (eg, not using an `Arc<>` where uniffi insists you do, not satisfying some trait bound etc, everything will start to fall apart. The trait bounds in particular might be challenging. As noted above, this means you are likely to be limited to the subset of things supported by *both* uniffi and mlua, which might not be satisfactory.

> Maybe it's also better for all the languages to have them use their own ecosystems' documentation generation tools.

Yes, exactly - it's not just the identifier names etc, it's also the conventions etc that each language have, which tend to carry through to other tooling for that language.
