### ISSUE TITLE
Support for projects not using `cargo`

### ISSUE THREAD

**Issue by emarteca** [mozilla/uniffi-rs#2151]
Currently, the `library_mode` `generate_bindings` calls `cargo` to retrieve metadata about the project for which bindings are being generated: e.g. `generate_bindings` starts with [this line](https://github.com/mozilla/uniffi-rs/blob/cd38ccea8236df7d93aff336c325a3a8e524af5d/uniffi_bindgen/src/library_mode.rs#L45):
```
let cargo_metadata = MetadataCommand::new()
        .exec()
        .context("error running cargo metadata")?;
```

This means `uniffi-rs` does not work for projects that use a different build system, where `cargo` is not available and/or where the project is missing a `Cargo.toml` file.

It would be nice if `uniffi-rs` was generalized to not be reliant on `cargo`.

**Comment by mhammond** [comment]
Hopefully fixed by #2175
