### ISSUE TITLE
Using proc-macros for constructor requires Arc<Self>

### ISSUE THREAD

**Issue by parthdt** [mozilla/uniffi-rs#2158]
Hello,

I'm trying to export some rust code to swift using uniffi. For the following snippet:
```
#[derive(uniffi::Record)]
pub struct FzilInput
{
    pub bytes: Vec<u8>
}

#[uniffi::export]
impl FzilInput
{
    #[uniffi::constructor]
        pub const fn new(bytes: Vec<u8>) -> Self {
        Self { bytes }
    }
}
```

`uniffi-bindgen` aborts with error: ` called Result::unwrap() on an Err value: Constructor return type must be Arc<Self>`.

As per [Proc-macro docs](https://mozilla.github.io/uniffi-rs/latest/proc_macro/index.html#the-uniffiexport-attribute), Self should be a valid return type. 

How can this be solved?

**Comment by jplatte** [comment]
You can't export an `impl` block for a record type at all. impl blocks are only supported for object types (at the moment).

**Comment by parthdt** [comment]
Thanks for the response. Exporting the struct as an object does work.

I'm a beginner in both rust, and swift; would you tell me how to use this field: `bytes`, inside swift? Swift requires a `UnsafeMutableRawPointer`, when I try to load a new `[UInt8]` array.

**Comment by mhammond** [comment]
It's difficult to know without seeing your code, but our test at https://github.com/mozilla/uniffi-rs/tree/main/fixtures/coverall has extensive coverage of "bytes", so that can probably point you in the right direction.

**Comment by mhammond** [comment]
It looks like #2159 is handling this bytes request, so I'll close this for now.
