### ISSUE TITLE
Rust pointers can have both even and odd addresses

### ISSUE THREAD

**Issue by mgeisler** [mozilla/uniffi-rs#2165]
The documentation seems to imply that pointers always have an even address (aligned to 2 bytes):
 
https://github.com/mozilla/uniffi-rs/blob/cd38ccea8236df7d93aff336c325a3a8e524af5d/uniffi_core/src/ffi/handle.rs#L14-L15

However, this is [not necessarily true](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=81edc92b4aba101a52601805ed7a1e94):

```rust
    let a: [u8; 3] = [10, 20, 30];
    dbg!(&a);
    dbg!(&a[0] as *const u8);
    dbg!(&a[1] as *const u8);
    dbg!(&a[2] as *const u8);
```

gives me

```
[src/main.rs:4:5] &a[0] as *const u8 = 0x00007ffd556a28f5
[src/main.rs:5:5] &a[1] as *const u8 = 0x00007ffd556a28f6
[src/main.rs:6:5] &a[2] as *const u8 = 0x00007ffd556a28f7
```

which has both odd and even pointers. So if I run this safe code, I will have violated this invariant:

```
Handle::from_pointer(&a[2])
```

When I tried the same with `Box::into_raw`, I did indeed only end up with pointers to even addresses. I don't know if I was just lucky or if there is some underlying reason why the comment is true specifically for leaked `Box` values?

Cc @badboy.

**Comment by badboy** [comment]
> When I tried the same with `Box::into_raw`, I did indeed only end up with pointers to even addresses. I don't know if I was just lucky or if there is some underlying reason why the comment is true specifically for leaked `Box` values?

Basically: Alignment. In our code those handles are from an Arc and are thus aligned to 8 bytes.
There's only 2 calls to `Handle::from_pointer`, both passing in the return of `Arc::into_raw`.

Using `Handle` in a different way is indeed problematic. At the very least the comment should make this more clear, maybe we can add checks or safety comments though.

**Comment by mgeisler** [comment]
I hope #2170 will clarify this a bit.

**Comment by jplatte** [comment]
I think actually UniFFI is relying on undocumented things here. Sure, the `Arc` itself must contain a pointer and be aligned the same way as a pointer, but that does not mean that the data that pointer points to is aligned the same way.

I suspect that the current `Arc` implementation in `std` always returns pointers whose adress is a multiple of 8 for a different reason: The `Arc` "payload" consists of a pointer-sized integer for the refcount and the actual data, in one place in memory. This struct's alignment is always at least as big as that of a pointer. Alternative implementations of refcounted pointers are possible (IIRC C++ mandates that `shared_ptr` impls keep the refcount and data in separate allocations), though it seems extremely unlikely that `std` would ever change. Still, it's worth keeping in mind.
