### ISSUE TITLE
Structs which `#[uniffi::export]` the impl of a trait should have that reflected in the bindings.

### ISSUE THREAD

**Issue by praveenperera** [mozilla/uniffi-rs#2169]
I have the following trait

```rust
use crate::impl_default_for;

#[uniffi::export(with_foreign)]
pub trait AutoComplete: Send + Sync + std::fmt::Debug + 'static {
    fn autocomplete(&self, word: String) -> Vec<String>;
}

#[derive(Debug, Copy, Clone, uniffi::Object)]
pub struct Bip39AutoComplete;


#[uniffi::export]
impl Bip39AutoComplete {
    #[uniffi::constructor]
    pub fn new() -> Self {
        Self
    }
}

#[uniffi::export]
impl AutoComplete for Bip39AutoComplete {
    fn autocomplete(&self, word: String) -> Vec<String> {
        // todo: implement
        vec![]
    }
}
```

And this SwiftUI component 

```swift
struct AutocompleteField<AutoCompleter: AutoComplete>: View {
    let autocompleter: AutoCompleter
    @Binding var text: String

   ...
```

But I can't automatically pass in `Bip39AutoComplete` into the SwiftUI component. To get it to work I have to do the following on the swift side.

```swift
extension Bip39AutoComplete: AutoComplete {}
```

It's not a big deal, just one line, but I was wondering if it could be added to the already generated code as below:

```diff
- open class Bip39AutoComplete: Bip39AutoCompleteProtocol {
+ open class Bip39AutoComplete: Bip39AutoCompleteProtocol, AutoComplete {
```

**Comment by praveenperera** [comment]
In android I can do this

```kotlin
open class Bip39AutoComplete : org.bitcoinppl.cove.Bip39AutoComplete(), AutoComplete {}
```

Though it probably just makes sense to add them directly to already generated kt file

```diff
open class Bip39AutoComplete :
    Disposable,
    AutoCloseable,
-    Bip39AutoCompleteInterface {
+    Bip39AutoCompleteInterface, AutoComplete {
    constructor(pointer: Pointer) {}
```

**Comment by mhammond** [comment]
This is likely to be tricky for a few reasons - one is capturing the metadata, but the other is mapping the semantics to all supported bindings once we end up with many such traits (ie, with multiple inheritance) - eg, Kotlin has a very strange inheritance story.

I wonder if we can instead come up with a way so that the swift binding generator alone can be told (eg, via uniffi.toml) about the desired hierarchy or similar?) But regardless, I don't see an easy answer here.
