### ISSUE TITLE
[Swift] Would it be possible to use checked exceptions?

### ISSUE THREAD

**Issue by LBeernaertProton** [mozilla/uniffi-rs#2179]
Is there any blocker currently that prevents uniffi from using checked exception in the generated binding code for swift?

**Comment by linabutler** [comment]
Hi @LBeernaertProton!

Could you please say a bit more about what you mean by “using checked exceptions”? 😊 UniFFI does generate throwing Swift functions for methods and functions that are annotated with `[Throws]` in the UDL, and you can use `[Error]` interfaces to define the different error variants that you expect.

You can see an example of this in `arithmetic`. [Here](https://github.com/mozilla/uniffi-rs/blob/c5da61baf98d421f2da521b1ab085f576695178d/examples/arithmetic/src/arithmetic.udl) is its UDL, and [here](https://github.com/mozilla/uniffi-rs/blob/c5da61baf98d421f2da521b1ab085f576695178d/examples/arithmetic/tests/bindings/test_arithmetic.swift) is how it’s called from Swift.

Maybe I’m misunderstanding what you’re asking, though?

Please let us know!

**Comment by LBeernaertProton** [comment]
Hey @linabutler , what I meant is the the swift bindings that throw errors are not using  checked exception notations [which are supported by the language](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/errorhandling/#Specifying-the-Error-Type).

E.g.: This rust function
```
#[uniffi::export]
fn foo_bar() -> Result<(), MyError>
```

Is translated into:
```
func fooBar() throws;
```

What I would like to see:

```
func fooBar() throws (MyError);
```

I was wondering if there is currently anything preventing anyone from adding this to the generated bindings?

**Comment by linabutler** [comment]
Ahh, I'm so sorry, I didn't realize you were talking about [typed throws](https://github.com/swiftlang/swift-evolution/blob/9c9461048411d697807ea4dc1f3dcead714192d6/proposals/0413-typed-throws.md)!

> I was wondering if there is currently anything preventing anyone from adding this to the generated bindings?

I did some digging, and it looks like typed throws aren't actually shipping in any Swift release just yet! The documentation page you linked to is a little ahead of the game 😅

The latest release of Swift is [5.10.1](https://www.swift.org/install/macos/#latest-release-swift-5101), but SE-0413 is only available in [the Swift 6 development snapshots](https://github.com/swiftlang/swift/commit/baaa8f3e5b8c4aad16264faf15415b72991e8b44). Digging a bit more, swiftlang/swift#74449 says:

> The implementation of this experimental feature is not complete and it's not ready to be enabled in production. This experimental feature only gates the source-breaking parts of [SE-0413](https://swiftlang.github.io/swift-evolution/#?proposal=SE-0413): Typed throws, which will not be enabled by default in the Swift 6 language mode.

...So they might not be ready for the Swift 6 release, and it'll be a while before we can adopt them in the UniFFI bindings.

**Comment by LBeernaertProton** [comment]
Oh, sorry about that, I did not realize that this was not properly supported in the current version of swift.

Thanks for you time.

**Comment by Sajjon** [comment]
@linabutler Hey! I might do a UniFFI PR later this fall when Xcode 16 GM is released - and with it Swift 6 - in which we can add a new config to `uniffi.toml` for Swift bindings. Perhaps `experimental_typed_throws`, like `experimental_sendable_value_types` I added in https://github.com/mozilla/uniffi-rs/pull/2045, what do you think? In the generated Swift bindings we can use:

We can simply use `#if swift >= 6.0` and generate binding code conditionally so it works pre Swift 6.0.

**Comment by linabutler** [comment]
Sounds great to me, @Sajjon—thank you! 🏆
