### ISSUE TITLE
Only invoke cargo metadata for desired targets

### ISSUE THREAD

**Issue by alex-pinkus** [mozilla/uniffi-rs#2183]
(Based on a similar issue: https://github.com/bbqsrc/cargo-ndk/issues/83)

Unlike most other cargo tools, cargo metadata counter-intuitively defaults to including all targets. This means that when running with `--library`, `uniffi` ends up processing (and thus downloading dependencies for) all targets, many of which are likely to be unsupported by the `cdylib` that the user pointed the CLI at. Specifically, the `MetadataCommand` invocation here is broader than it needs to be:
https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/library_mode.rs#L45-L47

If the user passes a `--crate`, `uniffi` would ideally skip the `MetadataCommand` entirely, as the `--help` message implies it does. Without `--crate`, perhaps `uniffi` could either attempt to infer the target of the `cdylib` (maybe a bad idea) or accept a new parameter for `--target` that scopes down the command.

**Comment by mhammond** [comment]
https://github.com/mozilla/uniffi-rs/pull/2175 is touching all of that - but doesn't address this. All it actually ends up needing is the source directory of the other uniffi crates you use. Thanks for the link!

**Comment by mhammond** [comment]
Thanks - that PR should address this right? That `cargo_metadata` feature landed too, and disabling that will "just work" in many scenarios - I'd love to hear if it does for you.

**Comment by alex-pinkus** [comment]
Yes -- adding `no_deps()` addresses my use case perfectly! Thank you!

I think that `no_deps()` is the optimal solution for my needs, but since you asked -- in order to solve by turning off the new `cargo_metadata` feature I would have _also_ needed the external override you [mention here](https://github.com/mozilla/uniffi-rs/blob/3c6521a7891ed7a38024d8f2856a9a1be7ed6ccb/uniffi_bindgen/src/library_mode.rs#L145).

My use case is roughly that my build runs in a sandboxed environments where `cargo` runs as normal but some, but not all, crates from `crates.io` are made available. It is common in this environment to fetch crate information only for the actual dependencies of the intended package on the intended target. This means that as far as `cargo` is aware, during my build, the only packages that exist are the ones that my build infrastructure has already determined are necessary for my build. In this environment, I still need to be able to locate the crate _somehow_, but I need to do so without examining the universe of dependencies.

**Comment by skeet70** [comment]
@alex-pinkus `no_deps` was a breaking change in `uniffi-bindgen-java`, I'm working on making it a CLI option, but I'm curious if your usecase would be fixed if [`cargo metadata --offilne`](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html#manifest-options) was exposed?

**Comment by alex-pinkus** [comment]
I think that `--offline` would just fail in a different way, because it would determine that a package dependency exists from the metadata that it has, but it would believe that it needs network to resolve it. Making this a CLI option is probably the best path forward if we cannot always use `no_deps`.

Concretely, today this fails when I build on Mac or Linux because of a dependency (call it `crate_a`) that has a Windows-specific dependency that I cannot download (call it `crate_b`). As long as we have already downloaded metadata for `crate_a`, `cargo` will be aware of the dependency on `crate_b`, and will thus try to fetch and fail to fetch it regardless of platform for default-configured calls to `cargo metadata`.

**Comment by mhammond** [comment]
See #2201 - the default has moved back so fetching all deps, but the cli implementation of the bindgen command now takes a new option which can avoid fetching these deps.

**Comment by alex-pinkus** [comment]
That’s great! Thank you!
