### ISSUE TITLE
Change introduced in v0.28.1 breaks cargo-swift 

### ISSUE THREAD

**Issue by tszymczyszyn-shopify** [mozilla/uniffi-rs#2216]
Looks like v0.28.1 altered the signature of `uniffi_bindgen::library_mode::generate_bindings` which breaks `cargo-swift@0.8.0`. More information in https://github.com/antoniusnaumann/cargo-swift/issues/64. Not sure what is the versioning policy for `uniffi-rs`, but this is unexpected.

**Comment by mhammond** [comment]
damn - sorry about that, we shouldn't have made that change in a dot release.

**Comment by mklnz** [comment]
Wow took me so long to figure it out since it it just spit out the error `No path known to UDL files for 'math'`, I couldn't get the tutorial working until I downgraded to 0.28.0

**Comment by tszymczyszyn-shopify** [comment]
[`cargo-swift` 0.8.1](https://crates.io/crates/cargo-swift/0.8.1) fixes the problem, so I think this issue can be closed.
