### ISSUE TITLE
Export callback interface as a struct property

### ISSUE THREAD

**Issue by SoloJiang** [mozilla/uniffi-rs#2221]
```rust
#[uniffi]
pub struct UploadFileOption {
  pub file_path: String,
  pub on_progress: Box<dyn UploadFileCallbackRef>,
}

#[uniffi::export(callback_interface)]
pub trait UploadFileCallbackRef: Send + Sync {
  fn on_progress(&self, progress: f32);
}
```

How to pass option like this, that can pass a callback as a struct property

**Comment by mhammond** [comment]
See https://mozilla.github.io/uniffi-rs/latest/udl/callback_interfaces.html - callbacks are deprecated and can't be used here. You need to use `Arc<dyn ...>`
