### ISSUE TITLE
Cleaner implementation still requiring Android API 33

### ISSUE THREAD

**Issue by rschulman** [mozilla/uniffi-rs#2226]
Despite adding some API version checks in #1997, I'm still getting an API version lint error:

```
Error: Call requires API level 33 (current min is 24): java.lang.ref.Cleaner#create [NewApi]
      val cleaner = java.lang.ref.Cleaner.create()
```

(This is [here](https://github.com/mozilla/uniffi-rs/blob/74c065a6ddb98320a1abe1155fd52db5677ca6ea/uniffi_bindgen/src/bindings/kotlin/templates/ObjectCleanerHelperJvm.kt#L15) in the templates).

I'm running uniffi-bindgen version `0.28.1` and have `android_cleaner = false` in my config.

**Comment by mhammond** [comment]
See also #2128

**Comment by rschulman** [comment]
Hm, yes, that may well be related, though I'll add for your reference (since you raised it in a comment in that thread) that the project I'm working on is 100% Kotlin, so this doesn't seem to be a purely Java problem.
