### ISSUE TITLE
Support HUAWEI HarmonyOS system

### ISSUE THREAD

**Issue by liuqingdada** [mozilla/uniffi-rs#2232]
As we all know, Huawei's mobile phone operating system has gradually taken shape, and Rust has supported the toolchain compilation of Huawei's mobile phone operating system. So can uniffi-rs support Huawei's mobile phone operating system? Thank you very much!

**Comment by mhammond** [comment]
I'm not sure what that means exactly - generally UniFFI doesn't have specific OS support but instead relies on both Rust and the foreign language support for an OS.

Can you please help us understand what support for that would look like?
