### ISSUE TITLE
Why is the `cli` feature required for all tagets

### ISSUE THREAD

**Issue by thunderbiscuit** [mozilla/uniffi-rs#2237]
Hi there!

I'm wondering why the 
```toml
[features]
default = ["uniffi/cli"]
```

must be turned on for all targets rather than simply applied to the `[build-dependencies]`. A project I work on has decided to instead add a separate binary crate to the project for the cli in case the compiler doesn't do a good optimization job and risk increasing binary size. 

Is that an issue? Is there a reason why the cli feature cannot simply be used on the build dependencies?

**Comment by mhammond** [comment]
I don't understand the question - you say it "must be turned on" but I'm not sure what you mean.

**Comment by thunderbiscuit** [comment]
I apologize I think this is a misunderstanding on my part. I was enabling the feature for all blocks using uniffi ([dependencies], [dev-dependencies], and [build-dependencies]) but it's only required when running the uniffi-bindgen binary.

Thanks!
