### ISSUE TITLE
Android app crash

### ISSUE THREAD

**Issue by Alphapage** [mozilla/uniffi-rs#2238]
Hello,

I followed this tutorial to build an android app using uniffi and kotlin:
https://forgen.tech/en/blog/post/building-an-android-app-with-rust-using-uniffi

The app is always crashing: I use the latest uniff, latest rust 1.81, latest gradle jna, api 7 min and debug in api 30 emulator.

What I am missing ?

For info, the same tutorial for ios is working perfectly.

Thank you in advance for your help.

**Comment by badboy** [comment]
Can you provide more information about the crash?
Android Studio or `adb logcat` might give you a stacktrace.

Only with that we'll really be able to help you.
