### ISSUE TITLE
Indication that Swift file is autogenerated

### ISSUE THREAD

**Issue by ianthetechie** [mozilla/uniffi-rs#2256]
It just occurred to me when reviewing a PR for an open-source project built on UniFFI that the autogenerated Swift bindings don't have a big warning at the top saying they are auto-generated. While I think it's obvious, including a warning comment at the top is probably a good idea.

**Comment by ianthetechie** [comment]
Actually, maybe I'm just doing something dumb in my build scripts... I see the comment at the top of wrapper.swift in here, but my generated file doesn't include it.

Command I'm running (where $1 is the library name; ferrostar in this case):

```shell
cargo run -p uniffi-bindgen generate --library target/aarch64-apple-ios/release/lib$1.dylib --language swift --out-dir target/uniffi-xcframework-staging
```

But the generated Swift file starts out like this 🤔 

```swift
// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ferrostarFFI)
    import ferrostarFFI
#endif
```

I'm not running any other commands in-between. The bindgen crate is the minimal one consisting of one line of code that runs `uniffi_bindgen_main`. Bindgen crate: https://github.com/stadiamaps/ferrostar/tree/main/common/uniffi-bindgen. UniFFI version 0.28.1.

**Comment by mhammond** [comment]
Mine all start with
```
// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation
```


// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(coverallFFI)
import coverallFFI
#endif

fileprivate extension RustBuffer {

**Comment by ianthetechie** [comment]
In case anyone has the same issue, it wasn't UniFFI's fault, but rather `swiftformat` deleting the comment among its extensive rewrites 😂 For now, we just disabled swiftformat on the autogenerated code.
