### ISSUE TITLE
uniffi::Record + Box

### ISSUE THREAD

**Issue by pronebird** [mozilla/uniffi-rs#2277]
Hi,

I have a struct that simply holds a really fat field (struct) inside, clippy suggests to Box it, so that's what I do but then `uniffi::Record` cannot really infer `Box<T>` and errors with:

```
the trait bound `Box<Recipient>: Lower<UniFfiTag>` is not satisfied
the following other types implement trait `Lower<UT>`
```

What's the least painful way to handle that given that `Recipient` is a type coming from external crate?

**Comment by pronebird** [comment]
Kind of answering my own Q. Basically the following breaks because the macro does not handle `<` or `>` in type name, i.e:

```rs
uniffi::custom_type!(Box<Recipient>, String);
```

So the solution is to type alias it:

```rs
pub type BoxedRecepient = Box<Recipient>;
uniffi::custom_type!(BoxedRecepient, String);
```

Then implement `crate::UniffiCustomTypeConverter` as usual i.e: 

```
impl crate::UniffiCustomTypeConverter for BoxedRecepient {
type Builtin = String;

    fn into_custom(val: Self::Builtin) -> uniffi::Result<Self> {
        todo!()
    }

    fn from_custom(obj: Self) -> Self::Builtin {
        todo!()
    }
}
```

**Comment by mhammond** [comment]
Custom types are intended to introduce a new type for use by the foreign bindings. In `uniffi::custom_type!(Box<Recipient>, String);` that type is `Box<Recipient>`, which doesn't make sense as a type in UniFFI, just like `Box<i32>` doesn't. Creating the type alias (or alternatively a wrapper) is exactly the correct thing to do, as it is the alias that's available in the bindings.
