### ISSUE TITLE
[Bug] Unresolved reference: uniffiClonePointer and Type mismatch: inferred type is uniffi.core.Structure but com.sun.jna.Structure was expected

### ISSUE THREAD

**Issue by cyanic-selkie** [mozilla/uniffi-rs#2283]
Hi,

I built my rust library for kotlin/android. When I build my project, I get the following errors:

`Type mismatch: inferred type is uniffi.core.Structure but com.sun.jna.Structure was expected`

and 

`Unresolved reference: uniffiClonePointer`

Both of these come from this piece of code:

```kt
/**
 * @suppress
 */
public object FfiConverterTypeStructure: FfiConverter<Structure, Pointer> {

    override fun lower(value: Structure): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): Structure {
        return Structure(value)
    }

    override fun read(buf: ByteBuffer): Structure {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: Structure) = 8UL

    override fun write(value: Structure, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}
```

As a quick and dirty workaround, I simply deleted this entire object and everything works fine.

**Comment by badboy** [comment]
Please always include your UDL/Rust code, otherwise it's impossible to understand what caused this.
I assume you named one of your types `Structure`?

**Comment by cyanic-selkie** [comment]
Right, sorry. The generic `Structure` name made me think it was an internal thing, I completely forgot I named one of my structs that. Renaming fixed the issue.
