### ISSUE TITLE
uniffi should pass String arguments as `&str`

### ISSUE THREAD

**Issue by eoger** [mozilla/uniffi-rs#229]
Right now uniffi will call Rust using owned strings, which isn't super idiomatic, we should special case this and pass `&str` instead.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1647)

**Comment by rfk** [comment]
We do have support for a `[ByRef]` annotation in the IDL, which passes references instead of owned values. I haven't tried it, but if you make the string arguments in the IDL use `[ByRef]` does it get closer to an idiomatic experience?

**Comment by eoger** [comment]
This works!

**Comment by eoger** [comment]
(Note that we should probably add this as an example)

**Comment by rfk** [comment]
Yes, or at least some documentation :-)

We could also consider whether it would make sense to have this as the *default* behaviour for certain data types, and require an explicit annotation if you want an owned value.
