### ISSUE TITLE
Is it possible to exclude some methods of an `impl` block when using `#[uniffi::export]`?

### ISSUE THREAD

**Issue by cyanic-selkie** [mozilla/uniffi-rs#2309]
Basically, I am looking for something like the code below. I find myself having to write methods outside of an object that I don't want to expose. This is particularly annoying when the methods deal with complex types in arguments/return values that I have no need to make compatible with uniffi. It would also make associated functions possible.

```rust
#[uniffi::export]
impl Deck {
    pub fn a(&self) {
        ...
    }

    #[uniffi::exclude_method]
    pub fn b(&self)  {
        ...
    }
}
```

**Comment by mhammond** [comment]
You can use multiple impl blocks:

```
#[uniffi::export]
impl Deck {
    pub fn a(&self) {
        ...
    }
}

impl Deck {
    pub fn b(&self)  {
        ...
    }
}
```

**Comment by cyanic-selkie** [comment]
Oh, damn, thanks!
