### ISSUE TITLE
Swift: UniFFI API checksum mismatch

### ISSUE THREAD

**Issue by yukibtc** [mozilla/uniffi-rs#2321]
Hi, adding new CI tests (clean environment, without any cache) for my SDK bindings I noticed this error:

```bash
UniFFI API checksum mismatch: try cleaning and rebuilding your project
```

**This happen ONLY with Swift**, not with Python or Kotlin. You can see the entire workflow [here](https://github.com/rust-nostr/nostr/actions/runs/11900941888/job/33162872412).

I'm using UniFFI `v0.28` with `proc-macros` and `futures`. Any idea on how to fix this? Why does this happen only in Swift and not in Python or Kotlin?

Thanks

**Comment by mhammond** [comment]
It sounds like you might be using stale generated swift code somehow - is it checked in to source control? All the checksum checks are in the generated swift code so you can see what the values are, and whether they change as your interface changes. We have some issues around checksums, but none where the checksum is plain wrong.

**Comment by yukibtc** [comment]
Sorry for late reply. I checked manually every single checksum and I think found the issue.

I was using this piece of code that causes a different checksum depending on the target:
```rust
#[cfg(all(not(target_os = "android"), not(target_os = "ios")))]
#[uniffi::export]
impl Connection {
    /// Use embedded tor client
    pub fn embedded_tor(&self) -> Self {
        let mut builder = self.clone();
        builder.inner = builder.inner.embedded_tor();
        builder
    }
}

#[cfg(any(target_os = "android", target_os = "ios"))]
#[uniffi::export]
impl Connection {
    /// Use embedded tor client
    pub fn embedded_tor(&self, data_path: String) -> Self {
        let mut builder = self.clone();
        builder.inner = builder.inner.embedded_tor(data_path);
        builder
    }
}
```
