### ISSUE TITLE
Feature Request: Provide  uniffi-bindgen generate for language subcommand

### ISSUE THREAD

**Issue by cavivie** [mozilla/uniffi-rs#2327]
Currently, the following commands are used to generate language-specific bindings:
```shell
uniffi-bindgen generate --language {LANGUAGE} ...

uniffi-bindgen-kotlin ...
uniffi-bindgen-swift ...
uniffi-bindgen-{LANGUAGE} ...
```

As mentioned [here](https://github.com/mozilla/uniffi-rs/pull/2248), different languages ​​may have different variant arguments, so different languages ​​are split out and run as main commands separately, which is a big step forward.

We can go a step further. In addition to providing a separate language as the main command entry, I also hope that the language here can exist in the form of a subcommand, so that all functions can be completed with one binary, and variant arguments related to the language itself can be used:
```shell
uniffi-bindgen generate kotlin ...
uniffi-bindgen generate swift ...
uniffi-bindgen generate {LANGUAGE} ...
```

Is such a feature request acceptable, or is it the goal of the project to accept such a change?

**Comment by mhammond** [comment]
I think we are more likely to head in a different direction, and have each binding be 100% responsible for generating bindings for a given language. This would make things more consistent with external bindings, such as golang or c#. Each language gets it own binding binary.

To put it another way, I think we should stop treating the builtin language as "special".

**Comment by mhammond** [comment]
Yeah, that's correct. Although I guess you could imagine a world where bindings were like git - eg, `uniffi-bindgen generate {LANGUAGE}` was generic and just tried to execute `uniffi-bindgen-language` or similar.

IOW, I think we mainly just want for none of the languages to be "special" - so "swift" and "go" and "js" etc all work as well as each other.
