### ISSUE TITLE
Catch error variant in Kotlin

### ISSUE THREAD

**Issue by weslenng** [mozilla/uniffi-rs#233]
Complementing #215
Putting this here so it doesn't get lost

In Swift and Python we explicitly test that this was the `IntegerOverflow` variant, but in Kotlin we test only that it was an `ArithmeticError`. Does it work if we catch `ArithmeticErrorException.IntegerOverflow` here like the other languages do?

_Originally posted by @rfk in https://github.com/mozilla/uniffi-rs/pull/215#discussion_r468186640_

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1649)

**Comment by tarikeshaq** [comment]
Thanks, @weslenng! Yup, that would work, #231 has an example from the `todolist` tests.

**Comment by weslenng** [comment]
> Thanks, @weslenng! Yup, that would work, #231 has an example from the `todolist` tests.

Ah, I hadn't seen this PR 😅 
I think we don't need this issue anymore
