### ISSUE TITLE
Missing Swift Bindings for Return Type Declared in a Different Crate

### ISSUE THREAD

**Issue by llbartekll** [mozilla/uniffi-rs#2332]
I am using UniFFI to generate Swift bindings for a Rust Client struct. One of its methods, route(), returns a type RouteResponse that is declared in a different crate. However, after generating the Swift bindings, the RouteResponse type is not included in the generated Swift file. As a result, the route() function cannot recognize the type it is supposed to return.

Here’s the declaration of the RouteResponse type in the other crate:

```rust
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "uniffi", derive(uniffi_macros::Enum))]
#[serde(untagged)]
pub enum RouteResponse {
    Success(RouteResponseSuccess),
    Error(RouteResponseError),
}
```

In my current crate (Client implementation), I am using pub use to re-export the type:

```rust
pub use x::y::route::RouteResponse;

#[uniffi::export(async_runtime = "tokio")]
impl Client {
    #[uniffi::constructor]
    pub fn new(project_id: String) -> Self {
        let client = Client::new(ProjectId::from(project_id.clone()));
        Self { project_id, client }
    }

    pub async fn route(
        &self,
        transaction: InitTransaction,
    ) -> Result<RouteResponse, Error> {
        let ca_transaction = CATransaction::from(transaction);
        self.client
            .route(ca_transaction)
            .await
            .map_err(|e| Error::General(e.to_string()))
    }
}
```

i generate bindings with this command:
```
  cargo run --features uniffi/cli --bin uniffi-bindgen generate \
      --library target/aarch64-apple-ios/release/lib$1.dylib \
      --language swift \
      --crate $1 \
      --out-dir target/uniffi-xcframework-staging
   ```

**Comment by mhammond** [comment]
I believe the problem is --crate (and tbh, I'm really not sure why that option exists) - we'd expect 2 .swift files to be generated with `RouteResponse` in one and `Client` in the other, with references across them. --crate tells uniffi to only generate one of the .swift files.

**Comment by llbartekll** [comment]
@mhammond thanks for your response. that's correct when I remove --crate, two files will be generated. ant the other one contains missing file but then I have around 200 errors of type `Invalid redeclaration ...`. they overlap in idk 70%?

**Comment by mhammond** [comment]
It depends on what actually overlaps as to whether that's a problem - it's expected for things like `RustBuffer` declarations etc, but not for stuff actually exposed by uniffi.

I don't know much about swift, but we do have examples of swift code sharing stuff between crates (eg, https://github.com/mozilla/uniffi-rs/tree/main/fixtures/ext-types/lib), but is it possible the problem is how you are invoking swift? IIUC, it should be invoked once, with all generated .swift and a single .h file specified.

**Comment by llbartekll** [comment]
the problem was that I've had same names for structs in two crates in rust and after generating bindings those names of structs in swift were conflicting.

thanks for your help
