### ISSUE TITLE
`MethodTooLargeException` runtime error when executing Android tests for our Kotlin artifact

### ISSUE THREAD

**Issue by Sajjon** [mozilla/uniffi-rs#2340]
I recently started getting `MethodTooLargeException` errors, e.g.

```
jdk.internal.org.objectweb.asm.MethodTooLargeException: Method too large: jdk/proxy3/$Proxy28.<clinit> ()V
	at java.base/jdk.internal.org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2118)
	at java.base/jdk.internal.org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:527)
	at java.base/java.lang.reflect.ProxyGenerator.generateClassFile(ProxyGenerator.java:506)
	at java.base/java.lang.reflect.ProxyGenerator.generateProxyClass(ProxyGenerator.java:178)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.defineProxyClass(Proxy.java:558)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.build(Proxy.java:670)
	at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:429)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
	at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:427)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1037)
	at com.sun.jna.Native.load(Native.java:624)
	at com.sun.jna.Native.load(Native.java:596)
	at com.radixdlt.sargon.UniffiLib$Companion$INSTANCE$2.invoke(sargon.kt:59715)
	at com.radixdlt.sargon.UniffiLib$Companion$INSTANCE$2.invoke(sargon.kt:1213)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.radixdlt.sargon.UniffiLib$Companion.getINSTANCE$sargon_android_debug(sargon.kt:1213)
	at com.radixdlt.sargon.SargonKt.newAccessControllerAddressSampleMainnet(sargon.kt:50684)
	at com.radixdlt.sargon.samples.AccessControllerAddressSampleMainnet.invoke(AccessControllerAddressSample.kt:16)
	at com.radixdlt.sargon.samples.AccessControllerAddressSampleMainnet.invoke(AccessControllerAddressSample.kt:12)
	at com.radixdlt.sargon.SampleTestable$DefaultImpls.testEquality(SampleTestable.kt:15)
	at com.radixdlt.sargon.AccessControllerAddressTest.testEquality(AccessControllerAddressTest.kt:15)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

I've never had this issue before. I got it when working on a fairly large addition to our UniFFI layer in [this PR](https://github.com/radixdlt/sargon/pull/286)

I've added some `#[derive(uniffi::Object)]` builders which contain some `RwLock` state. 

I'm unable to understand why I got hit with this, if it is because the size of our whole Kotlin artifact or if it relates to implementation (disregarding other code).

The mention `com.radixdlt.sargon.samples.AccessControllerAddressSampleMainnet` mentioned packages in the stack trace is a **red herring**, those types have not changed! Which makes me thing that we get hit by this because of size of or artifact?

I'm surprised first of all that no one else have had this issue? Or at least if I search for it in issues here on GH there are no results. 

Any help whatsoever what be greatly appreciated!

**Comment by CyonAlexRDX** [comment]
Update, we _**think**_ we know the issue, we believe the issue to be that UniFFI generates a too big

```kotlin
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
```

method. Ours is 3484 lines, 251kb, which seems to be too large for `JDK`? 

I'm gonna try to manually split it and re-run our Kotlin JVM tests and see if it works.

**Comment by Sajjon** [comment]
(Sorry for switching between private and work Github handlers. Im switching between work computer and personal sometimes)

Confirmed that it is **both** the `uniffiCheckApiChecksums` **and** the `interface UniffiLib: Library {}` causing this.

I first started by splitting the huge `uniffiCheckApiChecksums` into "batches" - then retried running our JVM Kotlin tests on my Apple Silicon mac and it also failed.

Then  I **also** commented out four methods in the `interface UniffiLib` and any reference to those four methods and tried again; It now worked!!

So I tried reverting the `uniffiCheckApiChecksums` split change and kept the change to `interface UniffiLib` which resulted in the same error! 

Now ofc I do need those four commented out methods... so hmm so maybe I can "hack around" the limitation on number of methods on an interface? I'm gonna try:

```kotlin
interface UniffiLibPart1: Library {
 // half of all methods go here
}
interface UniffiLibPart2: UniffiLibPart1 {
// second half of all methods go here
}
interface UniffiLib: UniffiLibPart1 {}
```

**Comment by Sajjon** [comment]
@bendk @mhammond or do you have any other suggestions ? Any contributor here in UniFFI lib who's great at JDK/Kotlin stuff?

(I can barely write hello world in Kotlin)

**Comment by Sajjon** [comment]
I shall mentioned that we are still on UniFFI `0.27.1`:

```toml
uniffi = { git = "https://github.com/mozilla/uniffi-rs/", rev = "6f33088e8100a2ea9586c8c3ecf98ab51d5aba62", features = [
  "cli",
] }
```

I might try to bump to latest and see if anything has changed.

**Comment by Sajjon** [comment]
I think it is unlikely that Sargon is the biggest UniFFI using project in the world? Sure it is a pretty big project - but surely some Mozilla projects must be bigger.

So I guess Sargon is the biggest UniFFI using **crate**, and that is why we are first with hitting this JDK issue - and Mozilla (or any other) is not hit (yet) since Mozilla uses multi-crate setup?

I might try yet again the multi-crate setup now that we have @bendk s uniffi-bindgen swift change.

But I would like to understand if I can try some other JDK version to see if it works? Or hmm, Im really out of my depth here with this JDK stuff... I guess I need to know if UniFFI imposes some JDK version? Or if I can try upgrading locally on my machine and UniFFI will use/respect that? Or is that up to `cargo ndk`?? You see! Im completely lost. @mhammond can you perhaps ask internally at Mozilla if anyone can help me with that question?

**Comment by mhammond** [comment]
> So I guess Sargon is the biggest UniFFI using **crate**, and that is why we are first with hitting this JDK issue - and Mozilla (or any other) is not hit (yet) since Mozilla uses multi-crate setup?

Exactly - we have many small(-ish) crates.

Re the jdk version, uniffi doesn't have any opinion there. I'm not sure what "cargo ndk" is, but we don't use it IIUC. Updating to a new jdk should be fine - it looks like we are currently on jdk 17 (which seems early, so I'm not 100% sure what we actually release with, but that's what I seem to have locally)

**Comment by mhammond** [comment]
> So I will soon create a PR, let me know if you want me to gate it behind a UniFFI build flag `experimental_split_large_kotlin_libraries` or similar!

I suspect the devil will be in the detail, but if the PR makes uniffi work where it otherwise would not, then there would be no need for a feature flag.

> It is probably easiest to express in terms of number of methods.

eg, this is where the devil will live :) I suspect that the number of methods might indicate that "maybe there's a problem around here, although some objects with many fewer might trigger it, and some objects with many more might be fine" - which probably wouldn't be an actual fix.

Maybe the other solution is "don't do that - just use multiple crates"?

**Comment by Sajjon** [comment]
Fixed in https://github.com/mozilla/uniffi-rs/pull/2344

**Comment by Thoralf-M** [comment]
Hello, we now [hit](https://github.com/iotaledger/iota-rust-sdk/actions/runs/19564185422/job/56022346796?pr=421) the already extended limit in our [SDK](https://github.com/iotaledger/iota-rust-sdk) and are wondering what's the best way forward. In https://github.com/mozilla/uniffi-rs/pull/2344#issuecomment-2531718612 it was mentioned that one should use multiple crates. However this doesn't seem to work right now if I didn't miss something.
I duplicated our SDK to see if we can split things up and use them from the different packages, but this results in an error:
```kotlin
import iota_sdk.generateMnemonic
import iota_sdk2.MnemonicLength as MnemonicLength2
import kotlin.io.println

fun main() {
    val mnemonic = generateMnemonic(null)
    println("24 word mnemonic from iota_sdk: $mnemonic")
    val mnemonic12 = generateMnemonic(MnemonicLength2.WORDS12)
    println("12 word mnemonic from iota_sdk: $mnemonic12")
}
```
```
> Task :compileKotlin FAILED
e: file:///home/t/Desktop/iota-rust-sdk/bindings/kotlin/examples/TestCombination.kt:11:39 Argument type mismatch: actual type is 'iota_sdk2.MnemonicLength', but 'iota_sdk.MnemonicLength?' was expected.
```
In this test everything is just duplicated, but how could one even have an interface where the type doesn't need to be defined in the same package? In this case `iota_sdk.MnemonicLength`.

Also what speaks against splitting the uniffi interface more than twice? Or is there another alternative that works right now?
Any advice would be appreciated

**Comment by bendk** [comment]
Sorry you're hitting this limit.  In the short term, I think you can make things work by splitting into 3 crates: one for common types like `MnemonicLength`, then then two others for the functionality that uses those types.  If you're using proc-macros it should all work pretty seamlessly, but see https://mozilla.github.io/uniffi-rs/latest/types/remote_ext_types.html for details.

Over the next few months I'm going to be experimenting with updating the Kotlin FFI.  The work is mostly motivated by performance and also crashes with the current code, but I think this issue should also be fixed as a side effect.
