### ISSUE TITLE
Ensure destructors use ExternError and is panic safe.

### ISSUE THREAD

**Issue by jhugman** [mozilla/uniffi-rs#236]
Following #220, we see that destructors no longer work with the

```
uniffi::deps::ffi_support::define_handle_map_deleter!({{ handle_map }}, {{ ffi_free.name() }});
```

This needs to happen after #221 is landed.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1654)

**Comment by linacambridge** [comment]
I think this done already, right? It looks like the destructors and allocators take a `RustError` now and catch panics...
