### ISSUE TITLE
Swift bindings only work in tests

### ISSUE THREAD

**Issue by eoger** [mozilla/uniffi-rs#237]
Specifically we include the `import uniffi_{{ ci.namespace() }}` statement at the beginning of these bindings, which I think is there because in tests we compile the Swift code into `libuniffi_{namespace}.dylib` to be able to be used into the Swift REPL. 
In regular production contexts the headers are included in the project and this statement causes a hard error.
@linacambridge I saw you worked on this, does what I describe makes sense?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1655)

**Comment by linacambridge** [comment]
Ah, yep, that makes perfect sense! I guess in a regular project we're compiling all the symbols into a giant static library, and the Swift bindings are compiled into that, so we don't need an `import` at all?

**Comment by eoger** [comment]
Yup that library doesn't exist :)

**Comment by rfk** [comment]
Is this a similarly-shaped problem to the kotlin megazord issue, except that in this case the megazord is statically compiled into the application itself?

**Comment by tarikeshaq** [comment]
FWIW the first iteration of the Nimbus SDK is for Fenix, so if this appears to be a tough one I wouldn't mind removing the `blocks-nimbus` tag.

(Not that I have any idea of the difficulty here)

**Comment by eoger** [comment]
Ah yes that's fair, I guess I wanted to mark it as pretty important as the Swift bindings are un-usable till we resolve this.

**Comment by jhugman** [comment]
It'd be good to get an example project showing this working. I have not yet been able to get it to work yet.


It's not clear if we can persuade xcodebuild/swiftc to work with both these build types with zero differences in the generated code.


Should we be introducing switches (e.g. command line args) or detect from Cargo.toml?


More generally, should uniffi make it easier to deploy the modules e.g. via carthage.
