### ISSUE TITLE
Richer error types

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/uniffi-rs#245]
Right now we only allow for error enums that have a flat structure. This is okay for a simple project, but we often want to report some dynamic information (what was the network error? what was the db error? etc).

 Currently, we have no good way of doing that, except requiring the consumer to define more errors.

This is also related to enums overall since they have the same limitation, but the specific error use case seems more important.

Thoughts? \cc @eoger @rfk @linacambridge

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1666)

**Comment by linacambridge** [comment]
This is a great point @tarikeshaq, thanks for bringing it up!

Just to make sure I understand: in a hypothetical example, if an HTTP error occurs, the caller might want to unpack it and figure out how to respond...a 503 might just mean "oops, don't do anything and try again later", but, say, a 401 means something's wrong and the application should make some noise. Right now, we have to either define special `Error` variants (`Http503`, `Http401`) for each type of failure, or encode what went wrong into the string.

Is that right?

I wonder if WebIDL unions could help us out here. Basically, something like this for the error definition:

```webidl
typedef (NetworkError or DatabaseError or BadExperimentError) Error;
```

And use `enum`s for the specific error kinds:

```webidl
enum NetworkError {
    "Http503",
    "Http401"
};

enum DatabaseError {
    "DiskImageMalformed",
    "ForeignKeyConstraintFailed",
    "NoSuchTable",
    "SyntaxError"
};

enum BadExperimentError {
    "EmptyName",
    "NoSuchExperiment",
    "InvalidCharacterInName"
};
```

That still means we need to write `impl From<rusqlite::Error> for DatabaseError`, `impl From<viaduct::Error> for NetworkError` in the Rust library...are you thinking we can autogenerate these, too, or were you mainly wanting to pass different kinds of errors without smooshing everything into one `enum`?

**Comment by tarikeshaq** [comment]
Thanks @linacambridge! My main concern is what if we want to report a dynamic error message that may not be explicitly defined in the error as a variant.

Lemme clarify, `viaduct::Error` has a variant `NetworkError(String)`, and that `String` could be useful to log/report. But we don't allow our error variants to have associative types so that `String` would get lost. 

One way is to force all the error enums to have a `String` associated type as a message. Changing the limitation from "only flat errors" to "only string associative errors". 
```rust
#[derive(Debug, thiserror::Error)]
enum NimbusError {
  #[error("Network error: {0}")]
  NetworkError(String),
  #[error("Database error: {0}")]
  DbError(String),
}
```

This allows us to encode the `.to_string()` of any errors we depend on dynamically. So in our library

```rust
impl From<viaduct::Error> for NimbusError {
   fn from(cause: viaduct::Error> -> Self {
          NimbusError::NetworkError(cause.to_string())
  }
}

impl From<rustqlite::Error> for NimbusError {
   fn from(cause: rustqlite::Error> -> Self {
          NimbusError::DBError(cause.to_string())
  }
}
```

Probably not the nicest way, and am very open to any ideas

**Comment by linacambridge** [comment]
Ohhhh that makes a lot of sense! Hahaha sorry I completely missed the point, I get it now! 😅
