### ISSUE TITLE
What to do when no constructor is specified in the IDL?

### ISSUE THREAD

**Issue by jhugman** [mozilla/uniffi-rs#246]
If no constructors are given in the IDL, uniffi fails. 

This issue is for tracking discussion for what we should do in this case. For developer ergonomics, I would suggest defaulting to a noarg default constructor.

Found as part of #175 but may be fixed during #37.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1667)

**Comment by rfk** [comment]
> For developer ergonomics, I would suggest defaulting to a noarg default constructor.

This makes a lot of sense to me FWIW 👍
