### ISSUE TITLE
Publish uniffi crates to crates.io

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/uniffi-rs#253]
It might be a good time to publish the `0.1` versions of our crates to crates.io if we think we are okay with the structure of our crates (i.e having a `uniffi`, a `uniffi_bindgen` and a `uniffi_build` crates.)

This is relevant because in https://github.com/mozilla/nimbus-sdk/pull/15 I'm adding the integration of Nimbus with `uniffi` and it would be nicer to point to a version on crates.io 😄 I'm also happy to point it to a specific commit if we think we're better of waiting on publishing.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1698)

**Comment by rfk** [comment]
I have no particular objection to publishing to crates.io, and I agree it's probably worthwhile. We should probably make sure we're all on the same page about how version numbers will be managed (and exactly what constitutes a breaking change).

**Comment by rfk** [comment]
We might also consider whether there's a ~~Matix~~ Element chat channel we'd include in the public-facing description, for adventurous third parties who find the crate and want to try it out.

**Comment by rfk** [comment]
Whelp, we're live for the world to see! 😬 

* https://crates.io/crates/uniffi_bindgen
* https://crates.io/crates/uniffi_build
* https://crates.io/crates/uniffi_macros
* https://crates.io/crates/uniffi
