### ISSUE TITLE
Allow setting the package name in the generated kotlin file

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/uniffi-rs#258]
Right now the generated kotlin file has the package name `uniffi.{name_of_lib}`. It is useful for Nimbus though if it was possible to override that.

This is useful because at https://github.com/mozilla/nimbus-sdk/pull/18 we publish the generated code directly.

The generated package name is set here https://github.com/mozilla/uniffi-rs/blob/a23fd65e1777c8274c80feab139b906442cdb02e/uniffi_bindgen/src/bindings/kotlin/gen_kotlin.rs#L21

There are a couple of options, one being having the package name in the idl, the other being having it as a parameter to `uniffi-bindgen`. Since the package name may not be relevant to all the languages, we may prefer the latter option

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1722)

**Comment by eoger** [comment]
We could do something similar to protobufs with `kotlin_package` `swift_package` etc directives in the idl file.

**Comment by weslenng** [comment]
There's a directive in WebIDL for project name or something like that?

**Comment by rfk** [comment]
I'm not aware of anything in WebIDL that would be a good fit for this, but we could make something up, similar to how we currently abuse the `namespace` declaration.

Maybe we could use extended attributes on the `namespace`, something like:

```
[KotlinPackage=foobar]
namespace nimbus {};
```

It'll probably feel a bit ugly, but would suffice for our short-term needs.

(Longer-term I am lightly -1 on including language-specific config options like this in the interface definition, but I think we should consider that as part of a broader survey of how the whole IDL thing is working out for us)

**Comment by jhugman** [comment]
FWIW: I'd favour language specific config options ending up in a separate file, though ambivalent to the format of that file.

**Comment by weslenng** [comment]
I was looking in the WebIDL documentation for something that would fit this feature, but I didn't find anything 😕

> FWIW: I'd favour language specific config options ending up in a separate file, though ambivalent to the format of that file.

Seems a lot better, but how this file could be structured?

**Comment by jhugman** [comment]
> Seems a lot better, but how this file could be structured?

I was thinking a first cut would be a `.toml` file, either as part of `Cargo.toml` or as a separate file. c.f. [`askama.toml`][1]

[1]: https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/askama.toml

**Comment by rfk** [comment]
May or may not be a good fit for us, but I did just now learn that `Cargo.toml` reserves a special namespace for use by external packaging tools, the [metadata table](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table).
