### ISSUE TITLE
Generated Kotlin uses experimental unsigned types

### ISSUE THREAD

**Issue by travis79** [mozilla/uniffi-rs#259]
I just noticed this while building the nimbus-sdk kotlin bindings added by Tarik. We get a lot of warnings about using [experimental unsigned types](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-experimental-unsigned-types/) without using the annotation saying "we know we are".

The warning:
`This declaration is experimental and its usage should be marked with '@kotlin.ExperimentalUnsignedTypes' or '@OptIn(kotlin.ExperimentalUnsignedTypes::class)'`

This may come up as an issue if used in a project that has warnings as errors enabled.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1730)

**Comment by rfk** [comment]
Further, the [nimus IDL](https://github.com/mozilla/nimbus-sdk/blob/main/experiments/src/nimbus.idl) doesn't appear to actually use any unsigned types, so I guess we're using them only for some internal machinery of uniffi.

**Comment by jhugman** [comment]
Although nimbus IDL doesn't use unsigned types, `RustBufferHelper` provides facilities that manipulate unsigned types. We don't propagate the annotations, but require [a compiler flag][1].

```sh
-Xopt-in=kotlin.ExperimentalUnsignedTypes
```

This issue could be de-scoped down to a documentation issue, or only generating `lift` and `lower` methods for types we actually use in the IDL.

[1]: https://github.com/mozilla/uniffi-rs/blob/686a8ec672cb6b86a6de920c43ff2d5678afd84a/uniffi_bindgen/src/bindings/kotlin/mod.rs#L70

**Comment by rfk** [comment]
> We get a lot of warnings about using experimental unsigned types without using the annotation saying "we know we are".

Oh wow, yeah. I just tried building nimbus-sdk myself "a lot of warnings" here means *53* warning lines.

>  or only generating lift and lower methods for types we actually use in the IDL.

I have some work along these lines already, so I think it's my preferred option. Something like:

* Change some of our internal machinery to use signed types, for e.g. the length of a string when serialized.
* Only general helper functions for types that we use in the IDL
* Annotate the helpers for types involving unsigned integers with `@ExperimentalUnsignedTypes` to propagate the opt-in requirement.

IIUC this would give a reasonable consumer experience:

* If the interface doesn't use any unsigned types, the consumer doesn't have to know or care about them at all.
* If the interface does use unsigned types, the consumer needs to explicitly opt in to the unstable feature.

**Comment by jhugman** [comment]
> * Change some of our internal machinery to use signed types, for e.g. the length of a string when serialized.
> * Only general helper functions for types that we use in the IDL

I think this would go a long way to making the propagating annotations workable. I'm still not sold on the benefits of propagating annotations over a kotlinc compiler flag however.
