### ISSUE TITLE
Split `ViaFfi` trait into `IntoFfi` and `TryFromFfi`

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/uniffi-rs#26]
This is based on the discussion in https://github.com/rfk/uniffi-rs/pull/22#discussion_r456967989.

This would entail the following: 

- Take a look at the `ViaFfi` trait in https://github.com/rfk/uniffi-rs/blob/e35bbac8880b61de1ef9a73e736d4f6b7933244e/uniffi/src/support/mod.rs#L105-L122
- Split it into two traits, 
  - an IntoFfi trait that requires the  `fn into_ffi_value(self) -> Self::Value;` function
  - a TryFromFfi trait that requires the `fn try_from_ffi_value(v: Self::Value) -> Result<Self>;` function
- Make the changes neccesary to make it build and pass the tests, those include:
  - Modifying the macro that generates the traits for primative types: https://github.com/rfk/uniffi-rs/blob/main/uniffi/src/support/mod.rs#L124
  - Splitting each impl for `ViaFfi` into two separate impls, one for `IntoFfi` and one for `TryFromFfi`, you will notice that you only need to implement TryFromFfi for &str (And not `IntoFfi`) and only need to implement `IntoFfi` for String (And not `TryFromFfi`) - Note: The string stuff only applies if #25 merges before you do this
  - Look around for uses of ViaFfi (example: https://github.com/rfk/uniffi-rs/blob/main/uniffi/src/scaffolding.rs#L58) and replace it with the appropriate trait (for lifting you'll use TryFromFfi, and for lowering you'll use IntoFfi)
  - Do some magic until it builds and tests pass! ✨ 

I might have missed something, \cc @rfk I think this is a `good-first-issue` kind of issue, so feel free to add any details 😄

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1560)

**Comment by rfk** [comment]
> I might have missed something, 

I think you nailed it 👍 

> an IntoFfi trait that requires the fn into_ffi_value(self) -> Self::Value; function

It's worth noting that this would essentially be identical to the [`IntoFfi` trait provided by our existing ffi-support crate](https://docs.rs/ffi-support/0.4.0/ffi_support/trait.IntoFfi.html). We could consider just importing and using the one from that crate rather than making our own...but on the other hand, it's nice to have a trait that we directly control in order to support easy refactoring, and we could aim to ~~uniffi~~ unify the two implementations at a later date.

**Comment by rfk** [comment]
If we decide we like the refactoring in https://github.com/mozilla/uniffi-rs/pull/192, we may decide we don't need to do this after all.

**Comment by tarikeshaq** [comment]
Ya, I don't think we need to this anymore (at least for the time being) since #192 removed the asymmetry with Strings.

I'll close it for now, and if in the future more asymmetry shows up we can deal with it then 😄
