### ISSUE TITLE
Figure out optional arguments with defaults

### ISSUE THREAD

**Issue by jhugman** [mozilla/uniffi-rs#263]
This is similar to the [issue about optional properties in records][1], namely that of default values in optional arguments in function definitions.

There are several times fxa_client uses optional/defaulted arguments.

```idl
ProfileInfo get_profile(optional boolean ignore_cache=false);
string authorize_oauth_code(string client_id, sequence<string> scopes, string state, optional string access_type = "online");
AccessTokenInfo get_access_token(string scope, optional u32 ttl);
```

This is a strawfox proposal implementing them in uniffi to use caller language features to implement them.

```kotlin
pub fun getProfile(ignoreCache: Boolean = false): ProfileInfo =
    callWithHandle { UNIFFI_STRAWFOX_FirefoxAccount_get_profile(it, ignoreCache.lower()) }
    let { ProfileInfo.lift(it) }
```

Note the `= false` default in the method declaration.

Reasons to like this: 

 * documented in the caller language.
 * generated code is very simple

Reason to not like this: 

 * the default value is not contained in rust, but in the IDL file itself.

For reference, in the hand written bindings for `ttl`, [`get_access_token`][2] effectively implemented an `Option<u32>`; the defaulting happened in the rust.

This might be desirable, especially when the bindings are handwritten and hard to keep in sync.

Looking for more experienced rust devs for thoughts: @eoger @linacambridge @rfk ?

[1]: 188
[2]: https://github.com/mozilla/application-services/pull/2896

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1743)

**Comment by rfk** [comment]
I really like having the default be obvious in the foreign-language bindings, where possible.

> the default value is not contained in rust, but in the IDL file itself.

This seems fine to me short-term.

Longer term, I'm thinking about what things will look like if/when we switch away from a separate IDL file and start using a more macro-based approach. We could *probably* figure out a way to annotate the rust code with defaults via a macro in a way that's similar to how it's done in the IDL. So...I don't think this should be a blocker for us doing something that is simple and works in the IDL.

The rust code can assume that a value will be provided explicitly, and we can treat the default values as a convenience for the foreign-language consumers.

**Comment by jhugman** [comment]
Thanks, @rfk. 

> We could _probably_ figure out a way to annotate the rust code with defaults via a macro in a way that's similar to how it's done in the IDL.

This is what I was hoping.
