### ISSUE TITLE
Remove mentions of “bridging header” from the Swift bindings

### ISSUE THREAD

**Issue by linacambridge** [mozilla/uniffi-rs#266]
The Swift backend generates a header file with C declarations for all the FFI symbols. `Template-Bridging-Header.h` serves the same purpose as `NamespaceLibraryTemplate.py` and `NamespaceLibraryTemplate.kt`. The Swift compiler uses that header file to generate FFI function declarations (it knows where to look for the header thanks to the `.modulemap`), and expose them to Swift.

But the term “bridging header” means something veeeery specific in Cocoa-land, and I’m pretty sure that’s not what this is 😅 So let’s rename `Template-Bridging-Header.h` to just `NamespaceLibraryTemplate.h` to match the other backends, and scrub all mentions of “bridging header” from the comments to avoid confusion.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-17)
┆Issue Number: UNIFFI-17

**Comment by rfk** [comment]
Oh hey, I did this accidentally over in #984!
