### ISSUE TITLE
Prototype bindings for Firefox Desktop platform (C++) consumers

### ISSUE THREAD

**Issue by linacambridge** [mozilla/uniffi-rs#269]
Once we have our ADR for platform consumers (#268), we’ll want to make a prototype. I don’t have many details to add here yet, since we don’t know how we’ll approach this—that’s what the ADR is for! 😁

I think we can reuse the core of #255. The `RustBuffer` serialization machinery is going to be useful here as well, except instead of serializing WebIDL-specific types like `mozilla::dom::Nullable`, `dom::Record`, and `dom::Sequence`, we can serialize `mozilla::Maybe`, `mozilla::HashMap`, and `nsTArray`, respectively. We’ll also need to generate some code for exposing functions, records, and objects to C++, too, like we do for Swift, Kotlin, and Python.

Good news: because we’re only generating a C++ API, and not any IDLs, I suspect we can land this in Desktop quicker than whatever we do for JS.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-18)
┆Issue Number: UNIFFI-18

**Comment by linacambridge** [comment]
Let's leave this open, but backburner it for now. Kate and Ana would like to focus on front-end experiments first, and figure out a story for platform later. Since the Nimbus team doesn't have any platform consumers yet, we'd be on the hook for maintaining Nimbus, the C++ bindings, _and_ the actual experiments themselves, which doesn't feel like the right thing.

#285 was helpful for figuring out how a pure-C++ API would look, but it's not worth our time to push on that since Nimbus doesn't need it right away.

**Comment by rfk** [comment]
Closing old Gecko issues and consolidating them under https://github.com/mozilla/uniffi-rs/issues/991
