### ISSUE TITLE
Technical review for generated Desktop bindings (JS and C++)

### ISSUE THREAD

**Issue by linacambridge** [mozilla/uniffi-rs#270]
This ticket covers reviewing the ADRs and implementations to make sure we’re being good Firefox Desktop citizens, since none of us are experts in Gecko platform work. We’ve reached out to @nnethercote (hi Nick! 😄) to help us with that.

I expect the reviews to be folded into the other work, but filing this as its own ticket for completeness.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-19)
┆Issue Number: UNIFFI-19

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Leaving unassigned as this will be work done by an external team. Lina will keep track of this throughout the sprint.

**Comment by linacambridge** [comment]
The review packet so far:

* An ADR for [front-end bindings](https://docs.google.com/document/d/1XVBvjt52EKgaaAflMDqUGXQy2AK3sufgEFIu1ZjWbqw), via WebIDL, XPIDL, `js-ctypes`, or Wasm.
* An ADR for C++ [platform bindings](https://docs.google.com/document/d/1kaVliEaNzhLthudBmWSJnmbyC70P0AQqNGE_4K0HYmI).
* A [prototype for front-end](https://github.com/mozilla/uniffi-rs/pull/255) bindings.

**Comment by nnethercote** [comment]
I've looked over the three parts of the review packet. Overall it looks good. The C++ proposal is straightforward. The JS proposal is still gnarly but that is unavoidable. I put some additional comments are in the Google Docs and the PR.

**Comment by linacambridge** [comment]
Thanks, @nnethercote! To close this issue out, I think we'll want to:

* Update the ADR to reflect that we're going with Option C for now. We can always revisit later.
* Bring #255 up to date with Nick's feedback, and get it reviewed and landed.
* Convert the Google Doc ADRs to Markdown, and move them into this repo.

After that's done:

* https://github.com/mozilla/application-services/issues/3571. Copy that ticket into a new Bugzilla bug and make a Phabricator patch to build the Rust Nimbus SDK and the generated bindings in Desktop. These can be Nightly-only to start with.
* Figure out the testing story. Start with a Nimbus xpcshell test, and maybe build a more elaborate testing strategy for generated bindings later (mozilla/uniffi-rs#272).

**Comment by rfk** [comment]
Clearing out some issues that we're not actively working on; I'm going to consolidate context on the Gecko bindings into a single new issue at https://github.com/mozilla/uniffi-rs/issues/991
