### ISSUE TITLE
Integrate binding generation into mach for Desktop

### ISSUE THREAD

**Issue by linacambridge** [mozilla/uniffi-rs#274]
For the prototype, we can just run `uniffi-bindgen gecko` manually, then check in the generated code into m-c. But it would be even cooler if we could wire it up to `mach`, so that the bindings get generated automatically as part of the Firefox build process. The end goal is to be able to just add the Rust component as a dependency to Desktop, and run `mach build`.

The Glean team was already [looking into this](https://bugzilla.mozilla.org/show_bug.cgi?id=1654840) for FOG. There’s some complexity around running a Rust executable at build time in Firefox because distros in that thread, but it sounds like all the scaffolding is there.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-21)
┆Issue Number: UNIFFI-21

**Comment by data-sync-user** [comment]
➤ Lina Cambridge commented:

Putting this in the Icebox, since we can work around it easily enough by checking in the build artifacts ourselves.

**Comment by rfk** [comment]
Clearing out some issues that we're not actively working on; I'm going to consolidate context on the Gecko bindings into a single new issue at https://github.com/mozilla/uniffi-rs/issues/991
