### ISSUE TITLE
Nimbus-SDK is unable to format generated nimbus.kt file due to not being found

### ISSUE THREAD

**Issue by travis79** [mozilla/uniffi-rs#287]
The specific error I'm seeing is: 
```
> Task :generateDebugUniffiBindings
Warning: Unable to auto-format nimbus.kt using ktlint: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
`uniffi-bindgen` is being [invoked from the nimbus-sdk build.gradle](https://github.com/mozilla/nimbus-sdk/blob/dc1e209cdbdc45d50e82164cacbd27a980f89643/android/build.gradle#L148) file, but I suspect that due to the way java structures "packages" as folder structure, that it's not looking into the additional folders. In this case `/build/generated/source/uniffi/debug/java` is what is being passed to uniffi-bindgen as the `--out-dir`, but the actual nimbus.kt file is ending up at `/build/generated/source/uniffi/debug/java/uniffi/nimbus/nimbus.kt`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1782)

**Comment by eoger** [comment]
Do you have `ktlint` available in your path? The warning could also refer to the executable not being found.

**Comment by travis79** [comment]
Aha! No ktlint in my path.  That does appear to be my problem. Thanks!
