### ISSUE TITLE
Rename `Serializable` to `ViaFFIUsingByteBuffer` in the Swift bindings

### ISSUE THREAD

**Issue by linacambridge** [mozilla/uniffi-rs#29]
..And `Primitive` to `ViaFFI`.

Even though they're not quite the same, the comment already says they're pretty analogous, and it would be nice to have that bit of symmetry—especially with #26 splitting up `ViaFFI` into `IntoFFI` and `TryFromFFI`.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1557)

**Comment by linacambridge** [comment]
[Here's](https://github.com/rfk/uniffi-rs/blob/e35bbac8880b61de1ef9a73e736d4f6b7933244e/uniffi/src/bindings/swift/templates/RustBufferHelper.swift#L112-L128) where they're defined now. This bug is about renaming the two protocols, and the other helpers that reference them.

**Comment by rfk** [comment]
This is (kinda) tackled in as part of #241
