### ISSUE TITLE
[Proposal] Use Default::default instead of Self::new for constructors

### ISSUE THREAD

**Issue by eoger** [mozilla/uniffi-rs#292]
I think it would make more sense to require the `Default` trait to be implemented for IDL constructors instead of requiring a "magic" pseudo-standard `fn new() -> Self` constructor.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-22)
┆Issue Number: UNIFFI-22

**Comment by rfk** [comment]
IIUC this would only support constructors with no arguments, would we keep the `new` convention for constructors with arguments?

**Comment by eoger** [comment]
Do we support these? For some reason I assume we did not. Nevertheless, I'd support a `[name="<ctor name>"]` attribute for these.

**Comment by linacambridge** [comment]
I really like your idea of falling back to `Default` for constructors with no arguments, and adding a `[Name]` attribute for secondary constructors that take arguments!

Could we do that without requiring `Default` to be implemented for the struct (only requiring it if you actually declare `constructor()` in the IDL, but not if you just do `[Name=“new”] constructor(string someArg, u8 somethingElse)`?)

**Comment by eoger** [comment]
> Could we do that without requiring `Default` to be implemented for the struct (only requiring it if you actually declare `constructor()` in the IDL, but not if you just do `[Name=“new”] constructor(string someArg, u8 somethingElse)`?)

Yup that makes a lot of sense to me!

**Comment by eoger** [comment]
We could also allow users to declare a `[Name=“new”] constructor()` (no argument ctor) without requiring them to implement `Default`.

**Comment by rfk** [comment]
I think our constructor stuff is in OK shape, let's close this out.
