### ISSUE TITLE
Change `.idl` extension to `.udl`

### ISSUE THREAD

**Issue by linacambridge** [mozilla/uniffi-rs#293]
Firefox uses the `.idl` extension for XPIDL, and `.webidl` for WebIDL. UniFFI IDL uses WebIDL syntax, but not the semantics...and the `.idl` extension. Dan suggested changing the extension to `.uidl` to help clarify that it's our own dialect of WebIDL that we're using, not "standard" WebIDL and definitely not XPIDL.

WDYT?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1795)

**Comment by linacambridge** [comment]
If you pronounce "UIDL" as "oo-ee-dl", it sounds like `weedle`, which is the [Rust WebIDL parser](https://crates.io/crates/weedle) that we use! 😁👍🏻

**Comment by rfk** [comment]
I support it 👍 

(Mentally, I am going to associate it with these [super classy pre-mixed vodka drinks called UDLs](https://www.danmurphys.com.au/search?searchTerm=udl), so I'll have to try really hard to remember the "I" is in there; but I can live with that...)

**Comment by linacambridge** [comment]
Or we could go with `.udl`, we're fancy, too! 🍸🥤

**Comment by jhugman** [comment]
I support this message. 👍 

Does this mean we can rule out supporting `DOMString`?

**Comment by linacambridge** [comment]
> Does this mean we can rule out supporting `DOMString`?

I _think_ so! Making sure I understand, though, by supporting `DOMString`, did you mean switching from `string` to `DOMString`, or something else?

**Comment by linacambridge** [comment]
Oh, for completeness, I wanted to capture some of the differences between UDL and ["standard" WebIDL](https://heycam.github.io/webidl/). Some of these are described in a comment in the Gecko JS backend, but it might be helpful to capture them in prose, too:

* UDL has the following aliases for numeric types: `u8`, `i8`, `u16`, `i16`, `u32`, `i32`, `u64`, `i64`, `f32`, `f64`. WebIDL calls these `octet`, `byte`, `unsigned short`, `short`, `unsigned long`, `long`, `unsigned long long`, `float`, `double`.
* UDL doesn't support [`unrestricted float`](https://heycam.github.io/webidl/#idl-unrestricted-float) or [`unrestricted double`](https://heycam.github.io/webidl/#idl-unrestricted-double).
* UDL only supports `boolean`, integer, floating-point, `sequence<T>`, and `record<string, T>` types. It does _not_ support promises, array buffers or views, frozen arrays, symbols, [`any`](https://heycam.github.io/webidl/#idl-any), or [union types](https://heycam.github.io/webidl/#dfn-union-type) (`(X or Y or Z)`).
* UDL supports `typedef`s like WebIDL, but they [cannot have attributes](https://heycam.github.io/webidl/#idl-annotated-types).
* UDL has just one string type, `string`—a UTF-8 encoded string, just like Rust's `std::string::String` type. WebIDL has three: [`DOMString`](https://heycam.github.io/webidl/#idl-DOMString) (a "wide" string of unspecified encoding, where each character is 16 bits; most likely UTF-16), [`ByteString`](https://heycam.github.io/webidl/#idl-ByteString) (a "narrow string" of unspecified encoding, where each character is 8 bits. For example, UTF-8, Latin-1...), and [`USVString`](https://heycam.github.io/webidl/#idl-USVString) (unspecified encoding, but guaranteed to be valid—for example, no unpaired surrogates).
* In UDL, all `dictionary` members are required by default. In WebIDL, they're optional by default, unless prefixed with the `required` keyword.
* In UDL, any argument can specify a default value. In WebIDL, such arguments must be prefixed with the `optional` keyword.

**Comment by rfk** [comment]
While we're considering changes to the developer-facing API surface, we should also think about https://github.com/mozilla/uniffi-rs/issues/304 and how we want to handle locating the uniffi config file relative to the interface definition file (or vice-versa).

**Comment by jhugman** [comment]
>> Does this mean we can rule out supporting `DOMString`?

> Making sure I understand, though, by supporting `DOMString`, did you mean switching from `string` to `DOMString`, or something else?

> UDL has just one string type, string—a UTF-8 encoded string, just like Rust's `std::string::String` type. WebIDL has three

Rust and each of our target foreign languages has one commonly used string type each, and everything supports UTF-8.

Supporting UTF-16 and unspecified encoded strings would require quite a lot of machinery which I don't think would often be used.

**Comment by linacambridge** [comment]
> Supporting UTF-16 and unspecified encoded strings would require quite a lot of machinery which I don't think would often be used.

Oh, I see what you mean! I totally agree with you—we absolutely don't need to support `DOMString` or any of the other WebIDL string types in UDL; `string` is perfect.

I'd even go a bit further and suggest that we not pursue unification 😎 of UDL and WebIDL now, if at all. Even though we're borrowing its syntax, its semantics don't quite fit our use case, and something like two-thirds of the stuff in the WebIDL standard doesn't really apply to us.

**Comment by rfk** [comment]
> I'd even go a bit further and suggest that we not pursue unification 😎 of UDL and WebIDL now, if at all.

+1; IMHO there are many things in WebIDL that are awkward for our needs.
