### ISSUE TITLE
Ensure enum variants with hyphens are reflected correctly in generated Gecko JS bindings

### ISSUE THREAD

**Issue by linacambridge** [mozilla/uniffi-rs#294]
For example, `enum PlacesEventType { "bookmark-added" }` gets translated to `PlacesEventType::Bookmark_added` by Firefox's `Codegen.py`.

Since UniFFI doesn't generate declarations for enums and dictionaries (`Codegen.py` takes care of that; the only thing UniFFI does generate for these are `Serializable` and `ViaFfi` specializations), we should make sure `filters::enum_variant_cpp` reflects them correctly. Right now, I think it'll drop the hyphen and convert them to `BookmarkAdded`, which is wrong, but I'm not sure.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-23)
┆Issue Number: UNIFFI-23

**Comment by rfk** [comment]
Clearing out some issues that we're not actively working on; I'm going to consolidate context on the Gecko bindings into a single new issue at https://github.com/mozilla/uniffi-rs/issues/991
