### ISSUE TITLE
Improve errors in the Gecko JS backend

### ISSUE THREAD

**Issue by linacambridge** [mozilla/uniffi-rs#295]
The Gecko JS backend _can_ throw errors now, but it's hecka janky.

First, everything is an `OperationError` (it seemed to be the best-fitting DOM exception type that we have in Gecko). Second, there's a big `panic!("TODO")` for translating `Error` enums, and the error type is discarded completely—only the message is thrown. This makes it hard to pattern match on thrown errors; you currently need to inspect the message.

Fixing this is a little involved. The way Firefox's WebIDL bindings work, any method that throws gets a `[Throws]` attribute. Unlike in UniFFI IDL, there's no way to specify the type of error that gets thrown. The C++ binding then gets an `ErrorResult& aRv` argument, which it uses to throw exceptions. The set of DOM exceptions that can be thrown is [hard-coded here](https://searchfox.org/mozilla-central/rev/89d33e1c3b0a57a9377b4815c2f4b58d933b7c32/dom/bindings/DOMExceptionNames.h), and that list gets translated by [this macro](https://searchfox.org/mozilla-central/rev/89d33e1c3b0a57a9377b4815c2f4b58d933b7c32/dom/bindings/ErrorResult.h#370-384) into a method on the `ErrorResult`. I think the guidance for web-exposed WebIDL interfaces is to throw a limited set of built-in generic exceptions, like `AbortError`, `InvalidStateError`, etc., which is kind of at odds with how we're using them.

Another way to do this might be to create a JS exception object, and make the `ErrorResult` throw that. I _think_ `JS::CreateError` is the right API to use—[here's an example of how one of those is created](https://searchfox.org/mozilla-central/rev/89d33e1c3b0a57a9377b4815c2f4b58d933b7c32/dom/base/ChromeUtils.cpp#1184-1197). So I think you'd call `aRv.MightThrowJSException()`, then create the `ErrorObject` like in that link, and then call `aRv.ThrowJSException(cx, err);`. This is all guesswork, though; I might be barking completely up the wrong tree here.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-24)
┆Issue Number: UNIFFI-24

**Comment by rfk** [comment]
Clearing out some issues that we're not actively working on; I'm going to consolidate context on the Gecko bindings into a single new issue at https://github.com/mozilla/uniffi-rs/issues/991
