### ISSUE TITLE
Decide how to handle blocking I/O in the Gecko JS backend

### ISSUE THREAD

**Issue by linacambridge** [mozilla/uniffi-rs#298]
Our Rust code is written in a blocking style (please check out #12 for the rationale behind that decision), and all bindings for our other languages—Kotlin, Swift, Python, and Gecko C++—just call the functions directly, and leave threading up to the consumer. So if a Rust function blocks on I/O or a network request, so will the calling code.

This lets consumers be flexible. Kotlin can use coroutines (green threads), Swift can use dispatch queues, Python can use an `asyncio.ThreadPoolExecutor` or Twisted's `deferToThread`, and so on. Objects exposed over the FFI are safe to use from multiple threads—the `ConcurrentHandleMap` on the Rust side guarantees that—but the threading strategy lives in the consumer, not the Rust code or FFI layer.

Gecko JS throws a wrench in this, because there's no way for Firefox JS code to spawn a thread directly. The closest we have to threading is `ChromeWorker`, which is a web `Worker` created from privileged code. Like web workers, chrome workers do not share memory—JS code must use messaging passing to communicate between the worker and main thread. Abstractions like `PromiseWorker` exist, to post messages to a worker and return a promise for a reply, but there's still the serialization and cognitive overhead of having to write two scripts (the main-thread JSM and the worker) to use a Rust component. And it means consumers need to be diligent about always calling blocking methods on the background thread.

On the C++ side, dispatching blocking calls to a background thread is easier. There are two functions that can help with this: [`NS_CreateBackgroundTaskQueue`](https://searchfox.org/mozilla-central/rev/0eebca3c33b7999bfd090672e6c6dde96ae89616/xpcom/threads/nsThreadUtils.h#1776-1783) creates a background task queue, which is an `nsISerialEventTarget` that accepts `Runnable`s and runs them on a background thread pool. It's a FIFO queue, so runnables run in the order they're submitted. [`NS_DispatchBackgroundTask`](https://searchfox.org/mozilla-central/rev/0eebca3c33b7999bfd090672e6c6dde96ae89616/xpcom/threads/nsThreadUtils.h#1756-1774) runs a one-shot background task, without creating a queue. And [`NS_NewRunnableFunction`](https://searchfox.org/mozilla-central/rev/0eebca3c33b7999bfd090672e6c6dde96ae89616/xpcom/threads/nsThreadUtils.h#666-673) wraps a C++ lambda in a `Runnable`, so you don't have to write boilerplate to subclass `mozilla::Runnable` yourself.

So maybe one solution is to:

* Add a `[MayBlock]` annotation to UniFFI IDL to indicate that a method can do blocking I/O. Other backends could ignore this for now.
* In the Gecko JS backend, make those functions (in the generated WebIDL and in the implementation) return a `Promise<T>` instead of `T`.
* In the generated C++ implementation, fire off a background task to call into the FFI function, then send a runnable back to the main thread to resolve the promise.

[Here](https://searchfox.org/mozilla-central/rev/0eebca3c33b7999bfd090672e6c6dde96ae89616/dom/system/IOUtils.cpp#209-243) is a nice example in the new `IOUtils` module that does just that pattern.

Let's also brainstorm some other ideas here, that's just the one I've thought most about—but that doesn't mean it's the best approach!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-25)
┆Issue Number: UNIFFI-25

**Comment by rfk** [comment]
> Add a [MayBlock] annotation to UniFFI IDL to indicate that a method can do blocking I/O.
> Other backends could ignore this for now.

I like the idea of marking this in the IDL a lot. I agree other languages can probably ignore it to start, but I suspect it'll be worth our while to consolidate best practices for each target language and to make that happen by default. (E.g. to we really expect to have different threading strategies in the Kotlin bindings for different components in practice?).

**Comment by linacambridge** [comment]
> I suspect it'll be worth our while to consolidate best practices for each target language and to make that happen by default.

Yes, this is a great idea! Gecko JS might need it more immediately just because of how it's built, but it can be super useful for other backends, too—and would make it easier for consumers like a-c, so they wouldn't need to [wrap every function](https://github.com/mozilla-mobile/android-components/blob/8514edc9b75afd0318bb2152821d82eb40f3afef/components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/SyncableLoginsStorage.kt) in a coroutine.

**Comment by rfk** [comment]
That a-c code is exactly the sort of I-cant-believe-we-made-a-human-write-that-by-hand-what-a-waste-of-their-time code that I hope to be able to eliminate once we feel like we understand the appropriate best-practices for such things :-)

**Comment by rfk** [comment]
From the meeting today, the solution describe above of annotating blocking methods in the IDL, converting those to promises in the JS bindings, and having a bunch of IOUtils-style infra to run tasks on a background thread sounds like the way forward here. It's not a blocker (heh) just yet, but we will probably need to prioritize this work in the next couple of weeks.

I expect a good way to approach this issue would be to:

* Manually generate the existing (synchronous) bindings for Nimbus, or an example component.
* Tweak the generated files by hand, following the example of what's done in `IOUtils`, to find a workable shape for the resulting generated code.
* Adjust the bindings generator so it spits out something like the hand-written code, but automagically.

**Comment by rfk** [comment]
In a recent meeting, I asked @badboy how blocking I/O was dealt with in Project FOG for Glean. The current approach taken there is broadly similar to what we do in appservices - the rust component is synchronous, and the calling foreign-language code needs to arrange for it to be dispatched to a background thread. IIUC FOG manages its own worker thread that is created at startup.

Interestingly, they're planning to explore a version of this where the threading happens inside of Rust, so that consumers don't need to worry about it. It sounds like this is potentially tractable for Glean because its API is designed to be "write only", so calling code can push data into glean and have it dispatched to a b/g thread, but doesn't have to wait for that dispatch to resolve and return a result.

**Comment by rfk** [comment]
> Add a [MayBlock] annotation to UniFFI IDL to indicate that a method can do blocking I/O.
> Other backends could ignore this for now.

Cross-referencing https://github.com/mozilla/uniffi-rs/issues/12#issuecomment-728534566; Nika pointed out that annotating individual methods to be made asynchronous is a blocking hazard, because every method of an `interface` will currently [synchronize on getting a mutable ref from the handlemap](https://github.com/mozilla/uniffi-rs/blob/4812fc2494d6db6e1800c0da8f7eba69b235451c/uniffi_bindgen/src/templates/macros.rs#L55). If *any* method may block, then *all* methods may block waiting for a concurrent call to one that does.

I think this actually argues in favour of us handling this in the UDL where we can check that we're doing the right thing. For example in the short term, we can make *every* method of an `interface` async if *any* of them are marked as blocking.

**Comment by rfk** [comment]
> Nika pointed out that annotating individual methods to be made asynchronous is a blocking hazard, because every method of an interface will currently synchronize on getting a mutable ref from the handlemap

This is no longer true, we got rid of handlemaps and the implicit blocking therein (ref ADRS 0003, 0004 and 0005).

**Comment by rfk** [comment]
Clearing out some issues that we're not actively working on; I'm going to consolidate context on the Gecko bindings into a single new issue at https://github.com/mozilla/uniffi-rs/issues/991
