### ISSUE TITLE
Running compiled uniffi-bindgen fails due to missing CARGO_MANIFEST_DIR

### ISSUE THREAD

**Issue by rfk** [mozilla/uniffi-rs#304]
If you compile and run the `uniffi-bindgen` tool (as one might when installing via crates.io) then it doesn't seem to be able to generate bindings:

```
$ cargo build -p uniffi_bindgen
...
$ ./target/debug/uniffi-bindgen generate ./examples/rondpoint/src/rondpoint.idl -l kotlin
thread 'main' panicked at 'Missing $CARGO_MANIFEST_DIR, cannot load config file: NotPresent', uniffi_bindgen/src/lib.rs:259:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                           
```

I believe it's expecting to find a `CARGO_MANIFEST_DIR` in the environment as of https://github.com/mozilla/uniffi-rs/pull/273, but this doesn't exist when you're running it as a standalone tool.

Running it via `cargo run` works:

```
$ cargo run -p uniffi_bindgen -- generate ./examples/rondpoint/src/rondpoint.idl -l kotlin
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/uniffi-bindgen generate ./examples/rondpoint/src/rondpoint.idl -l kotlin`
Warning: Unable to auto-format rondpoint.kt using ktlint: Os { code: 2, kind: NotFound, message: "No such file or directory" } 
```

But if I instrument the code with some strategic `println!`s, then I see that it tries to load the config file from `./uniffi_bindgen/uniffi.toml` rather than from `./examples/rondpoint/uniffi.toml`, while I expect users would intend the later.

I think we need to tweak how the tool finds its config file to match how we expect users will run the tool in practice, but I'm not entirely clear on how that should work. One option would be to follow the example [here](https://github.com/mozilla/uniffi-rs/blob/757a028278f8c8d81754e6a32ea3844012669deb/uniffi_bindgen/src/main.rs#L52) where we accept a `--manifest-path` argument, defaulting to a path relative to the idl file.

@jhugman @eoger thoughts?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1808)

**Comment by jhugman** [comment]
Oh, yuck.

Hmm. 

For command line args, the options seem to be:

 * to use a `--manifest-path` or `--manifest-dir` argument, and then derive the `uniffi.toml` file from there.
 * to specify the config file directly with a `--config-file` argument, defaulting  to `uniffi.toml`.

I _think_ I prefer the latter, as it allows multiple idl and toml files to co-exist in the same directory.

> But if I instrument the code with some strategic println!s, then I see that it tries to load the config file from `./uniffi_bindgen/uniffi.toml` rather than from `./examples/rondpoint/uniffi.toml`, while I expect users would intend the later.

For the case of missing arguments, I think searching up the directory tree starting from the directory of `idl` file, ignoring `CARGO_MANIFEST_DIR` altogether.

Aside 1: `manifest`'s help string doesn't make sense to me.

```sh
Path to crate's Cargo.toml. If not provided the IDL file is assumed to be under src/
```

I'm not sure I understand: the manifest is only there for the version check, is derived from the cwd, and has nothing to do with the location of the IDL.

Aside 2: I'd like to get most of these args into the `Config` struct, loading in one place, and pass _that_ around.
