### ISSUE TITLE
Measure the binary size impact for Gecko JS bindings

### ISSUE THREAD

**Issue by linacambridge** [mozilla/uniffi-rs#307]
We'll want to make sure we aren't weighing down the Firefox binary, especially once we start landing UniFFIed components in Desktop. Since there's an additional layer of WebIDL codegen involved during the Firefox build, keep in mind that the more complex the WebIDL method declaration, the bigger the size impact.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-28)
┆Issue Number: UNIFFI-28

**Comment by rfk** [comment]
Clearing out some issues that we're not actively working on; I'm going to consolidate context on the Gecko bindings into a single new issue at https://github.com/mozilla/uniffi-rs/issues/991
