### ISSUE TITLE
Build breakage: Unable to find the uniffi.toml file

### ISSUE THREAD

**Issue by jhugman** [mozilla/uniffi-rs#311]
From 
https://app.circleci.com/pipelines/github/mozilla/uniffi-rs/439/workflows/04600d42-37f4-44fd-8846-4af01ccdc948/jobs/1349

> error: unresolved reference: equal (test_arithmetic.kts:28:9)
error: unresolved reference: equal (test_arithmetic.kts:29:9)
tests/bindings/test_arithmetic.kts:1:12: error: unresolved reference: mozilla
import org.mozilla.uniffi.example.arithmetic.*;
           ^
tests/bindings/test_arithmetic.kts:3:8: error: unresolved reference: add
assert(add(2u, 4u) == 6uL)

This appears to be not finding/loading/repecting the `uniffi.toml` file.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1818)

**Comment by eoger** [comment]
https://github.com/mozilla/uniffi-rs/pull/310 should fix this
