### ISSUE TITLE
Update uniffi to support I/O strategy chosen in #3620

### ISSUE THREAD

**Issue by dmose** [mozilla/uniffi-rs#328]
This is likely to (at the very least) include changing the C++-templated code in the Gecko_JS backend

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-29)
┆Issue Number: UNIFFI-29

**Comment by rfk** [comment]
Clearing out some issues that we're not actively working on; I'm going to consolidate context on the Gecko bindings into a single new issue at https://github.com/mozilla/uniffi-rs/issues/991
