### ISSUE TITLE
Revert struct-padding workaround once upstream bug is fixed in JNA

### ISSUE THREAD

**Issue by rfk** [mozilla/uniffi-rs#334]
The code generated by uniffi makes heavy use of passing structs by value, and this seems to have uncovered an [argument-passing bug in JNA](https://github.com/java-native-access/jna/issues/1259). We landed a workaround for this bug in https://github.com/mozilla/uniffi-rs/pull/335 but it works by artificially padding our structs, so it seems likely to have some runtime performance costs.

(Briefly: it pads our structs to be more than 16 bytes in size, so that they will always be passed as a pointer, which works around the bug).

Once the underlying issue has been resolved in a JNA release, we should revert the above workaround.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-33)
┆Issue Number: UNIFFI-33

**Comment by rfk** [comment]
The latest release of JNA (5.8) has an updated version of `libffi` and appears to have fixed the issue!

**Comment by rfk** [comment]
I believe this bug is now actionable, and could make a good first issue. Basically, we need to:

* Remove the `padding` and `padding2` fields that were added in #335 (there are other cleanups in that PR, so we shouldn't revert the whole thing). This will need to be done in both the Rust definitions, and the various foreign-language bindings.
* Document somewhere in the manual that we require JNA 5.7 or greater; I don't think we have a good place for this yet, but it could go somewhere in the "Kotlin" section.
* Update `docker/Dockerfile-build` to install the newer version of JNA; this won't have any effect on tests passing because we weren't able to repro that crash in CI, but it'll be useful for completeness.

We'll also have to keep a careful eye out for any increase in crashes on Android once the new version rolls out to consumers.

**Comment by badboy** [comment]
I will take a shot at this.

**Comment by rfk** [comment]
sounds good - especially getting your head around the docker image and tests will be valuable as well
