### ISSUE TITLE
JNA workaround struct changes didn't get propagated to C++ templates

### ISSUE THREAD

**Issue by dmose** [mozilla/uniffi-rs#338]
In #335, a workaround for a JNA bug was added by padding out the RustBuffer and ForeignBytes code.  The workaround was propagated to most of the templates (Kotlin, etc), but the not to the C++ code used in the JS bindings.  Patch forthcoming which fixes that.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1872)

**Comment by rfk** [comment]
Sounds like my bad, so I'll happily volunteer for the review here.
