### ISSUE TITLE
Support other Python Formatter

### ISSUE THREAD

**Issue by azzamsa** [mozilla/uniffi-rs#349]
Currently uniffi only support `yapf` https://github.com/mozilla/uniffi-rs/blob/c97e301725b333d18d48bdc46b1d22d4c8140ae1/uniffi_bindgen/src/bindings/python/mod.rs#L36

Is there any aims to support other formatter such as `black`?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-37)
┆Issue Number: UNIFFI-37

**Comment by rfk** [comment]
Thanks for the suggestion. We don't have any short-term need for this ourselves, but I'd be happy to talk through how to implement it and review a PR if anyone feels inspired to contribute such a change. Approaches might include:

* Support a known list of formatters, and try each in turn until we find one that's installed on the system.
* Allow to specify a path to the formatter in `uniffi.toml`.

**Comment by azzamsa** [comment]
Sorry, but I don't use it anymore.
