### ISSUE TITLE
Implement callback interfaces for JS

### ISSUE THREAD

**Issue by jhugman** [mozilla/uniffi-rs#354]
This was #342 ; but now covers just the work in JS.

[Callback interfaces][1]:

```
callback interface Filesystem {
    void write_text(string filepath, string text);
    string read_text(string filepath);
};

namespace my_lib {
    set_filesystem(Filesystem fs);
}
```

[1]: https://heycam.github.io/webidl/#dfn-callback-interface

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-40)
┆Issue Number: UNIFFI-40

**Comment by jhugman** [comment]
@dmose would likely be the best person to estimate.

**Comment by rfk** [comment]
All Gecko/JS issues are being consolidated into https://github.com/mozilla/uniffi-rs/issues/991
