### ISSUE TITLE
clean up and land gecko_js async changes for demo into uniffi

### ISSUE THREAD

**Issue by dmose** [mozilla/uniffi-rs#355]
This is an enhancement in that it makes it possible to generate a simple Nimbus demo that works end-to-end.  The code is written in #350, and needs some cleanup, both according to the comments there, and generally should be reviewed and looked over, particularly for memory leakage as mentioned by @mystor in earlier discussions.  That's probably really a seperate ticket from this, but we'll leave it here for now.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-41)
┆Issue Number: UNIFFI-41

**Comment by rfk** [comment]
Clearing out some issues that we're not actively working on; I'm going to consolidate context on the Gecko bindings into a single new issue at https://github.com/mozilla/uniffi-rs/issues/991
