### ISSUE TITLE
audit threading and locking architecture for code gecko_js code generated by uniffi/Nimbus

### ISSUE THREAD

**Issue by dmose** [mozilla/uniffi-rs#358]
Based on a discussion that @rfk and I had yesterday, there's a bunch of things that we need to confirm and/or decide on in the threading/locking architecture for gecko_js code emitted by uniffi_bindgen.  There will undoubtedly be Nimbus-specific discussion too, but (that majority of?) of any code changes will likely land in the templates here.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-42)
┆Issue Number: UNIFFI-42

**Comment by dmose** [comment]
As a start, I'll be putting together a Google doc and sending it around for feedback.

**Comment by rfk** [comment]
Clearing out some issues that we're not actively working on; I'm going to consolidate context on the Gecko bindings into a single new issue at https://github.com/mozilla/uniffi-rs/issues/991
