### ISSUE TITLE
Land gecko_js async I/O code templates.

### ISSUE THREAD

**Issue by dmose** [mozilla/uniffi-rs#359]
The basic code is already written in #350.  It needs various cleanups and review.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-43)
┆Issue Number: UNIFFI-43

**Comment by rfk** [comment]
Clearing out some issues that we're not actively working on; I'm going to consolidate context on the Gecko bindings into a single new issue at https://github.com/mozilla/uniffi-rs/issues/991
