### ISSUE TITLE
Enum field in dictionary support

### ISSUE THREAD

**Issue by eoger** [mozilla/uniffi-rs#36]
I want to be able to compile this :
```
enum BoboType {
  "TRON",
  "ZORD",
};

dictionary TestMock {
  BoboType name_suffix_variant;
};
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1554)

**Comment by tarikeshaq** [comment]
+1 For `BoboType` 🤣 

I think this is a good first issue! 

To make this possible:
- One would need to implement `Lowerable` and `Liftable` for enum types, the traits can be found [here](https://github.com/mozilla/uniffi-rs/blob/main/uniffi/src/support/mod.rs)
- This could fit nicely in [here](https://github.com/mozilla/uniffi-rs/blob/main/uniffi/src/templates/EnumTemplate.rs)
- Probably do the lifting and lowering **very** similar to how `ViaFfi` is implemented on the above file

**Comment by rfk** [comment]
> One would need to implement Lowerable and Liftable for enum types

Right, and in practice, these could probably just call `into_ffi_value`/`try_from_ffi_value` to convert to a `u32` and then read/write it directly in the buffer.
