### ISSUE TITLE
RustError leak, for (at least) gecko_js bindings

### ISSUE THREAD

**Issue by dmose** [mozilla/uniffi-rs#360]
This was something @mystor turned us onto not long ago.  Unfortunately, I can't find the details, so I'll need to go explore and see if I can figure out exactly what's going on here...

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-44)
┆Issue Number: UNIFFI-44

**Comment by rfk** [comment]
Closing this as I don't think we have any further concrete work planned on the Gecko bindings.
