### ISSUE TITLE
Swift bindings should not generate helper methods for unused types

### ISSUE THREAD

**Issue by rfk** [mozilla/uniffi-rs#362]
The Kotlin and Python bindings inspect the set of types used by the UDL and only generate helper methods for the types that are in use. The Swift bindings unconditionally generate helpers for all primitive types.

For consistency (and potentially for a small win in the size of the final resulting artifacts) we should update the Swift bindings to avoid generating helper methods for unused types.  (And we'll need to watch out for https://github.com/mozilla/uniffi-rs/pull/357 when we do so).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-46)
┆Epic: UniFFI
┆Issue Number: UNIFFI-46
┆Sprint End Date: 2021-08-06

**Comment by rfk** [comment]
A good example of the approach needed here is the Kotlin "rust buffer helpers" template, which [iterates over all the types used by a `ComponentInterface`](https://github.com/mozilla/uniffi-rs/blob/041660d62b16b22a130361347432fc9612a26a51/uniffi_bindgen/src/bindings/kotlin/templates/RustBufferHelpers.kt#L28) and emits specialized helper code for each one.

There is a [similar Swift file](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/swift/templates/RustBufferHelper.swift) that could benefit from similar treatment, but it would also be worth grepping around in the other templates for any other places where the builtin types have code defined unconditionally.

**Comment by lougeniaC64** [comment]
@rfk Is this one still up for grabs? I can't remember if this was one that you marked for Ben.

**Comment by rfk** [comment]
IIRC Ben ended up with two of these assigned to him in Jira, this one and #460. I need to work on getting some more issues to `get involved` status!

**Comment by rfk** [comment]
> I need to work on getting some more issues to get involved status!

So it occurred to me that #442 is also a good getting-involved bug, and it would be a really nice on-ramp to the more significant change to error handling proposed in #460. @lougeniaC64 @bendk not sure who's keen to take on how much work here this sprint, but it might make sense to make (#442, #460) a pair and leave this one up for grabs.

**Comment by rfk** [comment]
(For now, assigning this to @bendk to match what's in Jira; @jdragojevic is there some setting we need to configure to allow Jira to mirror issue assignments over automatically?)

**Comment by bendk** [comment]
@rfk that plan sounds good.  I'm going to un-assign myself from this on and work on #442 instead.

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

In progress: meeting with Ryan today to discuss, seems to be straightforward although testing my changes may be interesting.
