### ISSUE TITLE
Figure out how to integrate with the megazord build system

### ISSUE THREAD

**Issue by eoger** [mozilla/uniffi-rs#38]
.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1552)

**Comment by thomcc** [comment]
Can you elaborate on the issue? This might be good for me to braindump on before I bail, but I don't really understand the question.

**Comment by eoger** [comment]
It should be solved by https://github.com/mozilla/uniffi-rs/pull/222, I can't really think of anything else we'd need to do here.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

I'm going to mark this as done based on [~eoger@mozilla.com] 's comment.  [~kcambridge@mozilla.com] pls re-open if I've missed something here.
