### ISSUE TITLE
Audit Python helper size conversions

### ISSUE THREAD

**Issue by eoger** [mozilla/uniffi-rs#39]
https://github.com/mozilla/uniffi-rs/blob/3c36c7b70c68a67c3861e4d14efc6c2857213b22/uniffi/src/bindings/python/templates/RustBufferHelper.py#L43-L44.

This looks like this corresponds to a `put_u32` on the Rust size, looking at the [Python docs](https://docs.python.org/3/library/struct.html#format-characters) it looks like we need to use `I` instead.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1551)

**Comment by rfk** [comment]
Good catch. In general, we probably need to come up with a good test suite of nested structs with different data types and test that they round-trip correctly in the various different languages.

**Comment by tarikeshaq** [comment]
This also makes me think about the unit testing story of this project... Not sure what that might look like (if it is even necessary/possible) but I'm realizing that all our tests are more or less integration tests 🤔

**Comment by rfk** [comment]
Indeed. I think a higher-than-average proportion of integration-style tests is probably inevitable here, because we really do need to test the details of cross-language integration. But we could certainly have a lot more unit-style tests than we currently do!

**Comment by rfk** [comment]
I've addressed this as part of https://github.com/mozilla/uniffi-rs/pull/214
