### ISSUE TITLE
Add support for reference arguments in the rust code

### ISSUE THREAD

**Issue by rfk** [mozilla/uniffi-rs#4]
Currently, every rust function exposed over the FFI is expected to take ownership of its arguments. This is most obvious in the existing "sprites" example, where the code for [`translate`](https://github.com/rfk/uniffi-rs/blob/f28adde220adfcb01c2732b23d7c857010a0d268/examples/sprites/src/lib.rs#L21) has to be declared as:

* `fn translate(p: Point, v: Vector) -> Point`

Which means that when the `move_to` method of the `Sprite` class calls it, it has to [pass in a clone](https://github.com/rfk/uniffi-rs/blob/f28adde220adfcb01c2732b23d7c857010a0d268/examples/sprites/src/lib.rs#L51):

* `        self.current_position = translate(self.current_position.clone(), direction)`

Making this more egonomic could be a good opportunity for somone new to the codebase to get familiar with it. The challenge would be to update the sprites example so that the `translate` function is declared as:

* `fn translate(p: &Point, v: &Vector) -> Point`

And the `.clone()` mentioned above can be removed.

In order to achieve this I think you would need to:

* Dig in to the [code that generates the ffi wrappers](https://github.com/rfk/uniffi-rs/blob/f28adde220adfcb01c2732b23d7c857010a0d268/src/scaffolding.rs#L103) that call these functions, to see where to pass the argument by reference instead of by value.
* Observe that you need some flag in the IDL to know whether to pass each argument by reference or by value, and that this will probably need to be added to the [`Argument`](https://github.com/rfk/uniffi-rs/blob/f28adde220adfcb01c2732b23d7c857010a0d268/src/interface/mod.rs#L360) struct so that it's available when you're generating the code.
* Observe that there is [some placeholder code](https://github.com/rfk/uniffi-rs/blob/f28adde220adfcb01c2732b23d7c857010a0d268/src/interface/mod.rs#L438) on the `Argument` struct that currently says "argument attributes are not yet supported", which corresponds to the [extended attributes](https://heycam.github.io/webidl/#idl-extended-attributes) feature of WebIDL.
* Experiment with adding an extended attribute to the arguments of the `translate` function in [`sprites.idl`](https://github.com/rfk/uniffi-rs/blob/master/examples/sprites/src/sprites.idl), something like `Point translate([ByRef] Point position, [ByRef] Vector direction)`.
   * I'll be totally honest, I don't know what the right syntax for this is in WebIDL, I'm just lead to believe it's possible by the fact that there's an `attributes` member on the arguments that we get back from the WebIDL parser!
   * See if you can add something that feels like a good developer experience in the IDL file, and which triggers the "argument attributes are not supported" error when you try to build the sprites example.
* Interpret the resulting argument into a flag we can set on our own `Argument` strut, then use that flag during code-gen to know whether to pass by reference.
* Make sure the sprites example still runs and outputs sensible result (in lieu of actual tests, which are forthcoming).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1567)

**Comment by linacambridge** [comment]
This isn't a Nimbus blocker, right? The fanciest data type in @tarikeshaq's proposed IDL is `ApplicationContext`, and that's a `dictionary` so it has value semantics, but just wanted to double-check!

**Comment by weslenng** [comment]
I'll try to make this issue 😉

**Comment by rfk** [comment]
Great, thanks for diving in!

> Make sure the sprites example still runs and outputs sensible result (in lieu of actual tests, which are forthcoming).

I should note, since I wrote the above, the examples have evolved into actual (if pretty minimal) tests, which will run here in CI or can be executed using `cargo test` if you have all the various command-line tools for the different target languages installed.
