### ISSUE TITLE
Eliminate re-declaration of helper structs and protocols in Swift bindings

### ISSUE THREAD

**Issue by rfk** [mozilla/uniffi-rs#408]
Writing the docs in https://github.com/mozilla/uniffi-rs/pull/405 made me realize, I think we're going to face a build issue when we come to incorporate multipe uniffied components into a single project. We should avoid this by generating unique names for all helper structs, using the component namespace as a...yeah, a namespace.

The Swift bindings for a uniffied component generate some helper C structs and declarations in a file named `uniffi_<namespace>-Bridging-Header.h`, which we expect to be `#include`d into the overall header file of the appservices megazord. If we have more than one uniffied component, then any symbol name conflicts in the generated header files risk causing errors when processing the combined header.

The template for this file is [here](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/swift/templates/Template-Bridging-Header.h) and it defines structs named `RustBuffer`, `ForeignBytes`, etc. I suspect we'll encounter problems with duplicating these definitions.

One solution would be to name them `<namespace>_RustBuffer` etc to avoid conflicts, but I'm open to other suggestions!

(The gecko-js backend has a similar problem, which IIUC it solves through a use of [C++ namespaces](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/gecko_js/templates/RustBufferHelper.h) and an [optional global name prefix](https://github.com/mozilla/uniffi-rs/blob/78af31928fa1c34a3c628bc3fd1a274313e34cc8/uniffi_bindgen/src/bindings/gecko_js/gen_gecko_js.rs#L25)).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2078)

**Comment by jhugman** [comment]
I think this issue can be be solved relatively simply with header guards.

```h
#ifndef UNIFFI_SHARED_H
#define UNIFFI_SHARED_H

// define RustBuffer, ForeignBytes, NativeRustError

#endif

// define the module specific things.
```

However, there are a host more issues around redefining Swift extensions (`Reader`, `Writer`, `ViaFfi` etc). We can likely split up the `extension` declarations (like `impl Trait for Struct`), and sprinkling some `fileprivate` around.

**Comment by rfk** [comment]
Oh, nice, I like this! A much simpler solution.
