### ISSUE TITLE
Cut a release 0.8.0

### ISSUE THREAD

**Issue by jhugman** [mozilla/uniffi-rs#412]
This is to make #409 available to application services.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2086)

**Comment by rfk** [comment]
@jhugman I invited you to be an owner of the `uniffi*` crates on crates.io, please feel empowered to go ahead and cut this release whenever you're ready.

**Comment by rfk** [comment]
(I should add, the release process documented in the readme will cut a new version and publish it to crates.io without requiring a review cycle; it's only the merge of the tagged release commit back to `main` here in github that needs a PR and review).
