### ISSUE TITLE
Kotlin Multiplatform support

### ISSUE THREAD

**Issue by ShadowJonathan** [mozilla/uniffi-rs#441]
Heya, i'm looking at uniffi's support for Kotlin, and i'm seeing quite a few imports which make me wonder if it's possible to support KMP, Kotlin Multiplatform, to be able to bind variants of the same code onto multiple platforms.

Are there any plans for this, or would this even be remotely possible?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-56)
┆Issue Number: UNIFFI-56

**Comment by rfk** [comment]
Hi @ShadowJonathan, thanks for reaching out! We don't have any particular plans to support KMP at the moment, but also I don't see any particular reason why we *couldn't* support it. I'm not very familiar with it though - if you know your way around using KMP a little bit, I'd welcome you trying out one of the small examples from this repo, seeing whether you can successfully integrate it into a KMP project, and letting us know how it works (and/or how it fails).

**Comment by benkuly** [comment]
+1 for Kotlin Multiplatform support. I'm a Kotlin Multiplatform dev and already did manual bindings for a c-library targeting JVM (using JNA), JS (using wasm) and Native on Kotlin ([see also here](https://gitlab.com/trixnity/trixnity/-/tree/main/trixnity-olm)). The problem: I never did something with Rust.

**Comment by benkuly** [comment]
The repository of Kotlin multiplatform bindings can be found [here](https://gitlab.com/trixnity/uniffi-kotlin-multiplatform-bindings). I'm not sure if it should be put it into the main repo of uniffi-rs.

**Comment by benkuly** [comment]
I thing JS bindings using WASM could be a bit more challenging, because I don't want to rebuild wasm-bindgen :thinking:

**Comment by mhammond** [comment]
> I'm not sure if it should be put it into the main repo of uniffi-rs.

Thanks for you interest! I think we'd be mildly against taking a new binding in the repo as we'd really like to have better support for bindings being external to uniffi itself (eg, see #1241 and related issues, our JS binding for desktop JS already are external, and #1200 talks about moving Ruby out). OTOH though, I think we'd probably be OK if the change to the existing Kotlin bindings were relatively small and allowed those bindings to be used in more contexts. I don't have any idea how feasible that would be though - what are your thoughts?

**Comment by benkuly** [comment]
I think we should leave it as an external project. The changes are not that small and I also have made a lot of changes to how the tests are running. So it would take a lot of time to integrate it into the uniffi-rs repository.

**Comment by benkuly** [comment]
Maybe we could mention existing external bindings in the README instead?
