### ISSUE TITLE
Propagate @ExperimentalUnsignedTypes annotations for APIs that use unsigned types

### ISSUE THREAD

**Issue by rfk** [mozilla/uniffi-rs#444]
Ref https://github.com/mozilla/application-services/issues/3957 for the source of this request.

Kotlin's unsigned types are currently experimental, and code that uses them needs to either:

* Explicitly opt-in to using the experimental feature, accepting the risk of bustage if if changes.
* Explicitly propagate the "this uses an experimental feature" flag so that downstream consumers can decide whether to opt in.

Since UniFFI generates library code that is intended for use by others, the right thing for us to do is the latter, allowing consuming code to make the final decision. In practice this means that anywhere our generated Kotlin code uses an unsigned type, should be annotated with `@ExperimentalUnsignedTypes`. If we don't, then consumers will get warnings about using the experimental unsigned types without an explicit opt-in.

In fact we already do this a little bit, as of https://github.com/mozilla/uniffi-rs/issues/216). See for example the [Kotlin RustBuffer helpers](https://github.com/mozilla/uniffi-rs/blob/9aee2083ae51fd8e3e87682a2c10370aa2213617/uniffi_bindgen/src/bindings/kotlin/templates/RustBufferHelpers.kt#L128), which explicitly tag each method for an unsigned type with the `@ExperimentalUnsignedTypes` annotation. But the current implementation does not go far enough.

As an example, for a UDL definition like this:

```
dictionary DirectlyUsesU8 {
  u8 member;
  string other;
};

dictionary RecursivelyUsesU8 {
  DirectlyUsesU8 member;
};
```

We currently generate a Kotlin wrapper that looks like:

```
data class DirectlyUsesU8 (
    val member: UByte,
    val other: String
) {
    // Omitted
}

data class RecursivelyUsesU8 (
    val member: DirectlyUsesU8 
) {
    // Omitted
}
```

But to avoid warnings when compiling the resulting Kotlin code, it should really look like:

```
@ExperimentalUnsignedTypes
data class DirectlyUsesU8 (
    val member: UByte,
    val other: String
) {
    // Omitted
}

@ExperimentalUnsignedTypes
data class RecursivelyUsesU8 (
    val member: DirectlyUsesU8 
) {
    // Omitted
}
```

This issue is about generating `@ExperimentalUnsignedTypes` annotations in the right places in the generated Kotlin code, so that:

* Components that use unsigned types will compile without any warnings about experimental types.
* Consumers of components that use unsigned types, need to explicitly opt in to that feature in order to use the component.
* Consumers of components that do *not* use unsigned types, do not need to opt in to that feature.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-58)
┆Issue Number: UNIFFI-58

**Comment by rfk** [comment]
In order to make sure I have my head around this, I made a draft of a test fixture for it over in https://github.com/mozilla/uniffi-rs/pull/445. I managed to get it to the point where the missing annotations are successfully *failing* the test case, which I figure is a good start!

**Comment by rfk** [comment]
So broadly, here's what I think we need in order to address this issue.

First, we need the ability to check whether a given interface member uses any unsigned types. This part will live in `./uniffi_bindgen/src/interface/` but could be a little awkward, as there is no "common base class" for interface members to which we could add an appropriate method. Instead we just have a [list of different types of interface member](https://github.com/mozilla/uniffi-rs/blob/9aee2083ae51fd8e3e87682a2c10370aa2213617/uniffi_bindgen/src/interface/mod.rs#L94) like `Enum`, `Record`, `Function`, etc. Probably the simplest option here will be to go through each of those structs and add a `uses_unsigned_types()` method, that knows how to recurse through the type signature of each different type of item. Not pretty, but it'll work, and trying to add it that way might uncover a better abstraction.

Next, we would need to update the [Kotlin templates](https://github.com/mozilla/uniffi-rs/blob/9aee2083ae51fd8e3e87682a2c10370aa2213617/uniffi_bindgen/src/bindings/kotlin/templates/) for each different type of interface member, adding a little header block to check whether it uses unsigned types and add `@ExperimentalUnsignedTypes` if so. Hopefully that's the easy part!

Finally, we'd need to add test coverage. I hope that #445 is a good start, but we should brainstorm other ways that an unsigned type might show up in the API and make sure they're covered as part of that fixture. UInts in enum variants? Sequences of optional UInts? And so on.

**Comment by mhammond** [comment]
Just to step back a little here:

> Since UniFFI generates library code that is intended for use by others, the right thing for us to do is the latter, allowing consuming code to make the final decision.

What "final decision" can it make here? Ultimately, it has the choice "use the experimental types" or "don't use the component", right? If they really are the only choices, the above scheme seems overly elaborate for that.

**Comment by rfk** [comment]
> What "final decision" can it make here? Ultimately, it has the choice "use the experimental types" or "don't use the component", right?

Yes. Or more likely: "use the component without opting in to the experimental types, and get a bunch of compiler warnings, that are ignored".

Perhaps there's a simpler scheme, along the lines of:

* Check whether anything in the component API uses an unsigned type (which we can do using the existing `TypeUniverse`).
* If so, emit some global annotation that applies `@ExperimentalUnsignedTypes` to the whole component.

I have not played around with `@ExperimentalUnsignedTypes` to see whether that's possible, although a quick glance seemed to suggest that it might not be.

I'm fairly strongly of the opinion that we should not set the opt-in ourselves, mostly because it seems rude to do that from library code; but as always, I'm open to being convinced that it's a better set of tradeoffs in practice.

**Comment by rfk** [comment]
(To be clear, I'm leaning on the notes from https://github.com/mozilla/uniffi-rs/issues/216#issuecomment-675671219 about what the abstract "Right Thing" is for Kotlin consumers)

**Comment by rfk** [comment]
Interestingly, reading [this reference](https://github.com/Kotlin/KEEP/blob/master/proposals/experimental.md) suggests that a third decision available to the consumer is "don't use the parts of the component API that contain unsigned integers", which I hadn't previously understood as a viable option.

**Comment by mhammond** [comment]
> I'm fairly strongly of the opinion that we should not set the opt-in ourselves, mostly because it seems rude to do that from library code

I agree with that - I guess I just wonder how much hand-holding we really need to give them. ISTM that the flow is something like (a) start to use component, (b) notice warnings, (c) decide if the appropriate course is to not use it, or to disable the warnings. The consumer remains completely in control and we don't need to do anything (well, other than explicitly opting in, which is still required in all scenarios)

I guess I'm really not seeing what practical benefits the scheme above offers over "do nothing"? I'm sure I'm just not seeing it though.

> a third decision available to the consumer is "don't use the parts of the component API that contain unsigned integers", which I hadn't previously understood as a viable option.

That would be cool and I can see extra value there (but it doesn't look completely trivial)

**Comment by rfk** [comment]
> I guess I'm really not seeing what practical benefits the scheme above offers over "do nothing"?
> I'm sure I'm just not seeing it though.

If we do nothing, then compiling the Kotlin code for our components will produce the "uses experimental features" warnings, which IIUC will currently fail our build in appservices because we have `-Werror`. The scheme proposed here has the effect of moving the warnings from our code to the consumer's code, which is better positioned to do something about them.

Another possible framing: the code produced by UniFFI should not produce any compiler warnings, but it currently does when using unsigned types.

**Comment by mhammond** [comment]
I don't want to beat a dead horse here and certainly don't object to any path forward, but just to clear up my misunderstanding:

> If we do nothing, then compiling the Kotlin code for our components will produce the "uses experimental features" warnings, which IIUC will currently fail our build in appservices because we have `-Werror`.

Isn't that still true if we do nothing? ie, that appservices will fail to build in both scenarios, and appservices is forced to take some (the same?) action to silence these warnings? I get that *conceptually* your proposal is cleaner, I'm just failing to see what's different about what action appservices would take in each scenario.

**Comment by rfk** [comment]
> Isn't that still true if we do nothing?

I don't think so, but it's entirely possible that I misunderstand (either the behaviour of the system, or what you mean when you say "do nothing").

Right now, Sammy's uniffication of the logins component has to [opt in to the unsigned types](https://github.com/mozilla/application-services/pull/4068/files#diff-330a702e658397591f0928dae3969068b2c31fb811239ea261232aad1e1e908bR53) in order to build successfully. I don't think we should be doing that.

My expectation is that if we make this proposed fix in UniFFI, then we can remove that opt-in and the appservices code will compile without warnings. Developers of future components would not have to worry about the opt-in at all, and would just propagate it to consumers automatically. In other words, we won't have to take any action to silence the warnings, because there won't be any warnings, because the generated code is declaring its intentions explicitly.

If we do nothing, then developers of any future components that use unsigned types will have to have some handling of the opt-in in their gradle files in order to deal with the warnings, just like the one currently in that PR.

**Comment by mhammond** [comment]
doh! I see, sorry - appservices *isn't* the consumer here. IIUC, "do nothing" means "app-services opts in, a-c/fenix does nothing". Your proposal means "app-services does nothing, fenix opts in".

Sorry for the noise.

**Comment by rfk** [comment]
> "do nothing" means "app-services opts in, a-c/fenix does nothing". Your proposal means "app-services does nothing, fenix opts in".

Just to close the loop: yes, this maps well to my mental model here 👍🏻. Also, Fenix opts in once, instead once per component.

Thanks as always; it's good to talk these things through *before* writing a bunch of code instead of after!

**Comment by rfk** [comment]
> First, we need the ability to check whether a given interface member uses any unsigned types. This part will live in
> ./uniffi_bindgen/src/interface/ but could be a little awkward, as there is no "common base class" for interface members
> to which we could add an appropriate method. 

I added something similar to this over in https://github.com/mozilla/uniffi-rs/pull/462, in the `ComponentInterface::type_contains_object_references` method and its friends. I can imagine a similar approach working out for something like `ComponentInterface::type_contains_unsigned_integers`, with similar levels of *"hrm this abstraction feels a bit weird but it's not too bad and doing much better would need a broader refactor..."* attached.
