### ISSUE TITLE
Remove support for non-threadsafe interfaces

### ISSUE THREAD

**Issue by rfk** [mozilla/uniffi-rs#449]
In #429 we officially deprecated the use of non-threadsafe interfaces; currently all interfaces are expected to have an explicit `[Threadsafe]` attribute and we'll issue a warning if they don't.

Per [ADR-0004](https://github.com/mozilla/uniffi-rs/blob/main/docs/adr/0004-only-threadsafe-interfaces.md), the intended end state is for all interfaces to be thread-safe by default, regardless of the presence of a `[Threadsafe]` attribute. This issue tracks the remaining work of getting to that state, which includes:

* [x] Cut at least one release with the deprecation notice for non-threadsafe interfaces in place.
* [ ] Audit all known internal consumers to make sure they've updated to using `[Threadsafe]`.
* [ ] Implement the removal, which will involve:
  * [ ] Removing the existing deprecation notice on non-threadsafe interfaces.
  * [ ] Deleting the `Object::threadsafe` method.
  * [ ] Finding all the places where we branch on `obj.threadsafe()`, and deleting the falsey branch.
  * [ ] Adding a new deprecation notice that warns when `[Threadsafe]` is present, since it's now redundant and confusing.
  * [ ] Simplifying the current "threadsafe" example and moving it into the test-fixtures directory
  * [ ] Updating our other examples so they don't give deprecation warnings.
* [ ] Cut at least one release with the new deprecation notice in place.
* [ ] Eventually, entirely remove support the for the `[Threadsafe]` attribute, making it a syntax error.

I'd like to treat this removal as a blocker for landing the Arc-pointer conversation proposed in [ADR-0005](https://github.com/mozilla/uniffi-rs/pull/430), so that we don't need to add code for wrapping non-threadsafe interfaces in a `Mutex` before putting them in an `Arc`.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2218)

**Comment by mhammond** [comment]
This sounds great!

>     * [ ]  Cut at least one release with the new deprecation notice in place.

I agree `[Threadsafe]` will be confusing, but because it will not cause harm it might be fine to delay that new deprecation notice. In particular, I expect that if we release 2 new versions in just a couple of weeks, external users will skip right over the intermediate. Not too bothered though.

**Comment by rfk** [comment]
>  Cut at least one release with the deprecation notice for non-threadsafe interfaces in place.

I'm going to go ahead and do this right now.

> In particular, I expect that if we release 2 new versions in just a couple of weeks, external users will skip right over the intermediate.

Yes, good point.

**Comment by rfk** [comment]
>  Cut at least one release with the deprecation notice for non-threadsafe interfaces in place.

I've released v0.9.0 with this in place, ref https://github.com/mozilla/uniffi-rs/pull/450
