### ISSUE TITLE
Proposal: Adding Mutability to Swift structs

### ISSUE THREAD

**Issue by skhamis** [mozilla/uniffi-rs#471]
## Problem

Uniffi currently generates structs in Swift with the keyword `let` which evaluates as a constant and `var` which is the mutable counterpart. [Swift documentation on var vs let](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html#ID310)

This is currently happening in the current uniffi work https://github.com/mozilla-mobile/firefox-ios/pull/8602 where I need to construct an entirely new struct to change a couple of variables inside. While not terrible, it does leave potential room for improvement. The actual "fix": https://github.com/mozilla-mobile/firefox-ios/pull/8602/commits/54cee20b10a249f37167b8e2fba6c4a69ee68317

## Solution

Since this is swift specific it might be harder to propose any solution in the UDL without mucking things up. However there seems to be two paths:

1. In the UDL have a decorator that can specify potential language-specific needs while keeping the verbose-ness of the current UDL style:
    - something like `[Mutable]` since almost all supported languages have equivalent of mutable/immutable

2. After briefly discussing this issue with @rfk, another (probably much better) option is to default swift structs to be `var` instead of `let` to allow mutability by default. However that comes with it's own potential paths to think through.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2234)

**Comment by rfk** [comment]
FWIW the Kotlin bindings have a similar property, using `val` instead of `var` and thus creating immutable properties.

I think I'm lightly +1 on allowing these properties to be mutable by default. One risk could be if consumers expect the mutations to somehow be automatically reflected in an underlying object in the Rust code, but given the current shape of our APIs that doesn't seem too likely.

**Comment by rfk** [comment]
If you wanted to play around with this in a local build, I *think* it could be as small as changing `let` to `var` in the Swift Record template [here](https://github.com/mozilla/uniffi-rs/blob/66de08450b9df8447278c7106dfa99f863f9c2ac/uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift#L3) and `val` to `var` in the Kotlin Record template [here](https://github.com/mozilla/uniffi-rs/blob/66de08450b9df8447278c7106dfa99f863f9c2ac/uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt#L3).

**Comment by skhamis** [comment]
> If you wanted to play around with this in a local build, I _think_ it could be as small as changing `let` to `var` in the Swift Record template [here](https://github.com/mozilla/uniffi-rs/blob/66de08450b9df8447278c7106dfa99f863f9c2ac/uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift#L3) and `val` to `var` in the Kotlin Record template [here](https://github.com/mozilla/uniffi-rs/blob/66de08450b9df8447278c7106dfa99f863f9c2ac/uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt#L3).

Will do! Seems pretty simple enough to test out -- though I think you're right that currently this shouldn't be a problem (though the future always holds nice surprises). 

I do think having an _option_ to design the structs to be immutable/mutable (maybe mutable by default with the decorator allowing immutability `[Const]` from my brief IDL lookup) might allow nice flexibility for API creators that want more control over the design of the struct. Though I do concede that I don't necessarily have a concrete example use cases for switching between the two.

**Comment by rfk** [comment]
@skhamis and I chatted about this, and the downsides of just going ahead and making this change seem pretty small. I don't think we currently have any places where consumers might risk forming an incorrect mental model of how mutating a returned data structure would affect the broader system. Ref https://github.com/mozilla/uniffi-rs/pull/474 for the implementation.

**Comment by rfk** [comment]
@skhamis, would you like to try cutting a new UniFFI release in order to make this available for your use in appservices? I'm curious to see how well the release-cutting notes in the README stand up to execution by someone other than me.

**Comment by skhamis** [comment]
@rfk, Definitely will give it a shot tomorrow morning and let you know how it goes!
