### ISSUE TITLE
`./automation/prepare-release.py` doesn't seem to work properly when used to cut a hotfix release

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/uniffi-rs#90]
Or perhaps the steps for cutting a hotfix in the "how to cut a release" guide are incomplete/wrong. https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md#make-a-new-point-release-from-an-existing-release-that-is-behind-latest-main

Following them ended up with https://github.com/mozilla/application-services/compare/release-v61.0.x...cut-v61.0.8 being produced which didn't have any of the cherry-commits from my fixes-for-v61.0.8 branch.

**Comment by thomcc** [comment]
I don't seem to have the ability to unassign this bug from myself, but given, ahem, circumstances...
