### ISSUE TITLE
Update Jira Triage instructions post migration to Jira Cloud

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/uniffi-rs#970]
I'm not going to take any action here until the dust settles from the migration, but wanted to note that some of the instructions in the [SACI Triage Rotation Guide](https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=CLOUDSERVICES&title=SACI+Triage+Rotation) will need to be updated for the new Jira setup. In particular:

* There's a not about old Bugzilla bugs being automatically synced to Jira when we update them in Bugzilla. Is this still true, and still relevant?
* There's a "Jira incoming issues" query which goes to a board that doesn't exist. What the right triage view for new Jira issues in the new world?

**Comment by rfk** [comment]
Bad bot.

/cc @jdragojevic for visibility, I created this in Jira and it was mirrored over to the uniffi-rs repo despite automations (I think?) being paused.

**Comment by jdragojevic** [comment]
closing - this exists in jira and need not live elsewhere.
