### ISSUE TITLE
Audit runtime assertions to ensure they have identifying error messages

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/uniffi-rs#971]
A recent Fenix crasher was hard to debug because it was due to a failing runtime assertion, but the error message didn't provide enough context to uniquely identify the source of the error. Let's audit our existing runtime assertions and provide each with a unique error message so that they can be more easily tracked down if they start failing.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-1)
┆Issue Number: UNIFFI-1

**Comment by rfk** [comment]
This is an appservices bug.
