### ISSUE TITLE
Alternative for missing annotations for unsigned integer usage

### ISSUE THREAD

**Issue by badboy** [mozilla/uniffi-rs#976]
I'd like to make use of unsigned integers in our API.
These are currently experimental in Kotlin and thus need a `@ExperimentalUnsignedTypes` annotation wherever they are used to avoid warnings.
This is currently [done in a few places](https://github.com/mozilla/uniffi-rs/blob/edce7c8c315c5292afebbc4980b20789c2701852/uniffi_bindgen/src/bindings/kotlin/templates/RustBufferHelpers.kt#L128), but that's not enough when user code uses it.

I tried adding more annotations by introducing helpers to add that wherever a user-specified type is used, but it's ... a lot.

There's a way to enable it for everything in the project through gradle:

```gradle
allprojects {
   tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
        kotlinOptions {
            freeCompilerArgs += [
                "-Xuse-experimental=kotlin.ExperimentalUnsignedTypes",
            ]
        }
    }
}
```

This needs to be added to the user's `build.gradle`.

Should I document this in the manual?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-69)
┆Issue Number: UNIFFI-69

**Comment by rfk** [comment]
@skhamis is working on adding more annotations over in https://github.com/mozilla/uniffi-rs/pull/977, but even with those annotations in place IIUC consumers still need to do an explicit opt-in. If you feel so inspired, please do add this in the Kotlin section of the manual. Thanks!
